"""The oracle packet: what the night hands to whoever builds the game.

    oracle_packet/
      GAME_DESCRIPTION.md   the design, for a human or an AI engineer to read
      design_profile.json   the same as data, with the evidence behind it
      prophecy.md           what the player was told (the visions are promises)
      BUILDER_PROMPT.md     the instruction to give an AI engineer, ready to paste
      transcript.md         the night itself (local; it is the player's own words)
      AI_GAME_DEVELOPMENT_MANUAL.md   a copy of the process manual's core, when one is found
      manual/                         its reference files, opened by section

`GAME_DESCRIPTION.md` is the "simple English prompt" the manual asks for, grown
up: it replaces a one-line pitch with a design derived from play.
"""

from __future__ import annotations

import json
import shutil
import time
from pathlib import Path

from . import __version__
from .content import Registry
from .model import PlayerModel
from .session import Session, packets_dir
from .synthesis import build_profile

MANUAL_NAME = "AI_GAME_DEVELOPMENT_MANUAL.md"
REFERENCE_DIR = "manual"          # the manual's reference files, in a folder beside its core


def find_manual(explicit: str | None = None) -> Path | None:
    """The process manual, if this copy of the oracle lives beside one."""
    if explicit:
        path = Path(explicit)
        return path if path.is_file() else None
    here = Path(__file__).resolve().parent
    for base in (here.parent, Path.cwd()):
        candidate = base / "docs" / MANUAL_NAME
        if candidate.is_file():
            return candidate
    return None


def _bullets(items) -> str:
    return "\n".join(f"- {i}" for i in items) if items else "- (none)"


def _signal_block(entry: dict) -> str:
    lines = [f"**{entry.get('signal', '').strip()}**"]
    if entry.get("evidence"):
        lines.append("  - Seen when the player: " + "; ".join(str(e) for e in entry["evidence"]))
    lines.append(f"  - Therefore: {entry.get('design_consequence', '').strip()}")
    return "- " + "\n".join(lines)


def game_description(registry: Registry, session: Session, synthesis: dict) -> str:
    d, p = synthesis["design"], synthesis["prophecy"]
    imp = registry.implications
    labels = {f["id"]: f["label"] for f in imp["gdv_fields"]}
    sources = (synthesis.get("draft") or {}).get("gdv_sources", {})
    by_rules = synthesis["source"]["design"].startswith("rules")
    sig = d["design_signals"]
    pc = sig.get("productive_contradiction") or {}
    out = [f"# {d['working_title']}", "",
           "Evidence class: **INERT** (an oracle packet: a design brief derived from play, not proof of anything)", "",
           f"Generated by THE BLANK DECK {__version__} on {time.strftime('%Y-%m-%d')} from session "
           f"{session.id} ({session.turn} turns, {len(session.world.summaries)} chambers; narrated by "
           f"{session.config.get('backend_used', 'offline')}; designed by {synthesis['source']['design']}).", "",
           "This is the creator's prompt for one small game. It did not come from a sentence; it came from "
           "watching how one person plays. It describes play preferences only, and says where it does not know.", "",
           "## The prompt", "",
           f"> Build me **{d['working_title']}**: {d['pitch']}", "",
           "## What the design stands on", "",
           "Three dominant signals, two secondary, one productive contradiction. Everything else is quiet on purpose.", "",
           "### Dominant", ""]
    out += [_signal_block(e) for e in sig.get("dominant", [])] or ["- (the night gave too little evidence for a dominant signal)"]
    out += ["", "### Secondary", ""]
    out += [_signal_block(e) for e in sig.get("secondary", [])] or ["- (none)"]
    out += ["", "### The productive contradiction", ""]
    if pc.get("between"):
        out.append(f"- Between **{pc['between'][0]}** and **{pc['between'][-1]}**.")
        if pc.get("evidence"):
            out.append("  - Seen when the player: " + "; ".join(str(e) for e in pc["evidence"]))
    out.append(f"- Resolution: {pc.get('resolution', '')}")
    out += ["", "## Design implications", "",
            "Each is a design consequence, not a score. Each must be true of the finished game.", "",
            _bullets(d["design_implications"]), "",
            "## Game Design Vector", "",
            "| Field | Value | From |", "|---|---|---|"]
    for key, value in d["game_design_vector"].items():
        origin = sources.get(key, "") if by_rules else "designer"
        out.append(f"| {labels.get(key, key)} | {str(value).replace('|', '/')} | {origin} |")
    out += ["", "A value that begins with *unknown* or that came from *default* was not evidenced: the builder "
                "chooses, within the scope constraints, and records the choice.", "",
            "## Negative constraints", "",
            "What the game must not contain is as binding as what it must.", "",
            _bullets(d["negative_constraints"]), "",
            "## Personal callbacks", "",
            "Transformed echoes of what this player did. They must be present and recognisable.", ""]
    out += [f"- From: {c['from']}\n  - Becomes: {c['becomes']}" for c in d["personal_callbacks"]] or ["- (none)"]
    un = d["unrequested_feature"]
    out += ["", "## The feature nobody asked for", "",
            f"- {un['feature']}", f"  - It follows from: {un['follows_from']}", "",
            "## What is not known", "",
            _bullets(d.get("unknowns") or ["Nothing material."]), "",
            "## The prophecy (promises already made to the player)", "",
            "The player has been told these. Each must be visibly true in the finished game.", "",
            "| Card | The player was told | What makes it true |", "|---|---|---|"]
    for v in p["visions"]:
        out.append(f"| {v['card']} | {v['text'].replace('|', '/')} | {str(v.get('fulfils') or '').replace('|', '/')} |")
    out += ["", "## Scope constraints", "", imp["scope"]["summary"], "",
            _bullets(imp["scope"]["constraints"]), "",
            "## How to build from this", "",
            "Give `BUILDER_PROMPT.md` to the AI engineer, in a directory that contains this `oracle_packet/` "
            "folder. If the process manual is present, the builder reads its operating core in full and "
            "follows its section 5.8, which treats this packet as the creator's prompt and the visions as "
            "acceptance criteria.", ""]
    return "\n".join(out)


def prophecy_markdown(synthesis: dict) -> str:
    p = synthesis["prophecy"]
    out = ["# The reading", "", p["address"], ""]
    out += [f"- {r}" for r in p["recollections"]]
    out.append("")
    for v in p["visions"]:
        out += [f"**{v['card']}**", "", v["text"], ""]
    out += [f"**{p['pronouncement']}**", "", p["final_line"], ""]
    return "\n".join(out)


def builder_prompt(registry: Registry, synthesis: dict, manual_present: bool) -> str:
    imp = registry.implications
    if manual_present:
        manual_line = (f"`oracle_packet/{MANUAL_NAME}`: the operating core of the process manual. Read it in "
                       "full; it is short. Then follow section 5.8 (the oracle front door), which is in "
                       f"`oracle_packet/{REFERENCE_DIR}/REF_PROCESS.md` when the reference was copied with the "
                       "core. Open the other reference files only when the core sends you to a section; "
                       "templates are in section 21.")
    else:
        manual_line = ("The AI game development manual, if you have been given one: follow its section on "
                       "starting from an oracle packet. If you have not, work in this order: write a one-page "
                       "covenant from the packet, create the project, make it run, make the core verb "
                       "playable, complete one loop, then fulfil the visions one by one, testing as you go.")
    scope = "\n".join(f"  - {c}" for c in imp["scope"]["constraints"])
    return (registry.texts["builder_prompt"]
            .replace("{{TITLE}}", synthesis["design"]["working_title"])
            .replace("{{MANUAL_LINE}}", manual_line)
            .replace("{{SCOPE}}", scope))


def transcript_markdown(session: Session) -> str:
    out = [f"# The night ({session.id})", "",
           "The player's own words and the house's answers. Kept on this computer only.", ""]
    for t in session.transcript:
        if t["role"] == "player":
            out += [f"> {t['text']}", ""]
        else:
            out += [t["text"], ""]
    return "\n".join(out)


def write_packet(registry: Registry, model: PlayerModel, session: Session, synthesis: dict,
                 out_dir: str | None = None, manual: str | None = None) -> Path:
    base = Path(out_dir) if out_dir else packets_dir() / session.id
    packet = base / "oracle_packet"
    packet.mkdir(parents=True, exist_ok=True)
    manual_path = find_manual(manual)
    files = {
        "GAME_DESCRIPTION.md": game_description(registry, session, synthesis),
        "design_profile.json": json.dumps(build_profile(registry, model, session, synthesis), indent=2,
                                          ensure_ascii=False),
        "prophecy.md": prophecy_markdown(synthesis),
        "BUILDER_PROMPT.md": builder_prompt(registry, synthesis, manual_path is not None),
        "transcript.md": transcript_markdown(session),
    }
    for name, text in files.items():
        (packet / name).write_text(text, encoding="utf-8", newline="\n")
    if manual_path is not None:
        shutil.copyfile(manual_path, packet / MANUAL_NAME)
        # The core is read in full; its reference files are opened by section and travel with it.
        reference = manual_path.parent / REFERENCE_DIR
        if reference.is_dir():
            (packet / REFERENCE_DIR).mkdir(exist_ok=True)
            for item in sorted(reference.glob("*.md")):
                shutil.copyfile(item, packet / REFERENCE_DIR / item.name)
    session.packet_dir = str(packet)
    return packet
