"""Render the modelling/texturing brief from a ranking. Prose comes from the critiques."""

from __future__ import annotations


def _bullets(items) -> str:
    items = [str(i).strip() for i in (items or []) if str(i).strip()]
    return "\n".join(f"  - {i}" for i in items) if items else "  - (none recorded)"


def render_brief(ranked: list[dict], title_date: str, preface: str = "") -> str:
    lines = [
        f"# Prop modelling and texturing brief - {title_date}",
        "",
        "Evidence class: **BRIEF - INERT - PROMOTES NOTHING**",
        "",
    ]
    if preface.strip():
        lines += [preface.rstrip(), ""]
    lines += [
        "Generated by `tools/prop_reference` from the warehouse manifest, the",
        "licence-clean Wikimedia Commons references, and the per-specimen",
        "critiques. Priority is deterministic: tier weight x installed factor x",
        "measured gap, discounted for families a completed review already served",
        "(see `tools/prop_reference/priority.py`). The photographs and the",
        "reference sheets live outside git under `art/reference/props/_fetched`;",
        "references are cited by Commons URL and licence.",
        "",
        "Rules that bind every item below, from `design/PROP_ART_BRIEF.md`: props",
        "are GDScript primitives, not imported meshes; new material keys go in",
        "`MATERIAL_CATALOG` in `gen_layout.py` and through `ingest_material_sources.py`",
        "(`SLOTS` + `GODOT_STAGE`) or they stay flat colour; verify by rendering,",
        "never by reading code; horizontal metal uses `brass_dull`, polished brass",
        "only vertical or hand-touched.",
        "",
        "## Priority table",
        "",
        "| # | priority | kind | variant | installed | tier | gap | flat colour | effort h |",
        "|---:|---:|---|---|---:|---|---:|---:|---:|",
    ]
    assessable = [r for r in ranked if not r["score"].get("not_assessable")]
    apart = [r for r in ranked if r["score"].get("not_assessable")]
    for row in assessable:
        s = row["score"]
        c = row.get("critique") or {}
        lines.append(f"| {row['rank']} | {s['priority']:.2f} | {row['kind']} | {row['label']} | "
                     f"{row['installed_count']} | {row['tier']} | {s['gap']:.2f} | "
                     f"{int(round(100 * row['flat_colour_share']))}% | {c.get('effort_hours', '')} |")
    if apart:
        lines += ["", "## Not assessable in the shed", "",
                  "These kinds drew nothing standalone: their visible geometry comes from the",
                  "layout pass, not the script, so no comparison was possible. The finding is",
                  "about their inspection registration, not their modelling.", ""]
        for row in apart:
            c = row.get("critique") or {}
            lines.append(f"- **{row['kind']}** ({row['label']}): {c.get('summary', 'no critique recorded')}")
    lines += ["", "## Specimens, in priority order", ""]
    for row in assessable:
        c = row.get("critique") or {}
        size = row.get("size_m") or [0, 0, 0]
        lines += [
            f"### {row['rank']}. {row['kind']} - {row['label']}",
            "",
            f"- **Priority** {row['score']['priority']:.2f} (gap {row['score']['gap']:.2f}, tier {row['tier']}, "
            f"installed {row['installed_count']}, review discount {row['score']['review_discount']})",
            f"- **What we have:** {size[0]:.2f} x {size[1]:.2f} x {size[2]:.2f} m, {row['mount']} mount, "
            f"{row['triangles']} triangles, {row['surfaces']} surfaces, "
            f"{int(round(100 * row['flat_colour_share']))}% flat colour",
            f"- **Real object:** {row.get('real_object', '')}",
            f"- **Confidence:** {c.get('confidence', 'no critique')}",
            "",
            f"{c.get('summary', '_No critique recorded for this specimen._')}",
            "",
            "**Modelling**",
            "",
            _bullets(c.get("modelling")),
            "",
            "**Texturing**",
            "",
            _bullets(c.get("texturing")),
            "",
            "**References used**",
            "",
            _bullets([f"{r.get('title', '')} - {r.get('licence', '')} - {r.get('url', '')}"
                      for r in row.get("references", [])]),
            "",
        ]
    return "\n".join(lines) + "\n"
