"""Export a human-readable recording script from a case dialogue tree.

Every node id in the tree is a take id (<voice_prefix><node>.ogg), so the
recording session and the importer agree on names by construction. Player
choice labels are listed as context only — they are never voiced.

    python art/tools/export_voice_script.py
        reads  game/data/case01_dialogue.json
        writes design/case01_recording_script.md
"""
import json
import os

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", ".."))
TREE = os.path.join(ROOT, "game", "data", "case01_dialogue.json")
OUT = os.path.join(ROOT, "design", "case01_recording_script.md")


def main() -> None:
    with open(TREE, encoding="utf-8") as fh:
        tree = json.load(fh)
    meta = tree.get("meta", {})
    prefix = meta.get("voice_prefix", "")
    speaker = meta.get("speaker_default", "")
    entries = tree.get("entries", {})
    entry_of = {node: key for key, node in entries.items()}
    lines = [
        "# Case 01 recording script — %s" % speaker.title(),
        "",
        "Generated by `python art/tools/export_voice_script.py` — do not",
        "hand-edit; re-run after any change to `game/data/case01_dialogue.json`.",
        "",
        "One take per node. **The filename is the contract**: deliver",
        "`%s<node>.ogg` (or any format; the importer converts). Raw takes go" % prefix,
        "in `game/assets/audio/voice/source/`, then run",
        "`python art/tools/import_voice_takes.py`.",
        "",
        "ALL-CAPS runs inside a line are captions Mina reads aloud — flat,",
        "clerical, faster than her natural voice. An ellipsis at the start of",
        "a line is a held beat, not a trail-off.",
        "",
    ]
    for node_id, node in tree.get("nodes", {}).items():
        take = "%s%s.ogg" % (prefix, node_id)
        lines.append("## %s" % take)
        if node_id in entry_of:
            lines.append("*(entry point: %s)*" % entry_of[node_id])
        lines.append("")
        lines.append("> %s" % node["line"])
        lines.append("")
        answered = [str(c.get("label", "")) for c in node.get("choices", [])]
        if answered:
            lines.append("*Player may answer: %s*" % " / ".join(
                "“%s”" % a for a in answered))
        if "silence_goto" in node:
            lines.append("*The player may also say nothing.*")
        if answered or "silence_goto" in node:
            lines.append("")
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines))
    print("wrote %s (%d takes)" % (OUT, len(tree.get("nodes", {}))))


if __name__ == "__main__":
    main()
