"""Changes raised by the image review of the contact sheets (after the room
content was drafted from canon and data). Keyed by area id; the builder appends
them to that area's numbered changes. Ids are explicit and stable. Each cites
the sheet tile that shows the problem.
"""
from _common import *

ADDENDA = {
    # ------------------------------------------------------------- B1
    "B1_COAL_ROOM": [change("B1_COAL_ROOM-002", "P1", "refine", "Chute must terminate at the bunker", objects=["B1_COAL_BUNKER chute (orison_v2_coal_delivery.gd)"], placement="Chute mouth seated on the bunker's board gate; the gravity run continuous from the street cover", purpose="Review: the chute ends in air about 0.5 m above the floor (OV/DT). Accord 11: nothing floats, everything terminates", sources=["design/ORISON_V2_COAL_DELIVERY_PROGRESS_2026-09-26.md", "game/scripts/building/orison_v2_coal_delivery.gd"], acceptance="Chute detail station shows the mouth seated"),
                     change("B1_COAL_ROOM-003", "P2", "refine", "Heap as geometry, not a decal; dust on the whitewash", objects=["B1_COAL_HEAP_0..13 fixtures"], purpose="Review: the room is spotless and blown out with a decal-based heap; the coal room is the dirtiest room in the building", sources=["art/blender/basement_fabrication.md (Blender coal pile)"], acceptance="OV reads a heap with an angle of repose and grime on the walls")],
    "B1_ELECTRICAL": [change("B1_ELECTRICAL-003", "P1", "add", "Conduit in and out of the fuse panel", objects=["B1_FUSE_PANEL: a riser conduit from the floor into the panel's bottom and a trunk out of the top to the ceiling with a junction box"], purpose="Review: the panel has no conduit in or out (DT). Accord 11: every wire has origin, path, destination", sources=["game/scripts/props/fuse_panel_prop.gd", "G05 sources"], preserve="Panel working front and activity", acceptance="Panel detail station")],
    "B1_BOILER_ROOM": [change("B1_BOILER_ROOM-003", "P2", "add", "Two cage bulbs over the firing aisle", objects=["new: two cage_bulb fixtures (fixed_lighting family) over the west control aisle, switched with the room"], purpose="Review: near-black in every detail tile; the firing door, gauge glass and controls are not legible without the lamp. L9 allows a boiler room to be dark, not unworkable", sources=["TASKS.md L9", "art/blender/fixed_lighting.md"], preserve="16/16 light budget: name the victim or make these two unlit visuals with a warm emissive if the budget is full", acceptance="Firing-door detail station readable with the lamp off")],
    "B1_RESIDENT_STORAGE": [change("B1_RESIDENT_STORAGE-003", "P1", "refine", "Bay labels single-sided and seated on the bay fronts", objects=["B1_STORAGE_BAYS Label3D bay labels"], purpose="Review: labels read mirrored from behind and float as glyphs along the aisle", sources=["game/scripts/building/orison_v2_basement.gd"], acceptance="Aisle stations show labels only on bay fronts, never mirrored")],
    "B1_LAUNDRY": [change("B1_LAUNDRY-004", "P1", "add", "Supply, taps and drains for the tubs and washers", objects=["new: a cold and hot pair over each rinse tub, a drain under each, a hose from the wall cocks to the washer feed (laundry_apparatus family)"], purpose="Review: the tubs and washers have no supply, taps or drains. Accord 11; the washers' CocksReach and DrainReach already exist as controls and need the pipes they imply", sources=["art/blender/laundry_apparatus.md", "art/blender/heating_distribution.md"], preserve="Washer reach areas", acceptance="Tub detail station shows taps and a drain")],
    "B1_PUBLIC_CORE": [change("B1_PUBLIC_CORE-003", "P2", "refine", "Orange light leak at the pier seam", objects=["pier/wall seam beside the stair foot (DT1)"], purpose="Review: a hard orange light leaks through the seam; close the geometry or clamp the voxel field there", acceptance="DT1 station without the leak")],

    # ------------------------------------------------------------- F01
    "F01_A_KITCHEN": [change("F01_A_KITCHEN-004", "P1", "refine", "No range visible in any tile; verify the native range mounts", objects=["F01_1A_STOVE_01 (household_stoves.json lists the instance; the sink frame, wall cupboard and monitor-top are the only fittings in the five tiles)"], construction="Confirm the HouseholdGasRange instance for 1A instantiates at its fitting and is not seated inside the wall or behind the hall opening; the frames are identical to 3D's kitchen, so the template placement is shared", purpose="Review: no range seen; Appliance Bible: 17 kitchens have an enamel gas range", sources=["game/data/orison_v2/household_stoves.json", "game/data/orison_v2/completion_interiors.json fittings", "art/blender/household_stoves.md"], acceptance="Kitchen OV shows the range in a station that covers the fourth wall; stove module unchanged at 18 instances"),
                      change("F01_A_KITCHEN-005", "P3", "keep", "The ringed dome is the monitor-top's compressor: correct for 1A", objects=["F01_1A_FRIDGE_01 (FridgeMonitor)"], purpose="The review read the GE-pattern drum as an unidentified cabinet; it is the Appliance Bible's monitor-top and 1A is one of the four electric flats", sources=["design/ORISON_APPLIANCE_BIBLE.md I"], acceptance="Unchanged")],
    "F01_D_KITCHEN": [change("F01_D_KITCHEN-004", "P2", "refine", "Sourceless blue-white light on the range top", objects=["F01_1D_STOVE_01 ambient / a stray light"], purpose="Review: an unexplained blue-white light on the range top; Accord 15", acceptance="Range detail without the glow")],
    "F01_PUBLIC_CORE": [change("F01_PUBLIC_CORE-003", "P1", "remove", "Exposed blockout plane in the core", objects=["the flat orange-tan plane targeted by DT1-3 (OrisonV2Blockout / ServiceAlley / readability cue nodes)"], purpose="Review: a block-out plane is visible in the public core at eye level", acceptance="Core detail stations show finished surfaces only")],
    "F01_SERVICE_CORE": [change("F01_SERVICE_CORE-003", "P1", "refine", "Untextured door slab and grey placeholder panel", objects=["F01_SERVICE_CORE_DOOR leaf; the flat grey panel on the landing"], purpose="Review: an untextured wood slab and a grey placeholder at the service core", acceptance="Threshold and overview show a finished door and no panel")],
    "F01_VESTIBULE": [change("F01_VESTIBULE-002", "P2", "refine", "Street sign reads reversed from inside", objects=["FrontDoorExteriorSign / entry sign Label3D double-sided"], purpose="Review: the sign's lettering is mirrored through the glass; make the Label3D single-sided with an opaque back", acceptance="Vestibule OV shows no mirrored lettering")],
    "F01_LOBBY": [change("F01_LOBBY-005", "P2", "refine", "Yellow numbered placard and the white brick patch", objects=["the yellow numbered floor placard; the white brick texture patch on the lobby wall (review)"], purpose="A modern wayfinding placard and a texture patch in the lobby; replace the placard with the enamel plate family and close the patch", sources=["art/blender/wayfinding_plate.md"], acceptance="Lobby OV")],
    "F01_COMMON_B": [change("F01_COMMON_B-003", "P2", "refine", "Windows look onto an unfinished grey box", objects=["the light-court or neighbouring mass outside F01_COMMON_B's windows"], purpose="Review: the window view is a grey plaster box; the light court's finished face or a neighbour's back belongs there", sources=["art/blender/light_court.md"], acceptance="Window detail stations")],

    # ------------------------------------------------------------- F02
    "F02_C_KITCHEN": [change("F02_C_KITCHEN-004", "P1", "refine", "Icebox rotated off its base", objects=["F02_2C_FRIDGE_01 (yaw about 15 degrees off the wall)"], purpose="Review: the oak icebox stands rotated in OV, RV and DT1; a placement bug", sources=["game/data/orison_v2/household_fridges.json", "art/data/orison_v2/completion_interiors_source.json"], acceptance="Kitchen OV shows the icebox square to the wall")],
    "F02_B_PRIVATE_HALL": [change("F02_B_PRIVATE_HALL-003", "P2", "refine", "Chrome shelf posts to painted iron or oak", objects=["2B_fabric_shelf_01/02 (Shelf01 chrome posts)"], purpose="Review: bright chrome posts read post-1950; see BW-003", acceptance="Hall threshold view")],
    "F02_B_KITCHEN": [change("F02_B_KITCHEN-003", "P3", "refine", "A pot on the lit burner", objects=["F02_2B_STOVE_01 lit burner"], purpose="Review: a burner is lit with nothing on it; Lena's biggest pot belongs there", acceptance="Range detail")],
    "F02_C_BATH": [change("F02_C_BATH-003", "P2", "refine", "Hung duct over the bath", objects=["the hung duct in 2C's bath"], purpose="Review: the duct reads industrial; see BW-005", acceptance="Bath OV")],
    "F02_SERVICE_CORE": [change("F02_SERVICE_CORE-003", "P1", "refine", "Service core shows the public marble stair and no lift", objects=["F02_SERVICE_CORE stair finish; service lift landing doors"], purpose="Review: the service stair reuses the public marble and iron; the service lift landing is absent. See BW-006", acceptance="Core OV shows a plain service stair and the lift landing")],

    # ------------------------------------------------------------- F03
    "F03_D_KITCHEN": [change("F03_D_KITCHEN-004", "P1", "refine", "No range visible in any tile; verify the native range mounts", objects=["F03_3D_STOVE_01 (household_stoves.json lists the instance; the tiles are identical to 1A's kitchen)"], construction="As F01_A_KITCHEN-004: confirm the 3D range instantiates at its fitting and is visible from the room", purpose="Review: no range or stove seen; the Appliance Bible gives every kitchen but 4B one", sources=["game/data/orison_v2/household_stoves.json"], acceptance="Kitchen OV shows the range")],
    "F03_D_BATH": [change("F03_D_BATH-003", "P1", "refine", "Toilet tank's flat magenta face (missing material)", objects=["3D_wc cistern"], purpose="Review: a magenta face is a missing material binding", sources=["game/data/orison_v2/completion_interiors.json (3D_wc template)"], acceptance="Bath DT3 shows porcelain")],
    "F03_B_MAIN": [change("F03_B_MAIN-005", "P2", "refine", "Workbench carcass untextured; shelving posts; the radio's seat", objects=["3B_workbench (assembly) carcass; 3B_tools0/1 posts; 3B_radio"], purpose="Review: the bench carcass is an untextured dark box, the shelves are square steel posts with flat boxes, the radio sits on the rack not the wall", sources=["art/blender/work_tables.md", "art/blender/domestic_storage.md"], acceptance="Bench and shelf details")],
    "F03_B_KITCHEN": [change("F03_B_KITCHEN-004", "P2", "refine", "Service door is a featureless charcoal slab", objects=["F03_B_SERVICE_DOOR leaf"], purpose="Review; the only kitchen service door in the building should be a panelled service leaf with a kick plate", sources=["art/blender/shop_joinery.md (fitted back doors) as the pattern"], acceptance="Kitchen OV")],
    "F03_EAST_HALL": [change("F03_EAST_HALL-003", "P2", "remove", "Powder-blue plane with a cream stripe at the core end", objects=["the flat plane at the east hall's core end (review)"], purpose="A placeholder plane in a public hall", acceptance="Hall OV")],
    "F03_SERVICE_CROSSING": [change("F03_SERVICE_CROSSING-002", "P2", "refine", "Sawtooth ceiling planes over the crossing", objects=["ceiling geometry over F03_SERVICE_CROSSING"], purpose="Review: angled sawtooth planes read as an export artefact", acceptance="Crossing OV")],
    "F03_SOUTHWEST_HALL": [change("F03_SOUTHWEST_HALL-003", "P3", "refine", "Stray diagonal pipe", objects=["the diagonal pipe in the southwest hall (review)"], purpose="Accord 11: give it supports and a destination or remove it", acceptance="Hall OV")],
    "F03_A_MAIN": [change("F03_A_MAIN-005", "P1", "refine", "Reads as an unfurnished template", objects=["3A main room overall"], purpose="Review: 3A main and all of 3D read as unfurnished templates despite the potting bench; the propagation shelf (F03_A_MAIN-001) is the fix", acceptance="OV reads a horticulturist's room")],

    # ------------------------------------------------------------- F06 / ROOF (review)
    "ROOF_DECK_WEST": [change("ROOF_DECK_WEST-004", "P1", "refine", "The house tank reads as brick, not timber staves", objects=["ROOF_TANK_BODY and bands (house_tank.md: timber staves, binding hardware)"], purpose="Review and the smoke capture: the tank body carries a brick-like map; the native tank is coopered timber with iron bands", sources=["art/blender/house_tank.md", "art/blender/city_tanks.md (calibrated stave finish for the neighbours)"], acceptance="Deck OV shows timber staves and bands"),
                       change("ROOF_DECK_WEST-005", "P2", "refine", "Ventilator housings read as cream stone plinths", objects=["ROOF_VENT_FAN_A/B/C housings (A06 pending)"], purpose="Review: only fan D reads as a fan; the ILG-pattern housings of Bible VIII.5.i are the owner JSON's A06 item", sources=["art/data/v2_owner_improvement_20261008.json A06", "art/blender/roof_ventilator.md"], acceptance="Fan detail stations read motor housings")],
    "ROOF_DECK_EAST": [change("ROOF_DECK_EAST-003", "P2", "refine", "Chimney reads as a short plain block", objects=["masonry chimney (chimney_crown.md: bonded masonry, mortar joints, stone coping)"], purpose="Review: the chimney is a plain brick block; the crown record describes joints and coping", sources=["art/blender/chimney_crown.md"], acceptance="East walk station")],
    "ROOF_PUBLIC_CORE": [change("ROOF_PUBLIC_CORE-004", "P2", "refine", "Mirror-reversed lift-drive sign text; bulkheads untextured cream boxes", objects=["lift drive sign Label3D (double-sided); bulkhead wall finish"], purpose="Review: sign text reads reversed from the RV station; bulkhead walls are untextured", sources=["art/blender/roof_bulkhead_caps.md"], acceptance="RV station shows readable text and finished walls")],
    "F06_A_STUDY": [change("F06_A_STUDY-003", "P2", "refine", "Desk wall is a flat white slab on black cuboids; modern headphone stand", objects=["6A_deskwall (assembly)", "6A_phones stand"], purpose="Review; see BW-003", acceptance="Study OV")],
    "F06_C_MAIN": [change("F06_C_MAIN-005", "P2", "refine", "Boxy untextured sofa and block coffee table", objects=["6C_sofa (Sofa195)", "6C_cof (Coffee06)"], purpose="Review; see BW-003 (rolled-arm sprung sofa variant)", acceptance="Main OV")],
    "F06_A_BATH": [change("F06_A_BATH-003", "P2", "refine", "Black mirror and the dithered moon through the bath glass", objects=["F06_6A_MIRROR_01 reflection; bath window glass"], purpose="Review: the mirror renders black and the moon dithers into a speckled disc through the glass", sources=["art/blender/lift_mirror.md (shared live reflection)", "design/V2_PHOTO_GLAZING_2026-10-05.md (declared optics)"], acceptance="Bath DT stations")],

    # ------------------------------------------------------------- F04 (review)
    "F04_LANDING": [change("F04_LANDING-003", "P1", "refine", "An unlit landing between a lit hall and the stair", objects=["F04_LANDING practical (none in data); see BW-017"], purpose="Review: no practical on the landing; the lamp pool is the only light and the lift plate cannot be read. The overview pair faced the parapet, so the landing is otherwise uninspected", sources=["game/data/orison_v2/fixed_lighting.json"], acceptance="Landing station with the hand lamp off reads the lift plate and the 4B transom")],
    "F04_PUBLIC_CORE": [change("F04_PUBLIC_CORE-003", "P2", "refine", "The lift landing reads as a dark stone-framed hole in bare brick", objects=["PassengerElevator landing at F04 (elevator.gd _build_landing: center-parting landing doors, call plate and interlock at every stop); the core wall finish around it"], construction="Plaster the core wall around the landing (BW-015) and give the closed landing leaves their painted-steel finish, sight glass and brass sill so a closed shaft reads as doors, not a void", purpose="Review: the passenger lift the caption promises cannot be found; the brick opening may be it but reads as a hole", sources=["game/scripts/building/elevator.gd", "art/blender/lift_mirror.md"], preserve="Lift motion, interlocks and call plates", acceptance="Core OV shows the landing doors and plate")],
    "F04_WEST_HALL": [change("F04_WEST_HALL-003", "P3", "refine", "Lit with no fixture in frame; terrazzo chip scale", objects=["F04_WEST_HALL practical (BW-017); terrazzo map (BW-020)"], purpose="Review: the ceiling plane and door head read lit although no fixture is visible; chips oversized", acceptance="Hall OV shows the practical")],
    "F04_EAST_HALL": [change("F04_EAST_HALL-003", "P2", "refine", "No hall light; the 4A transom is the only lit thing", objects=["F04_EAST_HALL practical (BW-017); 4A transom light (BW-016)"], purpose="Review: the approach to 4A reads unlit except for an overexposed transom, so the door glows", acceptance="East hall OV with the lamp off")],
    "F04_SERVICE_CROSSING": [change("F04_SERVICE_CROSSING-002", "P3", "refine", "Slab wainscot planes and the hard floor seam", objects=["the flat wood-grained slab planes at the crossing (millwork without its profile); the terrazzo-to-tan floor edge"], construction="Stile-and-rail relief from millwork_profile.md on the slabs; a 40 mm brass threshold strip at the floor seam as the F05 crossing already carries a strip", purpose="Review: wainscot that lost its mouldings and a hard material edge where the public floor meets the service floor", sources=["art/blender/millwork_profile.md"], acceptance="Crossing OV")],
    "F04_SOUTHWEST_HALL": [change("F04_SOUTHWEST_HALL-003", "P3", "refine", "4D's door is anonymous from the hall", objects=["F04 4D entry door numeral (BW-022)"], purpose="Review: the rental door carries no unit number", acceptance="DT3 reads 4D")],
    "F04_A_VESTIBULE": [change("F04_A_VESTIBULE-004", "P3", "refine", "Blockout purpose text names 2B", objects=["game/data/orison_v2_blockout.json space F04_A_VESTIBULE.purpose (reads '2B privacy, coat storage and distribution')"], construction="Data text fix to '4A privacy, coat storage and distribution'; no geometry", purpose="Review caught the copied purpose string; it propagates to every caption and census built from the blockout", sources=["game/data/orison_v2_blockout.json"], acceptance="Sheet caption reads 4A")],
    "F04_A_MAIN": [change("F04_A_MAIN-005", "P2", "refine", "The radio reads as a panel and a white shape", objects=["4A wireless table and its set (4A_wireless_table; BW-011 adds DomesticRadio_4A)"], construction="A readable cabinet set from the domestic_radios family with a horn or cone and dial; until BW-011 lands, remove the abstract pair", purpose="Review: at present an abstract pair of shapes", sources=["game/data/orison_v2/domestic_radios.json"], acceptance="Wireless-table detail station reads a radio")],
    "F04_A_PRIVATE_HALL": [change("F04_A_PRIVATE_HALL-002", "P2", "add", "Wren's hall file", objects=["new: 4A_hall_file, a second-hand oak four-drawer vertical file (domestic_storage family, new variant) with one drawer not fully shut"], placement="Against the hall's east wall between the bath and bed doors, its back to the wall, leaving the 0.9 m clear width", dimensions="about 0.38 x 0.65 x 1.32 m (a typical oak vertical file of the period; measure before placing)", materials="quarter-sawn oak, brass label frames (Label3D or blank), nickel pulls", wear="finger grime at the top pull; a ring from a cup", purpose="The blockout gives this hall 'document storage' and the review found none; the clerk's filing lives where he passes it every night", sources=["game/data/orison_v2_blockout.json F04_A_PRIVATE_HALL.purpose", "art/blender/domestic_storage.md"], preserve="Door swings and the hall's clear width", acceptance="Hall OV reads the file; doors still open fully")],
    "F04_A_BATH": [change("F04_A_BATH-003", "P1", "refine", "WC without a cistern; curtain over nothing", objects=["4A_wc (template 5C_wc; BW-018)", "F04_4A_SHOWER_01 curtain and receptor (BW-008)"], purpose="Review: no cistern, tank or flush pipe in any tile; the closed pleated curtain reads as a column with no tray under it", acceptance="Bath DT on the WC shows the low cistern; the tray reads under a gathered curtain")],
    "F04_B_KITCHEN": [change("F04_B_KITCHEN-004", "P2", "refine", "Range sides carry a wood-grain material; burners read as electric coils", objects=["F04_B_STOVE_01 (the native 4B range) side panels and burner grates"], construction="Rebind the side panels to the enamel material (the one-material-per-buffer trap: check the GLB's material slots) and give the burners cast-iron spider grates over the gas rings", purpose="Review: a gas range with wood sides and coil burners reads as neither gas nor 1928", sources=["game/data/orison_v2/household_stoves.json", "art/blender/household_stoves.md"], preserve="Stove activity and the lit-burner state", acceptance="Range detail station")],
    "F04_B_BATH": [change("F04_B_BATH-003", "P3", "keep", "The low cistern is period-correct", objects=["4B WC with its close-coupled low cistern"], purpose="The review read the low tank as post-1928; bathroom_details.md specifies a low cistern with a lever, which the 1928 reopening refit would have installed; it is also the reference every copied WC must match (BW-018)", sources=["art/blender/bathroom_details.md"], acceptance="Unchanged")],
    "F04_B_CLOSET": [change("F04_B_CLOSET-003", "P2", "remove", "Placeholder cubes on the equipment shelf", objects=["the grey noise-textured cubes and plain cream boxes on 4B_equipment_shelf (Shelf01)"], purpose="Review: placeholder crates stand in for equipment; F04_B_CLOSET-001 supplies the rail and stock that replace them, and the steel posts go with BW-003; the closet's side wall also shows bath tile (BW-004)", acceptance="Closet OV shows no flat-colour cubes")],
    "F04_B_ALCOVE_APPROACH": [change("F04_B_ALCOVE_APPROACH-002", "P3", "refine", "The closet switch's white toggle lever", objects=["F04_B_CLOSET_SWITCH (interaction) beside F04_B_ALCOVE_APPROACH_SWITCH"], construction="Same push-button plate as the room switches (light_switch.md); the two plates are two circuits (hall, closet) and stay", purpose="Review: a toggle lever reads modern against the push-button family", sources=["art/blender/light_switch.md", "game/data/orison_v2/room_lighting.json"], preserve="Closet switch interaction", acceptance="DT1 at the closet switch")],
    "F04_C_MAIN": [change("F04_C_MAIN-005", "P1", "refine", "Colour board and bookshelf absent from their own detail stations", objects=["4C_story_colorboard (DomesticObject09 at its census anchor)", "F04_4C_BOOKSHELF_01"], construction="Both ids exist in the runtime census and were targeted by DT1 and DT3, which show the empty side table and the hall opening; confirm the instances render at their anchors (not inside the wall, back-facing or scaled to nothing) before F04_C_MAIN-002 and -004 build on them", purpose="Review: two of the three story objects named for this room are missing from their own stations", sources=["game/data/orison_v2/domestic_objects.json", "game/data/orison_v2/bookshelves.json"], acceptance="DT1 shows the board; DT3 shows the shelf")],
    "F04_C_KITCHEN": [change("F04_C_KITCHEN-004", "P1", "refine", "Icebox rotated with its rear edge in the wall plane", objects=["F04_4C_FRIDGE_01 (FridgeIcebox; same yaw as F02_2C_FRIDGE_01 and F05_5C_FRIDGE_01)"], construction="Square the icebox to the wall as F02_C_KITCHEN-004; the three copies share one placement record", purpose="Review: a transform error rather than casual placement; the rear edge reads inside the wall in OV and DT1", sources=["game/data/orison_v2/household_fridges.json", "art/data/orison_v2/completion_interiors_source.json"], acceptance="Kitchen OV shows the icebox square and clear of the wall")],
    "F04_D_KITCHEN": [change("F04_D_KITCHEN-004", "P1", "refine", "No range in the four tiles; verify the native range mounts", objects=["F04_4D_STOVE_01 (household_stoves.json lists it with ambient_lit false; the sheet is partial, four tiles)"], construction="As F01_A_KITCHEN-004: confirm the HouseholdGasRange instance for 4D instantiates at its fitting and faces the room", purpose="Review: captioned cooking and washing, only washing is provided", sources=["game/data/orison_v2/household_stoves.json", "game/data/orison_v2/completion_interiors.json fittings"], acceptance="Kitchen OV from the hall side shows the range"),
                      change("F04_D_KITCHEN-005", "P3", "keep", "The cabinet with the domed cylinder is the monitor-top", objects=["F04_4D_FRIDGE_01 (FridgeMonitor)"], purpose="The review read the tall cream cabinet with a long pull and a banded dome as a 1940s refrigerator; it is the monitor-top, which F04_D_KITCHEN-003 and BW-012 already replace with a dry icebox", acceptance="Resolved by F04_D_KITCHEN-003")],
    "F04_D_BATH": [change("F04_D_BATH-003", "P1", "move", "Switch plate off the tile above the basin", objects=["F04_D_BATH_SWITCH (anchor at -7.45, 1.12, -12.25) and its plate"], placement="To the latch side of the bath door, 150 mm from the frame at 1.12 m; the basin's own position is not in the data read for this dossier, so confirm the clearance on the floor", purpose="Review: an electric switch in the splash zone of the basin is wrong for any period", sources=["game/data/orison_v2/room_lighting.json switches", "game/data/orison_v2_blockout.json anchors"], preserve="Switch interaction and the light it owns", acceptance="DT at the basin shows tile only; the switch is reachable from the door")],

    # ------------------------------------------------------------- F05 (review)
    "F05_PUBLIC_CORE": [change("F05_PUBLIC_CORE-003", "P2", "refine", "Landing floor at 5C's door is flat tan with no skirting", objects=["F05_PUBLIC_CORE floor and base around F05_DOOR_06"], construction="Carry the hall terrazzo and the painted base across the landing to the door sill", purpose="Review: the landing outside 5C reads as a service space, not the public hall it joins", sources=["game/scripts/building/floor_coverage_pass.gd"], acceptance="DT1 at DOOR_06 shows terrazzo and base"),
                        change("F05_PUBLIC_CORE-004", "P3", "keep", "Honed marble without baked wear is the owner's decision", objects=["stair, stair_b, stair_c families"], purpose="The review asked for positional wear on the main flight; stair_honed.md removed the baked nosing stripes deliberately because they repeated across half-landings; any wear must be positional (per-tread) or none", sources=["art/blender/stair_honed.md"], acceptance="Unchanged")],
    "F05_WEST_HALL": [change("F05_WEST_HALL-004", "P1", "refine", "Unit doors 5A and 5B render nearly black", objects=["F05_DOOR_02, F05_DOOR_03 leaves; F05_WEST_HALL practical (BW-017)"], purpose="Review: the two unit doors are this hall's story and they are unreadable at this exposure; a hall practical and the leaf finish (BW-016) fix it", acceptance="Hall OV with the lamp off reads both doors")],
    "F05_SERVICE_CROSSING": [change("F05_SERVICE_CROSSING-002", "P3", "refine", "Peephole as a white disc; dark joint at the upper-left wall", objects=["F05_DOOR_05 peephole (BW-014); the wall joint gap in OV"], purpose="Review: the white disc and the glowing frame pull the eye more than the kick wear does", acceptance="TH at DOOR_05")],
    "F05_A_MAIN": [change("F05_A_MAIN-005", "P2", "refine", "Desk lamp is polished chrome", objects=["the task lamp on 5A_plantable (task lamp family instance for 5A)"], materials="dull nickel or black japanned steel, copper base kept", purpose="Review: the one object in the room that breaks the 1927 rule", sources=["game/data/orison_v2/task_lamps.json", "art/blender/task_lamps.md"], acceptance="Plan-table detail"),
                   change("F05_A_MAIN-006", "P2", "refine", "Two blank pale-grey recesses on the wall opposite the window", objects=["the two recesses seen in RV (the vestibule and private-hall openings whose leaves blow out, or window recesses without sash); identify first"], construction="If openings: BW-016; if window recesses: the glazing family's sash and the light-court face beyond (F01_COMMON_B-003 is the same symptom)", purpose="Review: flat panels with a light line flatten the far wall and read as placeholders", acceptance="RV station shows finished openings")],
    "F05_A_BATH": [change("F05_A_BATH-003", "P1", "refine", "WC without a cistern; curtain to the floor over nothing; pipe as a grey strip", objects=["5A_wc (BW-018)", "F05_5A_SHOWER_01 curtain and receptor (BW-008)", "the flat grey vertical strip beside the window (a pipe placeholder: heating_distribution riser or remove)", "F05_A_BATH_VENT_REGISTER grey box (BW-005)"], purpose="Review: the fixtures are period in type; the missing cistern and tray undercut the sanitary room", sources=["art/blender/heating_distribution.md"], acceptance="Bath DT stations")],
    "F05_A_STUDY": [change("F05_A_STUDY-002", "P2", "refine", "Placeholder cubes on the plan shelf; thin steel posts", objects=["grey blocks and white boxes on 5A_planshelf (Shelf07; posts go with BW-003)"], construction="Banded plan rolls, two sample bricks and a mortar cube (desktop_stock) replace the cubes; F05_A_STUDY-001 adds the bands and T-square", purpose="Review: the model and pin board carry the story; the shelving reads as modern utility shelving with plain cubes", sources=["game/data/orison_v2/surface_stock.json"], acceptance="Study OV")],
    "F05_B_MAIN": [change("F05_B_MAIN-005", "P1", "refine", "The tulip pedestal under the listening set", objects=["5B_din_t (TableRound10; BW-003)"], purpose="Review: the most visible anachronism on the floor sits under the room's hero object", acceptance="Main OV shows a turned-leg table"),
                   change("F05_B_MAIN-006", "P3", "refine", "Cone speakers render as flat faceted discs", objects=["the two cone speakers on 5B_wireless_table (household_radios / radio_apparatus family)"], construction="A paper cone with a surround and a pressed-steel back, the Western Electric pattern Cal would own; the flat disc is the LOD or a lost normal set", purpose="Review", sources=["game/data/orison_v2/household_radios.json", "art/blender/radio_apparatus.md"], acceptance="Side-table detail")],
    "F05_B_BATH": [change("F05_B_BATH-003", "P2", "move", "Column radiator stands mid-room", objects=["the tall cream column radiator in F05_B_BATH (heating family instance for 5B's bath)"], placement="Against the wall under the window or beside the WC with its valve on the supply side; one-pipe steam needs the riser at the wall (Bible VIII.5.c)", construction="Sectioned casting from the heating family, not a ribbed cylinder", purpose="Review: a radiator in the middle of a bath floor has no pipe and reads as a cylinder", sources=["game/data/orison_v2/heating.json", "art/blender/heating_distribution.md"], acceptance="Bath OV")],
    "F05_B_KITCHEN": [change("F05_B_KITCHEN-004", "P2", "refine", "The hob radios sit on the table, not the range", objects=["5B_k_hob_radio0, 5B_k_hob_radio1 (HouseholdRadio, authored as hob radios); the range back shelf is empty"], construction="Confirm their support: the ids say hob, the frames show two sets on the comparison table and nothing on the range; either keep the table (and rename) or seat them on the range shelf as authored", purpose="Review versus data", sources=["game/data/orison_v2/household_radios.json"], acceptance="Kitchen OV matches the data")],
    "F05_C_VESTIBULE": [change("F05_C_VESTIBULE-003", "P1", "refine", "The ceiling duct ends in mid-air by the door head", objects=["the hung duct across F05_C_VESTIBULE (BW-005)"], purpose="Review: a galvanized duct across an apartment entry is wrong for 1928 and it does not terminate", acceptance="TH shows no open duct end")],
    "F05_C_BATH": [change("F05_C_BATH-003", "P2", "refine", "The sink wall is bare plaster while the other three are tiled", objects=["F05_C_BATH wall finish quad behind F05_5C_SINK_01"], construction="Emit the tile finish on the fourth wall (the same side-aware quad as BW-004)", purpose="Review: tile stops at the corner; the WC also lacks its cistern (BW-018) and the duct reads modern (BW-005)", acceptance="Bath OV")],
    "F05_C_BED1": [change("F05_C_BED1-002", "P2", "move", "One wardrobe from the studio closet to the bedroom", objects=["5C_w0_wardrobe (Wardrobe07) from F05_C_STUDIO to F05_C_BED1"], placement="Against the bedroom's south wall, clear of the window and the door swing, doors facing the bed", purpose="Review: the bedroom captioned for clothing has no clothing storage while the studio closet holds two wardrobes; F05_C_STUDIO-001 keeps the second as the pigment store", sources=["art/data/orison_v2/completion_interiors_source.json"], dependencies="F05_C_STUDIO-001", preserve="Wardrobe leaf motion", acceptance="Bedroom OV shows the wardrobe; the closet holds one")],
    "F05_C_MAIN": [change("F05_C_MAIN-004", "P3", "refine", "A loose cable loop on the floor by the radiator", objects=["the dark cable loop and the boxy object beside the radiator (seen from the studio)"], construction="Give the cable an origin and a destination (the signal outlet of BW-013 and a device) or remove it", purpose="Accord 11", acceptance="Studio OV")],
    "F05_C_KITCHEN": [change("F05_C_KITCHEN-004", "P2", "refine", "Icebox angled off the wall", objects=["F05_5C_FRIDGE_01 (FridgeIcebox; the same placement record as 2C and 4C)"], construction="Square it with F02_C_KITCHEN-004 and F04_C_KITCHEN-004; if the angle is wanted as second-hand placement, author it once and clear the wall", purpose="Review: reads as deliberate here and as clipping in 4C; one record, one decision", sources=["game/data/orison_v2/household_fridges.json"], acceptance="Kitchen OV")],
    "F05_D_RESTRICTED": [change("F05_D_RESTRICTED-003", "P3", "remove", "Floor-level duct strip and box register", objects=["the grey duct strip along the floor line rising to a white louvred box (DT1)"], purpose="Review: placeholder geometry in an intentionally empty shell; seat the branch in the chase (BW-005) or remove it; the shell otherwise stays as authored (F05_D_RESTRICTED-001)", acceptance="DT1 without the strip")],

    # ------------------------------------------------------------- City (review)
    "CITY_STREET": [change("CITY_STREET-005", "P2", "refine", "Hard-edged dark rectangles on the pavement", objects=["ExteriorGroundDecal instances (exterior_detail_pass.gd) at the Orison's base and along the walk"], construction="Feather the decal alpha and clip them to the slab joints; a stain follows a joint, a puddle follows a dip", purpose="Review: they read as missing or unmasked decals in four stations", sources=["game/scripts/building/exterior_detail_pass.gd"], acceptance="Route stations show no hard rectangles"),
                    change("CITY_STREET-006", "P2", "refine", "Neighbouring masses are flat untextured blocks", objects=["city closure blocks beyond the two facades, the pale column and the flat right-hand wall at the alley mouth"], construction="Brick or render map, window grids and a cornice line on every mass inside the storm boundary; the middle-distance loss the brief ships hides them only when the rain is on", purpose="Review: everything beyond the two facades is flat blocking", sources=["art/blender/city_closure.md", "design/ORISON_STREET_BRIEF.md (middle-distance loss)"], acceptance="Facade wide and route stations"),
                    change("CITY_STREET-007", "P2", "keep", "Weather at capture is not evidence", objects=["the street's storm state (live GPU rain, near rain suppressed, puddle pass) and the measured Milky Way of the brief"], construction="Before treating the dry road and clear sky as defects, repeat the street stations with the storm on (WEATHER_SEED set, rain enabled); the dossier sweep set no weather", purpose="Review: no rain, puddles or wet sheen anywhere; the brief ships a quiet storm and keeps the Milky Way overhead by design", sources=["design/ORISON_STREET_BRIEF.md", "game/scripts/building/orison_v2_atmosphere.gd"], acceptance="A storm-state capture of the same stations")],
    "CITY_FACADE": [change("CITY_FACADE-002", "P3", "refine", "Showroom brass and a flat doormat", objects=["front door handle, lock and bell push; the red doormat; the handle-side stone"], wear="Finger-polished high points on tarnished brass; a coir mat with a worn centre; a greasy band on the stone at hand height", purpose="Review: the best-dressed exterior in the city has no positional wear", sources=["art/blender/front_facade.md", "art/blender/door_knob_set.md"], acceptance="facade_door station"),
                    change("CITY_FACADE-003", "P2", "refine", "A white sphere floats in the sky beside the blade", objects=["the small bright sphere left of the lantern in facade_blade (moon disc or an exposed light mesh)"], construction="Identify and fix: if the moon, place it on the sky dome; if a light mesh, hide it", purpose="Accord 15", acceptance="facade_blade station")],
    "CITY_ALLEY": [change("CITY_ALLEY-003", "P1", "refine", "Polished brass downpipes and the black band at the wall tops", objects=["alley leaders and shoes (roof_drainage.md leaders); the wall tops ending in a flat black strip; the grey plane closing the alley's far end (alley_4_back)"], materials="painted cast iron, rust at the joints, a stain fan on the brick under each shoe", construction="Coping or a roof edge at the wall tops; finish the closing plane as a neighbour's back", purpose="Review: brass tubes and a black band in every frame; no staining under pipes or lamps", sources=["art/blender/roof_drainage.md", "art/blender/city_closure.md"], acceptance="alley_1 and alley_4 stations"),
                   change("CITY_ALLEY-004", "P2", "refine", "The rear door is a flat speckled slab", objects=["the grey-green alley door with its yellow block handle; the white specks on its frame"], construction="Panelled service leaf with a kick plate, a knob set and a drip; find the specks (light leak or stray vertices)", sources=["art/blender/shop_joinery.md (fitted back doors)"], purpose="Review", acceptance="alley_0 station")],
    "CITY_SUBWAY": [change("CITY_SUBWAY-003", "P3", "keep", "Kiosk lettering and the arch lattice need a closer station", objects=["kiosk sign and the lattice across the lit arcade arch"], purpose="Review: from the one station the kiosk reads as thin lines and the lattice could read as a shuttered arcade; not a defect until seen closer", acceptance="A second station at the kerb opposite")],
    "CITY_BODEGA": [change("CITY_BODEGA-005", "P1", "refine", "Stand-in stock, a featureless register and a strip-light fitting", objects=["aisle stock (unlabelled orange cylinders, yellow boxes, cream block sacks, uniform green spheres); the counter register box; the boxed ceiling fitting"], construction="Tins with wordless printed bands and seams (no lettering in textures), stacked boxes with torn flaps, burlap sacks, produce with variation; a 1920s brass-and-nickel register with keys; the ceiling fitting becomes two opal pendants or a trough reflector from the fixed_lighting family", materials="tin, card, burlap, nickel", wear="scuffs at aisle ends and the door", purpose="Review: fully lit and trading but the cleanest room in the city; the fitting reads as a modern strip", sources=["art/blender/bodega_frontage.md", "art/blender/bodega_receiving.md", "art/blender/fixed_lighting.md"], acceptance="bodega_aisles and bodega_counter stations")],
    "CITY_SHOP_MODEL_LAUNDRY": [change("CITY_SHOP_MODEL_LAUNDRY-003", "P2", "refine", "Flat garments, flat shelf boards, a blown-out front window", objects=["hanging garments on the rail (flat cut-outs); the shelf wall of pale boards; the front glazing"], construction="Cloth-batch garments with folds; wrapped parcels on the shelves (laundry_trade.md); the window glass from the photo glazing optics", purpose="Review: identifiable, but every object is a stand-in", sources=["art/blender/laundry_trade.md", "design/V2_PHOTO_GLAZING_2026-10-05.md"], acceptance="IN0 and floor_0 stations")],
    "CITY_SHOP_SHOE_REBUILDING": [change("CITY_SHOP_SHOE_REBUILDING-003", "P2", "refine", "A near-black floor, shoe lumps and a red cube", objects=["cobbler floor finish and its practical; shelf stock (dark lumps); the plain red cube; the ladder leaning into the aisle"], construction="Lift the floor with a second cage bulb over the bench and a lighter floor map; lasts and shoes with form (cobbler_fittings.md); remove or dress the cube; stand the ladder against the shelving", purpose="Review: the floor is unreadable in every frame", sources=["art/blender/cobbler_fittings.md", "art/blender/fixed_lighting.md"], acceptance="IN0 station readable")],
    "CITY_SHOP_KEYS_CUT": [change("CITY_SHOP_KEYS_CUT-003", "P3", "refine", "A uniform key grid and four copied boxes on a flat mat", objects=["key board silhouettes; the four identical boxes on the red mat; the table's dark blocks"], construction="Vary blank shapes and gaps on the board, one row empty; three boxes, one open; the table's blocks become the picks and blanks of CITY_SHOP_KEYS_CUT-001", purpose="Review: copy-paste reads at a glance", sources=["art/blender/resident_keys.md"], acceptance="IN1 station")],
    "CITY_SHOP_HARDWARE_PAINT": [change("CITY_SHOP_HARDWARE_PAINT-002", "P3", "refine", "Identical cans and an identical drawer wall", objects=["the seven wire-bail cans; shelf cylinders; the drawer wall pulls"], construction="Three can sizes, dented lids, drips down two; one drawer open; wordless colour bands on the cans", purpose="Review", sources=["art/blender/hardware_stock.md"], acceptance="IN1 station")],
    "CITY_SHOP_FUNERAL_PARLOUR": [change("CITY_SHOP_FUNERAL_PARLOUR-004", "P3", "refine", "Rigid chair rows and flat curtains", objects=["the spindle-back chairs; the alcove curtains"], construction="Rows kept (the room is arranged) with two chairs a few degrees off and one pulled out; curtains from the cloth batch with folds", purpose="Review: identical copies in rigid rows; the arranged order stays, the copies go", sources=["art/blender/funeral_drapes.md"], acceptance="IN0 station")],
    "CITY_SHOP_LUNCHEONETTE": [change("CITY_SHOP_LUNCHEONETTE-003", "P2", "refine", "A blown-out register, an unidentifiable pole and a featureless black cabinet", objects=["the cream register (overexposes to a white block); the cream pole with a box head behind the counter; the flat black cabinet on legs"], construction="Register albedo and keys from diner_till.md; identify the pole (a malt mixer or a menu stand) and give it its form; the black cabinet becomes the back-bar cooler of diner_backbar.md", purpose="Review", sources=["art/blender/diner_till.md", "art/blender/diner_backbar.md", "art/blender/diner_apparatus.md"], acceptance="IN1 and floor_0 stations")],
    "CITY_SHOP_OTIS_SON": [change("CITY_SHOP_OTIS_SON-002", "P2", "refine", "Flat yellow window panel, black-blob taps, blank drawer labels", objects=["the front window's yellow panel; fountain taps; the drawer-wall labels; the terrazzo (BW-020)"], construction="Window as show-globe backlight (CITY_SHOP_OTIS_SON-001) through real glazing; nickel fountain taps with handles from druggist_fountain.md; drawer labels as Label3D paper slips or left blank", purpose="Review: the arcade's most complete dressing with three stand-ins in front", sources=["art/blender/druggist_fountain.md", "art/blender/druggist_drawers.md"], acceptance="IN0 and IN2 stations")],
    "CITY_SHOP_NEWS_CIGARS": [change("CITY_SHOP_NEWS_CIGARS-003", "P1", "refine", "Shelves completely empty; case holds a few lumps", objects=["the booth's shelving and glass case (news_fittings, news stock)"], construction="Verify the news stock set instantiates; if it does not exist, author stacked papers (wordless mastheads as blocks of grey), magazine fans, cigar boxes with a lid up; the stool mat becomes a worn rubber mat with the hollow of CITY_SHOP_NEWS_CIGARS-001", purpose="Review: nothing says newspapers or cigars", sources=["game/data/orison_v2/news_fittings.json", "game/data/orison_v2/news_receiving.json"], acceptance="IN0 station")],
    "CITY_SHOP_PAWNBROKER": [change("CITY_SHOP_PAWNBROKER-003", "P2", "refine", "Bare sphere bulbs in the cage; the safe a black block", objects=["the two white sphere bulbs inside the counter cage; the safe"], construction="Shaded cage lamps from the fixed_lighting family; the safe gets its door line, hinges, dial boss and a painted name panel (no lettering in textures)", purpose="Review: the interior practicals that misbehave", sources=["art/blender/fixed_lighting.md", "art/blender/pawn_fittings.md"], acceptance="floor_0 and IN1 stations"),
                             change("CITY_SHOP_PAWNBROKER-004", "P3", "keep", "Clock faces without numerals are authored", objects=["the clock wall (pawn_clocks.md)"], purpose="The review read the dials as unfinished; pawn_clocks.md gives twelve geometric hour marks and invents no numerals, and the art rule forbids numerals in textures", sources=["art/blender/pawn_clocks.md"], acceptance="Unchanged")],
    "CITY_SHOP_RADIO_SERVICE": [change("CITY_SHOP_RADIO_SERVICE-003", "P2", "refine", "Jars instead of valves; a black torus on the floor; no test gear", objects=["the row of white-lidded jars on the bench; the shelves of pale bulbs; the black ring on the floor; the bare bench"], construction="Valves with bases and getters in a tube rack (radio_stock), a meter and a soldering iron on the bench (radio_bench); the torus is a wire coil (radio_wire) that needs its reel or goes; CITY_SHOP_RADIO_SERVICE-001 adds the 1610 set", purpose="Review: the one shop the divergence touches shows no evidence of the trade", sources=["game/data/orison_v2/radio_stock.json", "game/data/orison_v2/radio_bench.json", "game/data/orison_v2/radio_wire.json"], acceptance="IN0 and floor_0 stations")],
    "CITY_SHOP_PHOTO_SUPPLIES": [change("CITY_SHOP_PHOTO_SUPPLIES-002", "P2", "refine", "Film stock as flat blocks; cameras as dark boxes; an empty glass case", objects=["the shelving wall of coloured blocks; the three tripod cameras; the counter case"], construction="Film boxes with wordless printed bands in three sizes, some turned; cameras with bellows, lens boards and brass (photo_cameras.md); two cameras and a lens under the case glass", purpose="Review", sources=["art/blender/photo_cameras.md", "game/data/orison_v2/photo_stock.json"], acceptance="IN0 and IN1 stations")],
    "CITY_BAR_ROOM": [change("CITY_BAR_ROOM-005", "P2", "refine", "A flat red canopy, copied stools, packed flat pictures, a placed rack", objects=["the counter canopy slab; the round stools; the picture wall; the pool table's felt and balls"], construction="Canopy as a panelled valance with a light trough (bar_ceiling_finish); stools varied in height and wear; pictures as framed objects with glass and depth, spaced; felt worn at the rails and pockets, balls scattered as a game in progress, cue chalk dust", purpose="Review: the richest dressing in the city, undercut by copies and flat colour; CITY_BAR_ROOM-001 covers the bare counter", sources=["art/blender/bar_ceiling_finish.md", "art/blender/bar_furniture_construction.json", "art/blender/bar_pool.md", "art/blender/bar_gallery.md"], acceptance="WEST1 and POOL stations")],
    "CITY_BAR_DESCENT": [change("CITY_BAR_DESCENT-004", "P3", "refine", "Three litter props shared between lobby and vestibule", objects=["the cream taped box, the crate of dark lumps, the leaning cream board, the floor cards; the clean stair treads"], construction="CITY_BAR_DESCENT-001's diorama replaces these; until then give the board a printed face (wordless), the crate real contents and the treads a worn centre line", purpose="Review: the only genuine litter in the city is three props", acceptance="retail_bar_lob stations")],
    "CITY_BAR_STAGE": [change("CITY_BAR_STAGE-002", "P3", "refine", "The piano reads as a dark block on a flat platform", objects=["the upright piano and its platform (seen only from retail_bar_floor_1)"], construction="Lid, fallboard, music desk and candle sconces on the upright; a plywood platform edge with its nosing (bar_stage.md)", purpose="Review: the STAGE0/1 markers never framed the stage; the one frame that does shows a block", sources=["art/blender/bar_stage.md"], acceptance="A station from the pool table toward the stage")],
    "CITY_BAR_WC": [change("CITY_BAR_WC-002", "P3", "refine", "Red wash with no visible source; a flat speckled door", objects=["F01_BAR_LT_WC (cage_bulb_rise300) and the red wall wash; the WC door leaf"], construction="Confirm the cage bulb is the wash's source and give it a red-painted bulb or remove the tint; the door gets the panelled service leaf of CITY_BAR_WC-001's repairs", purpose="Accord 15: every lumen has a fixture", sources=["game/data/orison_v2/fixed_lighting.json", "art/blender/bar_service_access.md"], acceptance="WC station shows the bulb and the wash together")],
}
