"""F01 public and service spaces: street apron, vestibule, lobby, watch, mail, package, common room, cores, service hall, staff restroom."""
from _common import *

GP = "F01 / public and service"
INTRO_F01 = ("<b>The ground floor.</b> The address: the 1928 entrance with its transom, the sign that reads EST. 1928, the earliest photograph on the lobby wall, the lobby's sealed Vantry master "
             "clock permanently four minutes fast (Bible VIII.5.e), the brass mail bank with eighteen occupied boxes and six deliberately empty recesses (Bible IV.1), the house telephone board "
             "the player operates, the watch room with the watchman's detector clock, night register, signal register and tour key (G01-G03 implemented), the dumbwaiter on the service hall "
             "(G04), the common reading room with its oak table and bookcases, the package room's shelving, the lobby benches (public_furnishings.md) and the staff restroom. The lobby is where "
             "the schedules put the building's social life: Nadia's surgery hours at 08:15, Evelyn's noticeboard at 08:30, the Transients' almost-departure at 07:30, the tenant association "
             "on Saturdays, Cam's package handoffs at 18:00, Mae's gloved finger along the mail-bank brass. The smoke capture shows a terrazzo lobby with wainscot, two benches, two windows "
             "with brick reveals and a noticeboard, generously empty; the watch room with its instruments on bare plaster; the mail room's bank and board. The ground floor is correct and "
             "under-told: the eighteen households should be legible at the mail bank, the notices should carry the building's politics, and the vestibule should be the weather lock it is named.")

AREAS = [
    area("F01_STREET_APRON", GP, "STREET", "The street apron: the Orison's front step", "6.0 x 3.35 m public slab outside F01_DOOR_06 under the marquee, with the entry sign, the neon blade above, the vault lights", "everyone arriving; the arrival car",
         ("The fitted front pavement, the glazed oak entrance leaf, the marquee and the neon blade are installed (front_facade.md, front_court_roof.md). The apron needs its weather and its "
          "use: wet paving under the marquee's drip line, a boot scraper at the step, the milk and ice evidence of a morning delivery (crates stacked for collection at 20:00), the vault lights "
          "glowing from the basement, and the two entry lamps with their C1 moths. The player infers a building that is lived in before they enter it."),
         [change("F01_STREET_APRON-001", "P2", "add", "Boot scraper and delivery crates", objects=["new: cast-iron boot scraper beside the step; a stack of empty milk crates and an ice-tong hook by the areaway rail (desktop_stock)"], placement="Scraper 0.3 m from the leaf's hinge side; crates against the facade clear of the door swing and the route", materials="cast iron, pine crates", wear="wet paving and a mud fan at the scraper",
                 purpose="Bible VIII.4 ice and coal still; the apron is used by delivery", sources=["art/blender/front_pavement.md", "art/blender/front_facade.md"], preserve="Front entry route, arrival placement, marquee contacts", acceptance="Front entry route test unchanged; facade view shows crates"),
          change("F01_STREET_APRON-002", "P3", "add", "Election ephemera in the gutter", objects=["new: one soaked campaign broadside (papers) against the kerb, a brown derby on the areaway rail"], purpose="Period: the Saturday after the Hoover-Smith election; no lettering (a portrait silhouette and a star)", acceptance="Detail view")],
         canon=[C_BIBLE_VIII5H, C_COMMENSALS, C_OWNER], group_intro=INTRO_F01, implementation={"sources": ["art/blender/front_facade.md", "art/blender/front_pavement.md", "design/V2_FRONT_FACADE_PROGRESS_2026-10-05.md"], "dependencies": "A05 exterior stone trim pending", "preserved": "Entry route, arrival, marquee and blade owners", "acceptance": "Front entry route test unchanged"}),
    area("F01_REAR_APRON", GP, "STREET", "The rear apron: the service door's step", "2.2 x 2.75 m outside F01_REAR_SERVICE_DOOR on the service alley", "deliveries; Teresa at 22:00 and 07:40; the player",
         ("The rear step onto the graded alley with the shed work lights (G07). It needs the alley's trade: an ash can waiting for collection, a coal-cover wrench on a chain, a bootmark fan, the "
          "shed lamp's pool."),
         [change("F01_REAR_APRON-001", "P2", "add", "Ash cans and the chained wrench", objects=["new: two galvanised ash cans with lids by the wall; a coal-cover wrench on a chain by the door"], placement="Clear of the leaf's outward swing and the alley route", purpose="Bible VIII.5.c; the alley is where ash goes out and coal comes in", preserve="Rear door route (service alley test)", acceptance="Threshold view from the alley")],
         canon=[C_BIBLE_VIII5C], implementation={"sources": ["art/blender/service_alley.md", "art/blender/groundworks.md"], "dependencies": "none", "preserved": "Rear door and alley route", "acceptance": "Service alley test unchanged"}),
    area("F01_VESTIBULE", GP, "ORISON", "The vestibule: weather lock and address", "4.8 x 2.4 m between the street leaf (F01_DOOR_06) and the inner door (F01_INNER_DOOR)", "everyone",
         ("A weather lock with two doors. It should hold the address: the tenant directory with the lobby buzzer (WayfindingSignagePass, OPERATE), a mat that is really a drain grate, an umbrella "
          "stand, a radiator (the lobby's is beside the window), and the earliest photograph on the lobby wall belongs just inside. The transom light and the brass push plates are the 1928 fittings."),
         [change("F01_VESTIBULE-001", "P2", "add", "Umbrella stand, drain mat and the directory frame", objects=["new: cast-iron umbrella stand; a cast-iron grate mat set flush; the directory board beside the buzzer if not already here"], placement="Stand in the corner by the inner door's hinge; grate centred", purpose="A weather lock in November; the buzzer's directory is the building's roster", preserve="Both door swings and the entry route", acceptance="Threshold view from the street")],
         canon=[C_BIBLE_VIII5H, C_MATRIX], implementation={"sources": ["game/scripts/building/orison_v2_wayfinding.gd", "art/blender/front_facade.md"], "dependencies": "none", "preserved": "Door owners, buzzer", "acceptance": "Front entry route test unchanged"}),
    area("F01_LOBBY", GP, "ORISON", "The lobby: arrival, waiting and orientation", "10.8 x 5.4 m with two street windows, the inner door, 1A's entry door, openings to the core and the watch room; two fixed benches", "everyone; the tenant association on Saturdays; Nadia's surgery; Evelyn's rounds",
         ("Terrazzo, wainscot, two benches, two windows with brick reveals, a noticeboard. Generous and empty. The lobby is the building's parliament and should show it: the noticeboard dense with "
          "notices (Nadia's memos signed Management, Evelyn's red-pencilled corrections, the laundry schedule, a lost-and-found card), the sealed Vantry master clock on the core wall four minutes "
          "fast with the time clock below it, the earliest photograph (1928) framed by the inner door, a radiator by the window with a dish of gloves drying on it, a bench with one end worn where "
          "the Transients wait facing the doors, a brass spittoon by the other, the lift annunciator's bell visible through the watch opening. The player infers a lobby that is used all day by "
          "eighteen people who disagree."),
         [change("F01_LOBBY-001", "P1", "refine", "The noticeboard as the building's politics", objects=["existing LobbyBulletinBoard (23-piece authored board) or new board family"], placement="On the long wall between the windows at 1.5 m", construction="Pinboard owner (INSPECT); 23 pieces: memos, schedule, corrected notices with red strokes; Label3D only where the telegram grammar allows; no lettering in texture",
                 purpose="Schedules: Nadia posts, Evelyn corrects, the association meets; Bible VIII.5.h paper trail", sources=["game/data/resident_schedules.json", "design/PROP_SET_INTERACTION_MATRIX.md lobby bulletin board"], preserve="Bulletin board owner", acceptance="Detail view reads layers of paper"),
          change("F01_LOBBY-002", "P1", "add", "The master clock and the earliest photograph", objects=["existing Vantry reference ClockProp (sealed cover, RESIST-REFUSE) placed on the core-opening wall; new: framed 1928 photograph (CharacterMemoryArt) beside the inner door"], placement="Clock at 2.2 m centred over the core opening; photograph at 1.5 m", construction="Clock owner as in the matrix; photograph through WallArtLaw",
                 signal=SIGNAL_YES, purpose="Bible VIII.5.e: the lobby master is right and wrong; VIII.5.h: the earliest photograph dates from the reopening", sources=["design/ORISON_BIBLE.md VIII.5.e, VIII.5.h"], preserve="Clock refusal and house time", acceptance="Overview from the inner door reads clock and photograph"),
          change("F01_LOBBY-003", "P2", "add", "Bench wear, spittoon, gloves on the radiator", objects=["lobby benches: a worn patch on the end nearest the doors; new: brass spittoon, a dish of wet gloves on F01_LOBBY_RADIATOR_01"], purpose="Schedules: the Transients wait facing the doors; Accord 12", preserve="LobbyBenchZone sit/stand", acceptance="Detail views"),
          change("F01_LOBBY-004", "P3", "refine", "Sweep the earlier punchlist rows against the capture", objects=["'Order Board' teal slabs, floating nameplates, decorative bench on the wrong side (V1 rows)"], purpose="Close V1 rows that V2 has already resolved", acceptance="No floating labels in any tile")],
         canon=[C_BIBLE_III, C_BIBLE_VIII5E, C_BIBLE_VIII5H, C_SCHED, C_MATRIX], implementation={"sources": ["art/blender/public_furnishings.md", "game/scripts/building/orison_v2_public_furnishings.gd", "game/scripts/props/clock_prop.gd"], "dependencies": "A02 public floors pending final review", "preserved": "Benches, routes, 1A entry, time clock activity", "acceptance": "Mail and front entry routes unchanged"}),
    area("F01_WATCH", GP, "ORISON", "The watch room: detector, registers, tour key, annunciator", "4.2 x 4.4 m off the lobby opening with the ritual desk, the wire column, the watchman's detector clock, night register, signal register, tour key guard and the porter's call board; doors to the mail room and the core", "the player (clock in, take the report); the night watch",
         ("The smoke capture shows the instruments on bare plaster: the desk mass, the detector clock, the register shelf, the signal cabinet, the key guard, the annunciator with its row of flags, "
          "and a window to the lobby. G01-G03 are implemented and reviewed. The room needs its occupancy: the watchman's chair (the player's), a lamp on the desk, a coat on a hook, the tour "
          "route card on the wall (Label3D), a kettle on a gas ring, a cot folded against the wall (a night watch sleeps here between rounds), the wire column dressed with its terminal labels. "
          "The player infers the job: the building watched from this chair for sixteen years."),
         [change("F01_WATCH-001", "P1", "add", "Chair, desk lamp, coat and the folded cot", objects=["new: F01_watch_chair (ChairDark), F01_watch_lamp (task lamp landlord_enamel), a coat hook with a coat (cloth), a folded iron cot against the wall (new small family or crate-family stand-in)"], placement="Chair at the desk facing the lobby window; lamp on the desk's register side with a G14 cord; hook by the mail door; cot folded along the core wall",
                 construction="Shared variants; the cot as one static assembly", materials="oak, enamel, grey blanket, iron", wear="the chair's seat polished, the floor scuffed under it", lighting="the lamp is a real light only if the 16/16 budget allows; else an unlit visual with a glowing shade decal", purpose="The watch is manned; the player clocks in here", sources=["game/docs/v2_launch.md (clock in and take the report)", "art/blender/task_lamps.md"],
                 preserve="All five instrument owners and their reaches (DetectorReach, Reach_slip, hooks, book, index, reset, line, GuardReach, DispatchReach, CallHardwareReach)", acceptance="Overview reads a manned room; instrument tests unchanged"),
          change("F01_WATCH-002", "P2", "add", "Tour route card and kettle on a gas ring", objects=["new: route card (Label3D) by the key guard; a gas ring with a kettle on the shelf end (desktop_stock)"], purpose="The night watch's routine (tour key, report)", acceptance="Detail view at the key guard")],
         canon=[C_OWNER, "game/docs/v2_launch.md", C_MATRIX], implementation={"sources": ["G01-G03 sources in art/data/v2_owner_improvement_20261008.json", "game/scripts/props/watchman_clock_prop.gd", "night_register_prop.gd", "watch_register_prop.gd", "tour_key_guard_prop.gd", "otis_prop.gd"], "dependencies": "none", "preserved": "Instrument owners, desk mass, route to the core door", "acceptance": "Wall-mount and watch tests unchanged"}),
    area("F01_MAIL_TELEPHONE", GP, "ORISON", "The mail room: the brass bank and the house board", "3.8 x 4.4 m west of the watch room with the mail bank on the east wall, the house telephone board opposite, doors to the watch and package rooms", "the player (operator); every resident at their box",
         ("The Cutler-descended brass mail bank (eighteen occupied boxes, six deliberately empty recesses, box 4B the player's) and the house telephone board (G03) are installed. The room should "
          "show the eighteen households at the bank: a different card in each box window (blank rectangles in eighteen papers), two boxes stuffed (Jonah's checked daily for nothing, Cal's with "
          "catalogues), a parcel slip for 4C, Mae's finger-mark on the brass; at the board, the operator's stool, headset on its hook, a cord pile, a card of extensions (Label3D), and the "
          "dial-less telephone's truth: the player is the only way anyone reaches anyone (Bible VIII.4)."),
         [change("F01_MAIL_TELEPHONE-001", "P1", "refine", "Eighteen box windows, six empty recesses", objects=["LobbyMailBank: per-box window cards (18 distinct card rectangles, 2 overfull), 6 recesses without doors"], construction="Card decals on the bank's box doors; two door variants slightly ajar with paper", purpose="Bible IV.1: eighteen occupied boxes and six deliberately empty recesses", sources=["design/ORISON_BIBLE.md IV.1", "game/scripts/props/mail_bank_prop.gd"], preserve="MailBankProp leaf and PlayerBox zone", acceptance="Detail view of the bank reads eighteen different boxes"),
          change("F01_MAIL_TELEPHONE-002", "P1", "add", "Operator's stool, headset, cord pile", objects=["new: F01_operator_stool (ChairOak stool), headset on a hook (signal device), a coil of cords on the floor by the board, an extensions card (Label3D)"], placement="Stool at the board's working height; hook beside the board", signal=SIGNAL_YES, purpose="Bible VIII.4: the operator is the player; the board is Vantry house equipment", preserve="House switchboard prop reach", acceptance="Overview reads a manned board"),
          change("F01_MAIL_TELEPHONE-003", "P2", "refine", "Fix the backs-to-corridor facing if present", objects=["LobbyPorterBoard and LobbyMailBank rotation (punchlist 2026-08-25)"], purpose="Punchlist: both present their backs to the corridor in V1; verify in V2 capture", acceptance="Bank face visible from the door")],
         canon=[C_BIBLE_III, "Bible IV.1 (eighteen boxes)", C_BIBLE_VIII4, C_OWNER], implementation={"sources": ["game/scripts/props/mail_bank_prop.gd", "game/scripts/props/house_switchboard_prop.gd", "game/docs/v2_launch.md"], "dependencies": "none", "preserved": "Mail route, box 4B, board owner", "acceptance": "Mail route and wall-mount tests unchanged"}),
    area("F01_PACKAGE", GP, "ORISON", "The package room: secure parcel handling", "3.8 x 3.7 m between the mail room and the common room with fixed parcel shelving", "the player; Cam's handoffs",
         ("Fixed shelving and nothing on it. Parcels: string-tied brown paper in three sizes with slips, one for 4C (Cam's), one for 6C (an auction crate), one for 2A (caption envelopes), a parcel "
          "book on a ledge, a scale, a stamp pad. The dead-letter table of the matrix (DeadLettersProp) belongs here if it is not elsewhere."),
         [change("F01_PACKAGE-001", "P1", "add", "Parcels, the book and the scale", objects=["new: 8 parcels (desktop_stock) on the shelves, a parcel book (papers), a brass spring scale, a stamp pad"], placement="Parcels by size on the shelves; book and scale on the ledge", purpose="Schedules: Cam's package handoffs; the room's purpose text", preserve="Shelving and the route between doors", acceptance="Overview reads a parcel room")],
         canon=[C_SCHED, C_MATRIX], implementation={"sources": ["art/blender/public_furnishings.md (parcel shelving)"], "dependencies": "none", "preserved": "Shelving, doors", "acceptance": "Public doors test unchanged"}),
    area("F01_COMMON_B", GP, "ORISON", "The common reading room", "6.45 x 9.5 m with two windows, door from the package room; the six-place oak table, fitted chairs and two bookcases", "the tenant association; readers; Evelyn's bake round",
         ("The oak table, chairs and bookcases are installed (reading_furniture.md); sitting and shared reading activities remain unfinished. The room should be the association's: the minutes "
          "on the table under a weight, a water jug and six glasses, the bookcases' contents varied (a run of bound magazines, the building's prospectus's twin, a shelf of left-behind novels), "
          "a pendant over the table, a wall of the building's own paper (the 1928 notice), one armchair by the window with a reading lamp, a plate of Evelyn's cake under a cloth on Saturday. "
          "The player infers the room where the building argues with its landlord."),
         [change("F01_COMMON_B-001", "P1", "add", "The association's table and the armchair", objects=["reading table: minutes (papers) under a brass weight, jug and glasses (desktop_stock); new: armchair (domestic_seating) and a floor lamp (task lamp) by the window"], placement="Papers at the table's head; armchair in the window corner clear of the route", purpose="Schedules: the tenant association meets Saturdays; the room is for meeting and reading", preserve="Table and chairs' walking clearance", acceptance="Overview from the door"),
          change("F01_COMMON_B-002", "P2", "refine", "Bookcase contents", objects=["both bookcases: bookpile objects in varied runs, one shelf of bound magazines"], purpose="Bookcases with nothing read as furniture, not a library", acceptance="Detail views")],
         canon=[C_SCHED, "art/blender/reading_furniture.md"], implementation={"sources": ["art/blender/reading_furniture.md", "game/scripts/building/orison_v2_reading_furniture.gd"], "dependencies": "none", "preserved": "Walking clearance", "acceptance": "Public doors test unchanged"}),
    core("F01_PUBLIC_CORE", GP, "F01 public core: lift and stair", "The passenger lift's ground landing with the interlock (SR7-B), the primary stair and the openings to the lobby and the service transfer; the watch door beside the lift approach", "The lift landing is the building's most used square metre: the brass call plate, the dial, the gate rattle. The floor plate reads street/watch and service. Its unique piece: the lift inspection card.", level="F01"),
    service_hall("F01_CORE_TO_SERVICE", GP, "Core-to-service transfer", "2.9 x 2.0 m controlled transfer between the public core and the service hall", "The threshold between public and service: a painted line, a notice frame, the change in floor finish (terrazzo to concrete).", level="F01"),
    service_hall("F01_SERVICE_HALL", GP, "F01 service hall: the spine with the dumbwaiter", "The 1.2 m x 18.5 m spine from the core transfer to the rear service door, with the dumbwaiter and its ropes, 1D's entry, the staff restroom door and the service core door", "The dumbwaiter (G04) faces into the hall; Teresa's door opens here; deliveries come in at the rear. The hall should carry the trade: a sack truck, crates by the dumbwaiter, the super's chalk, a cage bulb every few metres.", level="F01",
                 extra_changes=[change("F01_SERVICE_HALL-002", "P2", "add", "Sack truck and crates by the dumbwaiter", objects=["new: a sack truck leaning by the dumbwaiter, two crates (crate family)"], placement="Against the wall beside the dumbwaiter opening, outside the 1.2 m route", purpose="G04 dumbwaiter is a working lift; things wait for it", preserve="Dumbwaiter brake reach and the route", acceptance="Threshold view from the transfer")]),
    core("F01_SERVICE_CORE", GP, "F01 service core", "The service lift and stair at the north end of the spine", "The service stair starts here and goes down to the plant; the floor plate names laundry, workshop and boiler.", level="F01"),
    area("F01_STAFF_RESTROOM", GP, "ORISON", "The staff restroom", "2.9 x 3.7 m off the service hall with a basin, WC and register (stack D)", "the player; the watch",
         ("A basin with its two valves, a WC, a register, a dome. It should be the building's own: a roller towel on a bracket, a bar of carbolic, a bucket and mop in the corner (the only mop the "
          "player will see), a notice (Label3D) about the drains."),
         [change("F01_STAFF_RESTROOM-001", "P2", "add", "Roller towel, mop and bucket, carbolic", objects=["new: roller towel bracket (cloth), galvanised bucket with a mop, soap (desktop_stock)"], placement="Towel beside the basin; bucket in the corner clear of the WC stance", purpose="Section E: the mop has somewhere to live; staff sanitation evidence", preserve="Tap and cistern reaches", acceptance="Overview")],
         canon=[C_ENTROPY, C_BIBLE_VIII5I], implementation={"sources": ["game/scripts/building/orison_v2_completion_interiors.gd (staff sanitation)"], "dependencies": "none", "preserved": "Fixture owners", "acceptance": "Completion interiors test unchanged"}),
]
