"""B1: the basement service floor."""
from _common import *

GB = "B1 / basement service floor"
INTRO_B1 = ("<b>The basement.</b> The oldest layer the player works in: the 1912 hand-fired coal boiler that was patched, re-jacketed and never replaced (Bible VIII.5.c), its coal annex with "
            "the gravity chute from the street cover (ORISON_V2_COAL_DELIVERY), the dry electrical room with the fuse panel (G05, implemented), the maintenance shop with its repair bench, "
            "toolboard and parts shelf, eighteen labelled resident storage bays, the laundry with two wringer washers, two rinse tubs and the ceiling airer (Bible VIII.5.d; T02 implemented), "
            "the reading nook with its emeralite lamp off the public core, and the service stair that continues down from F01. WORS 1610 broadcast out of this laundry from 1962 to 1999 "
            "with no transmitter ever found (Bible III); Cal is the transmitter (web I); Juno records the laundry's hum on Thursdays; Teresa has the machines to herself at 03:00 on Saturdays; "
            "Omar checks the breaker panel at 03:00 every night. The owner JSON records the boiler finishes (T01), the laundry cloth (T02) and the basement walls and service context (A04) "
            "as implemented and reviewed. The 2026-10-05 sweep's open findings for B1 were the stair underside, coal heap, alley boundaries and reading-room furniture, since addressed. "
            "What the basement still lacks is the residents' use of it: the storage bays hold nothing, the laundry has no laundry, the nook has no reader.")

AREAS = [
    area("B1_LAUNDRY", GB, "ORISON", "The laundry: WORS 1610 came from here", "7.8 x 7.7 m west basement room off the public core (B1_LAUNDRY_DOOR); two washers, the airer, tubs", "every household on its day; Teresa at 03:00 Saturday; Juno and her recorder on Thursdays",
         ("Two galvanised wringer washers, the rinse tubs with their three draped cloths and the rope-and-pulley airer are installed and operate (WasherProp areas, the airer's lower/raise). "
          "The room should carry the building's week: a posted laundry schedule (Label3D) by the door with pencil tallies, a basket per household left under the airer with a chalked floor "
          "number, Mina's uniformly folded stack on the folding table, Lena's two extra households' loads, Evelyn's wiped-down machines, Omar's deep-service oil can and the bulb he changes. "
          "And the silence where a transmitter should be: a brass signal outlet high on the wall with a cloth lead that goes nowhere, painted over (Accord 11: one anchor painted over; "
          "Bible III). The player infers the most social room in the building, used by everyone and never at the same time, and the one thing in it that cannot be explained."),
         [change("B1_LAUNDRY-001", "P1", "add", "Household baskets and the folding table", objects=["new: 5 wicker baskets (desktop_stock) with chalked floor numbers; a folding table (work_tables) with Mina's uniform stack (cloth family)"], placement="Baskets along the wall under the airer's rope line, clear of the wringer swing; table against the wall opposite the washers",
                 construction="Static desktop_stock and cloth pieces; no new owner; chalk numerals as painted numeral decals (the texture rule allows no lettering; numerals as chalk strokes)", materials="wicker, cotton, chalk", wear="water on the floor between tub and wringer (local wet mask already in A04)", purpose="Schedules: eight households use this room on named days; the room should show the queue", sources=["game/data/resident_schedules.json laundry blocks", "art/blender/laundry_apparatus.md"],
                 preserve="Washer area reaches (lid, release, feed, cocks, drain), airer rope endpoints, standing approaches", acceptance="Overview shows baskets and the table without entering any washer stance"),
          change("B1_LAUNDRY-002", "P1", "add", "The posted schedule and the painted-over signal outlet", objects=["new: schedule board (Label3D text in the telegram grammar) by the door; a brass signal outlet plate at 2.2 m with a cloth lead to nothing, painted over"], placement="Board at 1.5 m beside B1_LAUNDRY_DOOR; outlet high on the north wall (the wall WORS came through)",
                 construction="Notice family board; fixed_lighting-family plate with a lead stub", materials="card, brass under cream paint", signal=SIGNAL_YES, purpose="Bible III: WORS 1610 from the laundry room with no transmitter ever found; Accord 11", sources=["design/ORISON_BIBLE.md III", "design/ORISON_STUDIO_BRIEF.md (the studio shares the laundry's north wall)"], acceptance="Detail view at the north wall reads the plate"),
          change("B1_LAUNDRY-003", "P2", "add", "Omar's deep-service evidence", objects=["new: oil can, a spare belt on a nail, a stepladder folded by the switch (desktop_stock)"], purpose="Schedule: Omar deep-services the machines Saturday mornings", acceptance="Reverse view")],
         canon=[C_BIBLE_III, C_BIBLE_VIII5D, C_SCHED, C_ACCORDS, C_OWNER], group_intro=INTRO_B1,
         implementation={"sources": ["art/blender/laundry_apparatus.md", "art/blender/laundry_fittings.md", "game/scripts/building/orison_v2_laundry.gd", "game/scripts/props/washer_prop.gd"], "dependencies": "T02 cloth batch is implemented; add only static stock", "preserved": "Washer and airer owners, Mina's laundry routine path (OrisonV2MinaLaundryRoutineTest)", "acceptance": "Mina laundry routine and laundry route tests unchanged; overview reads a used room"}),
    area("B1_PUBLIC_CORE", GB, "ORISON", "Basement arrival: the stair foot and the reading nook", "7.6 x 7.7 m core at the foot of the primary stair with the lift pit walls, doors to laundry and storage, the opening to the boiler approach; the reading nook with its emeralite lamp", "everyone bound for the laundry; the reader in the nook",
         ("The stair arrives here under the fitted underside, beside the lift's basement landing. The reading nook (reading_nook.md: an original nook with the emeralite task lamp on its table) "
          "sits in the core; the basement floor plates point to laundry, workshop and boiler. The nook needs its reader's evidence: a book face down, a cold cup, a cushion; the stair foot needs "
          "the building's basement notices (boiler hours, the coal delivery date) and the mat where wet feet stop."),
         [change("B1_PUBLIC_CORE-001", "P2", "add", "The nook's reader", objects=["new: desktop_stock book face down, a cup, a cushion (cloth) on the nook furniture; the lamp as installed"], placement="On nook_table and the nook seat", purpose="Schedules do not name the reader; the nook should look used by whoever reads here at 03:00 (Jonah, probably)", preserve="Nook lamp owner (B1_NOOK_LAMP) and its cord", acceptance="Detail view at the lamp"),
          change("B1_PUBLIC_CORE-002", "P2", "add", "Basement notices at the stair foot", objects=["new: notice frame (Label3D) on the core wall by the floor plate"], purpose="Bible VIII.5.h paper trail; boiler hours and the coal date", acceptance="Readable by the lamp")],
         canon=[C_BIBLE_III, "art/blender/reading_nook.md"], implementation={"sources": ["art/blender/reading_nook.md", "art/blender/basement_fabrication.md", "art/blender/wayfinding_plate.md"], "dependencies": "none", "preserved": "Stair collision, lift landing, nook lamp", "acceptance": "Basement route test unchanged"}),
    area("B1_BOILER_APPROACH", GB, "ORISON", "The boiler approach", "4.1 x 1.2 m lit retreat route from the core to the boiler room's fire door, with the shop door and the electrical recess off it", "the player on the service round; Omar",
         ("A 1.2 m corridor whose whole job is the retreat line from the firing door (ORISON_V2_BOILER_ACCESS). It should read as the one corridor built for a man carrying a shovel: a scuffed "
          "centreline, a coal-dust gradient toward the fire door, a fire bucket of sand on a hook, the breeching's heat showing on the plaster near the door."),
         [change("B1_BOILER_APPROACH-001", "P2", "add", "Sand bucket, coal-dust gradient", objects=["new: fire bucket (desktop_stock) on a wall hook at 1.2 m; coal-dust floor decal gradient toward the fire door"], purpose="Accord 12 and 14: consequence of the firing route", preserve="1.2 m route and the open boiler-door tip clearance", acceptance="Threshold view from the core")],
         canon=[C_BIBLE_VIII5C], implementation={"sources": ["design/ORISON_V2_BOILER_ACCESS_PROGRESS_2026-09-26.md"], "dependencies": "none", "preserved": "Route", "acceptance": "Boiler route test unchanged"}),
    area("B1_BOILER_ROOM", GB, "ORISON", "The boiler room: the 1912 plant", "6.15 x 9.5 m with the boiler on its grounded base, the water column, the breeching to the flue, the operating boiler-well window, doors to the coal room and the service stair", "the player (firing, ash, draft, water column); Omar; Teresa's pre-shift patrol",
         ("The boiler, its firing and ash doors, the draft damper, the water glass, the breeching and the well window are installed and operate; T01's neutral iron and restrained lagging are "
          "reviewed. The room should show the firing routine's evidence: the shovel leaning by the fire door, the ash can and its ring on the floor, the clinker rake, the coal-dust fan from "
          "the coal door, a chalked log on the wall by the water column (dates and levels as strokes), the oil can and rag by the damper. Light is the plant's own: the firebox glow when open, "
          "one cage bulb. The player infers a plant kept alive by hand for sixteen years."),
         [change("B1_BOILER_ROOM-001", "P1", "add", "Firing tools and the ash can", objects=["new: shovel, clinker rake, ash can with lid, oil can and rag (desktop_stock / a small basement tools family)"], placement="Shovel against the wall beside the fire door outside its swing; ash can under the ash door's tip clearance edge with a ring decal; rake on two nails at 1.3 m",
                 materials="steel, galvanised tin, oiled wood handles", wear="the shovel's blade bright, the handle dark", purpose="Bible VIII.5.c: the coal chute, bunker, ash door and water glass all still have jobs", sources=["art/blender/boiler_body.md", "art/blender/boiler_door_swing.md"], preserve="Firing and ash door swings, the control aisle, the water-column stance, the damper route around the south end", acceptance="Overview from the fire door; door-swing test unchanged"),
          change("B1_BOILER_ROOM-002", "P2", "add", "The chalked log by the water column", objects=["chalk-stroke decal column on the wall beside B1_WATER_COLUMN_MASS"], purpose="Accord 13: the plant reads as maintained; Omar's hand", acceptance="Detail view at the column")],
         canon=[C_BIBLE_VIII5C, C_OWNER, C_ACCORDS], implementation={"sources": ["art/blender/boiler_body.md", "art/blender/boiler_pipework.md", "art/blender/boiler_instruments.md", "art/blender/boiler_window.md", "game/scripts/props/boiler_prop.gd"], "dependencies": "T01 implemented; add static stock only", "preserved": "BoilerProp areas, BoilerTend, HeatBalance, window owner", "acceptance": "Boiler route and instrument tests unchanged"}),
    area("B1_ELECTRICAL", GB, "ORISON", "The electrical room: the fuse panel", "4.1 x 4.3 m dry room south of the boiler approach with the fuse panel (G05) and its working front", "the player (fuse repairs); Omar at 03:00",
         ("The fuse panel is implemented and reviewed (G05) and its maintenance activity works. The room should carry the 1912 wiring's stratigraphy: cloth-covered conductors on porcelain cleats "
          "along the wall to the panel, a later conduit run beside them (1928), a knife switch with a wooden handle, a shelf of fuse cartridges in a box, the chalk tallies Omar makes at 03:00, "
          "and the one thing a 1912 demonstration building would have: a brass signal distribution frame with a hundred cloth leads, labelled with blank tags, half of them to points nobody remembers (Bible VIII.3)."),
         [change("B1_ELECTRICAL-001", "P1", "add", "The Vantry signal frame", objects=["new: B1_signal_frame (new native family: a wall-mounted brass terminal frame 1.2 x 0.9 m with cloth leads dressed in bundles to a trunk going up the riser)"], placement="On the wall opposite the fuse panel at 1.2 m, clear of the panel's working front",
                 construction="One native static assembly; INSPECT owner; cloth leads as bundled cylinders; blank tag rectangles", materials="brass, Bakelite terminal blocks, silk-braided leads gone grey", signal=SIGNAL_YES, wear="dust on the upper bundles, finger-polish on the lower terminals", purpose="Bible VIII.3: every flat has a point and nobody remembers what half terminate in; the frame is where they terminate",
                 sources=["design/ORISON_BIBLE.md VIII.3", "art/blender/service_instruments / G05 fuse panel sources"], preserve="Fuse panel working front and activity", acceptance="Overview reads two eras of electricity; fuse activity unchanged"),
          change("B1_ELECTRICAL-002", "P2", "add", "Cleated wiring and the cartridge shelf", objects=["new: porcelain cleats with twisted cloth pair along the wall to the panel; a shelf with a fuse box and Omar's chalk"], purpose="Accord 13 retrofits as timeline; schedule 03:00 check", acceptance="Detail view")],
         canon=[C_BIBLE_VIII2, "Bible VIII.3 (signal points)", C_OWNER], implementation={"sources": ["G05 fuse panel sources in art/data/v2_owner_improvement_20261008.json", "game/scripts/props/fuse_panel_prop.gd"], "dependencies": "none", "preserved": "Fuse panel and its activity", "acceptance": "Service save test unchanged"}),
    area("B1_ELECTRICAL_RECESS", GB, "ORISON", "The electrical recess", "1.8 x 1.0 m recess holding the panel-room leaf's outward swing off the boiler approach", "nobody",
         ("A recess whose only job is the door swing. One thing: the leaf's wear arc on the floor and a fuse cartridge dropped in the corner."),
         [change("B1_ELECTRICAL_RECESS-001", "P3", "add", "Door-arc wear and a dropped cartridge", objects=["floor arc decal; desktop_stock cartridge"], purpose="Accord 12", acceptance="Detail view")],
         canon=[C_ACCORDS], implementation={"sources": ["game/data/orison_v2_blockout.json"], "dependencies": "none", "preserved": "Door swing", "acceptance": "Route unchanged"}),
    area("B1_MAINTENANCE_SHOP", GB, "ORISON", "The maintenance shop: the player's bench", "4.1 x 5.6 m opposite the electrical room with the repair bench, toolboard and parts shelf (b1_repair_bench, b1_toolboard, b1_parts_shelf), doors to the approach and the service stair", "the player; Omar",
         ("The bench, toolboard and parts shelf are installed (the bench is a copy of Omar's). The shop should be the player's, not Omar's: the carried set's spare battery case on charge, a crate of "
          "capsules from HARDWARE PAINT, a vice, the bulb stock, a tally of the service round on the wall, and one broken household thing waiting (a toaster from 4A?). The toolboard's painted "
          "silhouettes with one hook empty (the ladder is HARDWARE PAINT's, not here). The player infers their own workplace and the super they share it with."),
         [change("B1_MAINTENANCE_SHOP-001", "P1", "add", "Stock and the charging case", objects=["new: capsule crate, bulb boxes, a vice on the bench edge, a battery case with a cloth lead to a signal plate, a service-round tally board (Label3D)"], placement="Crate under the bench; bulbs on the parts shelf; vice on the bench's door end; battery case on the floor by the wall; board at 1.5 m",
                 construction="desktop_stock pieces and one Label3D board", signal=SIGNAL_YES, purpose="The complete Mina loop buys the capsule and the player keeps stock somewhere; SR7 apparatus lives here", sources=["game/docs/core_loop.md", "design/ORISON_SERVICE_ROUND_BRIEF.md"], preserve="Bench stance, door swings", acceptance="Overview reads a working shop"),
          change("B1_MAINTENANCE_SHOP-002", "P2", "refine", "Toolboard silhouettes with one empty hook", objects=["b1_toolboard"], construction="Painted silhouette decals behind each tool; one hook with a silhouette and no tool", purpose="Shop guide flair reused honestly: the shadow board", acceptance="Detail view")],
         canon=[C_OWNER, "art/blender/household_wardrobes.md (copied basement repair bench)"], implementation={"sources": ["art/blender/household_wardrobes.md (the copied bench)", "game/scripts/building/orison_v2_basement.gd"], "dependencies": "none", "preserved": "Bench and door owners", "acceptance": "Basement route unchanged"}),
    area("B1_COAL_ROOM", GB, "ORISON", "The coal room: bunker, heap and the street chute", "6.15 x 6.85 m annex off the boiler room with the bunker, fourteen coal-heap fixtures, the gravity chute to the closed street cover and its delivery aperture", "the player; the coalman's delivery is static architecture",
         ("The bunker, heap and chute are installed (coal delivery progress). The room should show delivery and use: a coal shovel and the bunker's board gate, a dust fan from the chute's mouth, "
          "the heap's angle of repose with a shovel cut on the boiler side, a tally of deliveries chalked on the bunker board, a tin lamp on a nail (the only light besides the dome), and "
          "the hopper's rust. Earlier punchlist rows (untextured gray bin, no coal, no grime) were V1 and must be checked against the capture."),
         [change("B1_COAL_ROOM-001", "P2", "add", "Shovel cut, dust fan and the tally", objects=["heap variant with a cut face on the boiler-door side; dust decal fan at the chute mouth; chalk tally strokes on the bunker board; a coal shovel"], purpose="Bible VIII.5.c: coal still has a job; Accord 14 consequence", preserve="Chute geometry and the delivery aperture", acceptance="Overview from the coal door")],
         canon=[C_BIBLE_VIII5C], implementation={"sources": ["design/ORISON_V2_COAL_DELIVERY_PROGRESS_2026-09-26.md", "art/blender/basement_fabrication.md (coal pile)"], "dependencies": "none", "preserved": "Chute, bunker", "acceptance": "Coal delivery test unchanged"}),
    area("B1_RESIDENT_STORAGE", GB, "ORISON", "Resident storage: eighteen bays", "15.4 x 5.65 m with eighteen labelled bays (B1_STORAGE_BAYS) on central and east aisles, door from the public core", "every household; Juno's tape boxes; the Transients' never-collected trunk",
         ("Eighteen bays with labels and nothing in them (the previous sweep's open finding: cage partitions solid, no doors, no contents was a V1 row to recheck). The bays should hold what "
          "eighteen households put in a basement in 1928: trunks, a bicycle (Cam's spare), a pram nobody has had a use for, Lena's bolts, Mae's crated objects under cloths, Omar's bay full of "
          "other people's broken things, Nadia's bay with rolled drawings, the Transients' bay with a trunk whose label has nine dates, and one bay padlocked and empty (2D's or 3C's). The player "
          "infers the building's attic, below ground, and reads each household twice."),
         [change("B1_RESIDENT_STORAGE-001", "P1", "add", "Contents per bay by household", objects=["new: 18 bay contents sets from the crate/desktop_stock/cloth families, one per unit, keyed to the bay label; two bays padlocked and empty"], placement="Inside each bay against its back wall, leaving the aisle clear and the bay door swing (if any)",
                 construction="Static merged kits (max 4 objects per bay) selected by unit id; mesh partitions with chain-link alpha if the cage family supports it", materials="tin trunks, wicker, canvas, timber crates, cloth covers", wear="dust on the bays nobody visits, a clear floor in Omar's and Noel's", purpose="Eighteen households must be legible here as they are upstairs; Accord 14",
                 sources=["game/data/apartment_life_profiles.json (per-unit sets)", "art/blender/domestic_storage.md"], preserve="Aisles and the storage door route", acceptance="Overview down each aisle reads at least six different households"),
          change("B1_RESIDENT_STORAGE-002", "P2", "refine", "Chain-link partitions and bay doors", objects=["B1_STORAGE_BAYS partitions"], construction="Alpha-scissor chain-link material on the partition family; a hinged mesh door per bay (static, closed; one open)", purpose="Previous sweep finding: solid partitions read as walls", acceptance="Overview reads cages")],
         canon=[C_ACCORDS, C_LIFE], implementation={"sources": ["game/scripts/building/orison_v2_basement.gd (storage bays)", "design/ORISON_V2_BASEMENT_PROGRESS_2026-09-26.md"], "dependencies": "none", "preserved": "Bay labels, aisles", "acceptance": "Basement route unchanged"}),
    area("B1_SERVICE_CORE", GB, "ORISON", "Basement service core", "3.7 x 6.2 m service stair continuation with doors to the boiler room and the shop", "the player; Omar",
         ("The service stair's bottom: coal dust on the lowest treads, a bucket of sand, the floor plate. Nothing else."),
         [change("B1_SERVICE_CORE-001", "P3", "add", "Coal dust on the lowest treads", objects=["dust decal on the bottom three treads"], purpose="Consequence of the coal door beside it", acceptance="Detail view")],
         canon=[C_ACCORDS], implementation={"sources": ["game/data/orison_v2_blockout.json"], "dependencies": "none", "preserved": "Stair", "acceptance": "Route unchanged"}),
]
