"""F04: circulation, 4A Peter Wren, 4B the player, 4C Cam Ortiz and Noel Price, 4D Transient Guests."""
from _common import *

GC = "F04 / circulation"
G4A = "F04 / 4A Peter Wren (Case 02, ordained)"
G4B = "F04 / 4B the player"
G4C = "F04 / 4C Cam Ortiz and Noel Price"
G4D = "F04 / 4D Transient Guests"

INTRO_4A = ("<b>Peter Wren, 4A.</b> Legal clerk, rumpled brown sack suit cut in 1919, an overfilled pocket-book distending the breast pocket; every uncertainty demands another form; "
            "uncertainty does not prevent action (Bible I: the ordained second case). Canon: document staging by status, a date stamp, municipal binders, careful shoe placement, an umbrella "
            "drip tray that has overflowed, identical weekday meals in identical tins, a toaster with a replacement form taped to it that was never filed, cleanliness 0.88, the unresolved form "
            "11-B at every station (hero object and contradiction). Decor profile: a measured grid, submission and uncertainty aligned almost too carefully. He was the clerk on the Price appeal who "
            "certified the irregularity to death (web II.1); Evelyn taught him and the note reading See me is in the wallet (web II.6); he checks the mail bank at 07:40 and 18:05 so that nothing "
            "can arrive unobserved; Saturdays the luncheonette's third stool, same order since 1924. <i>Proposed backstory:</i> every unresolved form is the same form at different stages. "
            "<b>Build state:</b> a B-type home with the writing table, dining set, wireless table, radio, sectional bookshelf and story briefs already installed; it needs the staging, the grid and the tray.")

INTRO_4B = ("<b>4B, the player.</b> Night maintenance; the desk is the tidiest thing in the flat (Bible IV) and the case wall is tidier still (life profile contradiction). Canon: the operator's "
            "entry, kettle-toaster survival in the kitchen with the landlord's portable fan, the ordinary eight-day drop-octagon clock that must be wound (Bible VIII.5.e), the Vantry signal terminal "
            "and desk zone, the bespoke wake bed and nightstand in the alcove, the closet with its equipment shelf, the brass mail box 4B downstairs, the carried service set. 4B is where every "
            "dream ends and every shift begins; the alcove bed is the authored bedside. Mara Chen was the previous night tenant of 4B and is still on hold on the line (web II.9). "
            "<i>Proposed backstory:</i> she left one thing in the closet: a service cap with the wrong initials inside the band. <b>Build state:</b> complete in function (desk, bed, kitchen, "
            "bath, closet) and the punchlist's only undressed rooms are its closet and vestibule; the landlord's enamel task lamp is fitted; the 4B kitchen has the C1 roach scatter at the switch.")

INTRO_4C = ("<b>Cam Ortiz and Noel Price, 4C.</b> Two residents, two bedrooms, one negotiated table (hero object): a courier who is never fully still (maroon shell, satchel, knickerbockers, "
            "rest reads as collapse) and a museum preparator (indigo chore coat, white cotton gloves in the pocket, use and change are forms of love). Canon: shared territories, Cam's route by "
            "movement and Noel's objects in a museum-calm bay, bike versus gloves at the door, quick food versus preserved in the kitchen with a dead icebox on Noel's side nobody empties, a battered "
            "copper kettle both use, split sleep, cleanliness 0.5. Cam is Lena's kin and she mends the jersey strap (web II.5); Noel is the convicted man's son and has preserved the family flat into "
            "a museum (web II.1); Jonah, his brother, brings two coffees to the doorway at Sunday noon. <i>Proposed backstory:</i> a chalk line under the oilcloth divides the table; Noel's shelf holds "
            "three objects from the family flat before the trial. <b>Build state:</b> a C-type completion home with two beds correctly kept, a dining set, bookshelf, colour board and wireless table; no "
            "radio; the studio closet holds two wardrobes. It needs the division made visible.")

INTRO_4D = ("<b>The Transient Guests, 4D.</b> A replaceable pair with mismatched luggage and a railway cloakroom ticket knotted to a buttonhole; perpetual departure postpones the decision; departure "
            "is a decision (Bible IV). Canon: hotel wayfinding (impersonal reassurance visible from the exit), host-generic furniture, duplicate house-rules cards, prior guests' lost property (hero "
            "object), inadequate cookware, a cold icebox, rolling luggage, no personal history at all (contradiction), the office converted to a locked owner closet, sleep varies. They were the first "
            "tenants in 1908 and are still checking in (web I); every morning at 07:30 they stand in the lobby with coats on facing the doors; Saturdays they ask for a bill at a desk that has none. "
            "<i>Proposed backstory:</i> the locked closet holds nine previous guests' lost property, each tagged with a date and the room number 4D. <b>Build state:</b> an A-type completion home with "
            "5C templates and a monitor-top where the Bible allows an icebox; the study has a door and no lock; nothing in it is a rental yet.")

AREAS = [
    core("F04_LANDING", GC, "F04 passenger lift landing", "Top of the primary stair flight, lift plate and dial; opening to the west hall", "The player's own landing: the lift is called from here most nights. Jonah pauses on this landing at 17:00 (schedule). Its unique piece: the 1928 lift inspection certificate under glass.", level="F04"),
    public_hall("F04_WEST_HALL", GC, "F04 west hall: the player's approach", "From the landing west to the southwest hall; 4B's entry (F04_DOOR_03)", "the player, the guests",
                "The hall the player walks most. Its threshold evidence is the player's own: a service slip under the door, a boot scuff at the jamb. Noel's Sunday coffees happen at 4C's door on the core, not here.", level="F04"),
    public_hall("F04_SOUTHWEST_HALL", GC, "F04 southwest hall: the rental's approach", "Dead-end hall to 4D's entry (F04_D_ENTRY_DOOR)", "the guests and their luggage",
                "A hotel corridor by accident: luggage scuffs along the wall at case height, a cloakroom ticket on the floor, the mat kicked crooked (nobody squares it).", level="F04"),
    core("F04_PUBLIC_CORE", GC, "F04 public core", "Stair and lift; 4C's entry (F04_C_ENTRY_DOOR) opens here", "4C's door on the core is where the brothers drink their coffee on Sunday (schedule: the door opens at noon); Cam's bicycle wheel marks the wall beside it.", level="F04"),
    public_hall("F04_EAST_HALL", GC, "F04 east hall: Peter's approach", "From the core east to the service crossing", "Peter at 07:55 and 17:30, nobody else",
                "Peter's shoes are placed outside his door at the crossing, not here; this hall is the straightest in the building and he walks its centreline.", level="F04"),
    service_hall("F04_SERVICE_CROSSING", GC, "F04 service crossing: Peter's front door", "The crossing where 4A's entry (F04_DOOR_02) opens onto the spine", "A clerk's door on the service spine: the drip tray outside it has a tide line; the mat is squared. The notice frame here carries the posted laundry schedule he obeys off-peak.", level="F04"),
    service_hall("F04_SERVICE_HALL", GC, "F04 service hall (north)", "The 2.4 m north maintenance route to the service core", "The player's own working corridor on their own floor: a hook for the lamp, a crate of capsules from HARDWARE PAINT, chalk on the risers.", level="F04"),
    service_hall("F04_SERVICE_HALL_SOUTH", GC, "F04 service hall (south)", "Short south run from the crossing", "A dead end with a cage bulb; the mop-shadow corner.", level="F04"),
    core("F04_SERVICE_CORE", GC, "F04 service core", "Service lift and stair", "The service stair the player takes with a crate; the rail is dull.", level="F04"),

    # ------------------------------------------------------------------ 4A
    vestibule("F04_A_VESTIBULE", "4A", G4A, "umbrella_and_stamped_shoes", "2.0 x 2.7 m off the service crossing: the umbrella in its drip tray with a tide mark on the floor, Oxfords with the heel worn outside, a derby a size out on the shelf, a stamped envelope not yet posted. The grid starts here: everything square to the wall.",
              extra_changes=[change("F04_A_VESTIBULE-003", "P2", "add", "Overflowed drip tray with its tide line", objects=["new: 4A_drip_tray (desktop_stock) with a floor tide-line decal"], placement="Beside the door, 0.1 m from the wall", materials="japanned tin, a water line on the oak", purpose="Life profile surface set drip_tray; the one thing he lets overflow", acceptance="Threshold view")], group_intro=INTRO_4A),
    area("F04_A_MAIN", G4A, "ORISON", "Peter's living room: the measured grid", "4.15 x 4.5 m, one window, openings to the vestibule and the private hall", "Peter Wren (20:00: FORMS, his own affairs by post)",
         ("The writing table, the round dining table and two chairs, the wireless table and radio, the sectional bookshelf and the story briefs are installed. The room should be a measured grid: "
          "the writing table square to the window with document stacks staged by status (in, pending, re-check) each under a brass weight, the date stamp and ink pad aligned to the blotter edge, "
          "municipal binders in a row with their spines flush, the two framed pieces (submission and uncertainty) hung on one centreline almost too carefully (decor profile), a drip tray under the "
          "radiator valve, and at this station too an unresolved form 11-B, face up. The player infers a man who files to avoid deciding, and that the grid is the deciding he can do."),
         [change("F04_A_MAIN-001", "P1", "add", "Document staging by status on the writing table", objects=["4A_writing_table (existing)", "4A_story_briefs (existing)", "new: three paper stacks with brass weights, a date stamp, an ink pad, a ruler (desktop_stock)"],
                 placement="Three stacks in a row across the table's back edge, 0.05 m apart, aligned; stamp and pad at the right hand", construction="papers family (FurnitureInteractionPass single-corner owner) and desktop_stock pieces by support id", materials="paper, brass, black japanned stamp, green blotter",
                 wear="the blotter's ink shadow in the shape of his hand", purpose="Life profile surface set document_staging; decor profile measured grid; story panel duplicated forms", sources=["game/data/apartment_life_profiles.json", "design/resident_decor_profiles.json"], acceptance="Detail view of the table"),
          change("F04_A_MAIN-002", "P1", "add", "Municipal binders and the two framed pieces", objects=["F04_4A_BOOKSHELF_01 (sectional, existing): binder row", "new: two CharacterMemoryArt frames on one centreline"], placement="Binders on the bookshelf's middle shelf, spines flush; frames above the writing table at 1.5 m, 0.5 m apart, centred on the table",
                 construction="Bookpile/binder objects as shelf contents; WallArtLaw frames", materials="black cloth binders with blank label squares; black frames", purpose="Life profile municipal_binders; decor profile submission and uncertainty aligned almost too carefully; avoid casual angles", acceptance="Overview reads a grid"),
          change("F04_A_MAIN-003", "P2", "add", "Form 11-B at this station", objects=["new: 4A_form_11b_main (papers single sheet)"], placement="On the dining table, face up, square to the edge", construction="A single-sheet papers object with a form-grid decal (no lettering)", purpose="Hero object unresolved_form_11b at every station; proposed backstory: the same form at different stages", acceptance="Detail view"),
          change("F04_A_MAIN-004", "P3", "refine", "Chairs tucked, radio dial at one station", objects=["4A_din_dc1, 4A_din_dc2", "DomesticRadio_4A"], construction="Both chairs tucked square; radio knob at the news station (visual only)", purpose="A man who has never left a chair out", acceptance="Overview")],
         canon=[C_BIBLE_IV, C_LIFE, C_DECOR, C_STORY, C_WEB], proposed_backstory=["Every unresolved form is form 11-B at a different stage."], implementation=apt_impl()),
    kitchen("F04_A_KITCHEN", "4A", G4A, "identical_weekday_meals", "Identical tins in identical rows on the wall cupboard shelf; five identical lunch pails; the toaster with a replacement form taped to its side (a blank form rectangle, never filed).",
            extra_changes=[change("F04_A_KITCHEN-003", "P2", "add", "Form taped to the toaster", objects=["F04_4A_TOASTER_01: a taped paper rectangle decal on the end panel"], construction="Decal on the toaster variant's end panel; the carriage lever unobstructed", purpose="Appliance Bible III: a toaster with a form taped to it about a replacement he never filed", preserve="ToasterProp carriage, elements and crumb pan", acceptance="Detail view at the toaster")]),
    private_hall("F04_A_PRIVATE_HALL", "4A", G4A, "the hall is authored for document storage: a stack of binder boxes squared against the wall, a form 11-B on top; the shoe tree and a brush on a hook."),
    bath("F04_A_BATH", "4A", G4A, "single_adult_exact", "A bath with a window; a celluloid collar drying on the rail; a form 11-B on the cistern lid (the bathroom station)."),
    area("F04_A_BED", G4A, "ORISON", "Peter's bedroom", "3.3 x 4.0 m, one window, door from the private hall", "Peter Wren",
         ("Bed, wardrobe, nightstand. The 1919 suit on a hanger on the wardrobe door with the collar turned; sock suspenders on the nightstand; the pocket-book on the chair, too full to close, "
          "with a folded red-inked note's corner showing (web II.6, never readable). The bed made with the counterpane's pattern aligned to the bed's edge."),
         [change("F04_A_BED-001", "P2", "add", "The pocket-book and the suit", objects=["new: 4A_pocketbook (desktop_stock: an overfilled wallet with a folded note corner) on 4A_bed0_ns", "4A_w0_wardrobe garment set: brown sack suit, derby"], placement="Nightstand top; wardrobe outer leaf",
                 materials="worn leather, paper, brown wool", purpose="Signature prop (Bible IV) and web II.6 as an object", sources=["design/ORISON_RELATIONSHIP_WEB.md II.6"], acceptance="Detail view of the nightstand")],
         canon=[C_WARD, C_WEB], proposed_backstory=["The folded note in the pocket-book reads only See me, in red."], implementation=apt_impl()),

    # ------------------------------------------------------------------ 4B
    vestibule("F04_B_VESTIBULE", "4B", G4B, "operator", "The punchlist names this one of the only two undressed rooms in the building (0.54 records per square metre median; here zero). The operator's landing set: a service cap, the maintenance keyring on a nail, printed slips under a brass weight, a drip on the mat from the carried set's battery case.",
              extra_changes=[change("F04_B_VESTIBULE-003", "P1", "add", "Keyring nail and slip weight", objects=["new: 4B_key_nail, 4B_slip_stack (papers), 4B_brass_weight (desktop_stock)"], placement="Nail at 1.5 m beside the door; stack on the shelf", purpose="Punchlist: undressed; the player's own routine", acceptance="Threshold view")], group_intro=INTRO_4B),
    area("F04_B_MAIN", G4B, "ORISON", "4B living room: the desk and the case wall", "8.1 x 7.3 m, two windows, openings to vestibule and kitchen, door to the private hall", "the player; callers on the line",
         ("The terminal desk, its chair, the couch, shelf, meal table and chairs, coffee table, wireless table and radio, the projector on its stand and the landlord's enamel lamp are installed. "
          "The desk is the tidiest thing in the flat and the case wall must be tidier: the wall behind the desk carrying the case cards in a grid under the pinboard law, with the Vantry terminal "
          "and the dial-less house telephone beside it; the rest of the room lived in badly by someone who sleeps at odd hours: a blanket on the couch, a mug ring on the coffee table, a slip "
          "stuck in the radio's grille. The drop-octagon clock on the wall where the desk chair can see it (it must be wound; hold E). The punchlist's featureless white box must be identified in "
          "the capture. The player infers themselves, and that the only order in their life is on the wall."),
         [change("F04_B_MAIN-001", "P1", "add", "The case wall", objects=["new: 4B_case_wall (pinboard family 1.4 x 1.0 m) behind 4B_terminal_desk with card grid and strings; one owner (single tack)"], placement="Centred over the desk at 1.4 m, clear of the terminal's visual", construction="Pinboard variant, FurnitureInteractionPass, cards as blank rectangles",
                 materials="cork, card, red string", purpose="Life profile surface set case_wall; contradiction: the tidiest thing is the case wall", sources=["game/data/apartment_life_profiles.json"], preserve="DeskZone sit/stand, SignalTerminalProp visual, call interface", acceptance="Detail view from the desk chair"),
          change("F04_B_MAIN-002", "P1", "add", "The drop-octagon clock, winding owner preserved", objects=["existing 4B windable ClockProp (matrix) if present in V2; else install it from the clock family"], placement="On the wall beside the private-hall door at 1.8 m, visible from the desk chair", dimensions="0.45 m case",
                 construction="ClockProp with the hold-E winding verb and its work order; no signal", signal=SIGNAL_NO, purpose="Bible VIII.5.e: 4B has an ordinary eight-day drop-octagon clock set wrong from the lobby master", sources=["design/ORISON_BIBLE.md VIII.5.e", "design/PROP_SET_INTERACTION_MATRIX.md 4B windable clock"],
                 preserve="Winding verb and its WorkOrders binding", acceptance="Detail view; hold E winds"),
          change("F04_B_MAIN-003", "P2", "add", "Badly lived-in: blanket, mug ring, slips", objects=["new: cloth blanket on 4B_couch; desktop_stock mug and a slip on 4B_coffee"], purpose="Life profile cleanliness 0.5, sleep odd hours; the contrast with the desk", acceptance="Overview from the vestibule"),
          change("F04_B_MAIN-004", "P2", "refine", "Identify and remove the punchlist's featureless white box if it persists", objects=["unknown: the tall white box reported in F04_B_MAIN (walkthrough_punchlist.md)"], purpose="A primitive placeholder in the player's own room is a blocker-class legibility defect", acceptance="Overview and reverse show no untextured box; if the capture shows none, close the row")],
         canon=[C_BIBLE_IV, C_LIFE, C_BIBLE_VIII5E, C_MATRIX], implementation=apt_impl(preserved="DeskZone, call interface, SignalTerminalProp, ProjectorProp throw, radiator, radio owner, the landlord lamp's G14 cord, the 4B semantic requirements (mattress, clothing storage, kitchen sink, cold storage, cooking surface, trash, desk, bath)")),
    kitchen("F04_B_KITCHEN", "4B", G4B, "kettle_toaster_survival", "The kettle and toaster on a counter otherwise bare; the landlord's portable fan on the floor by the opening (box fan, OPERATE); a tin of biscuits; the C1 roach scatter at the switch is landed and must stay. A trash can is one of the 4B semantic requirements.",
            extra_changes=[change("F04_B_KITCHEN-003", "P1", "add", "Trash can and the landlord's fan", objects=["new: 4B_trash (desktop_stock galvanised can with lid)", "existing or new: 4B box fan (BoxFanProp)"], placement="Can under the counter end; fan on the floor beside the opening, cord to the outlet", purpose="4B semantic requirement trash; Appliance Bible: landlord-supplied portable fan", preserve="C1 commensal scatter anchor at the switch", acceptance="Overview")]),
    private_hall("F04_B_PRIVATE_HALL", "4B", G4B, "the hall turns to the alcove approach; a hook for the carried set's lamp when the player sleeps."),
    area("F04_B_ALCOVE_APPROACH", G4B, "ORISON", "4B alcove approach and the closet door", "3.0 x 1.9 m between the private hall and the alcove; the closet door opens here", "the player",
         ("A short distribution space with the closet switch outside the closet door. It carries the route from bed to bath at 3 a.m.: a floor runner worn in the middle, nothing else."),
         [change("F04_B_ALCOVE_APPROACH-001", "P3", "add", "Worn runner", objects=["new: 4B_runner (floor cloth family 0.7 x 2.0 m)"], placement="Centred on the route", materials="jute runner worn through in the centre", purpose="Accord 12 on the player's own route", acceptance="Overview")],
         canon=[C_ACCORDS], implementation=apt_impl()),
    bath("F04_B_BATH", "4B", G4B, "single_adult", "A window bath; the player's own: a razor, a tin of tooth powder, the towel never squared."),
    area("F04_B_CLOSET", G4B, "ORISON", "4B closet: equipment and the previous tenant", "1.6 x 2.2 m closet with the equipment shelf, door from the alcove approach", "the player",
         ("Undressed in the punchlist. The equipment shelf should hold the maintenance stock the loop uses (a capsule tin, fuse cartridges, a coil of cloth flex, a lamp bulb box) and the clothes "
          "storage the 4B requirements demand (a rail with the charcoal hoodie and work trousers). On the top shelf, one thing that is not the player's: a service cap with the wrong initials "
          "inside the band (proposed backstory: Mara Chen)."),
         [change("F04_B_CLOSET-001", "P1", "add", "Clothing rail and maintenance stock", objects=["4B_equipment_shelf (existing, Shelf01)", "new: 4B_closet_rail with garment silhouettes (cloth family), desktop_stock: capsule tin, fuse box, flex coil, bulb box"], placement="Rail across the closet at 1.7 m; stock on the shelf in a row",
                 construction="Wardrobe-family rail without leaves; desktop_stock pieces", materials="iron rail, charcoal jersey, tin, card", purpose="4B semantic requirement clothing_storage; punchlist undressed room", acceptance="Threshold view from the approach with the door opened"),
          change("F04_B_CLOSET-002", "P2", "add", "The previous tenant's cap", objects=["new: 4B_old_cap (desktop_stock service cap) on the top shelf"], purpose="Web II.9 Mara Chen made an object; INSPECT only, no case fact", sources=["design/ORISON_RELATIONSHIP_WEB.md II.9"], acceptance="Detail view of the top shelf")],
         canon=[C_LIFE, C_WEB], proposed_backstory=["A service cap with the wrong initials inside the band, left by the previous night tenant."], implementation=apt_impl()),
    area("F04_B_ALCOVE", G4B, "ORISON", "4B sleeping alcove: where every dream ends", "5.1 x 5.3 m, two windows, opening from the approach; the wake bed and nightstand", "the player; the wake return",
         ("The authored bedside: the box-built wake bed and its nightstand, two windows. Everything here is protected by the wake contract (the bedside derived from the unique F04 bed record). "
          "Dress around it, not on it: the nightstand with the carried set's cradle mark and a slip, the window blinds half down, a pair of boots at the bed foot, the counterpane thrown back "
          "because the player never makes it. The player infers their own exhaustion."),
         [change("F04_B_ALCOVE-001", "P1", "keep", "Keep the wake bed and nightstand exactly", objects=["4B_wake_bed", "4B_wake_nightstand"], purpose="CoreLoopDirector returns the player to the bedside derived from this record; CampaignShell rebuilds here", sources=["game/docs/core_loop.md", "game/docs/dream_boundary.md"], acceptance="OrisonV2WakeReconstructionTest unchanged"),
          change("F04_B_ALCOVE-002", "P2", "add", "Thrown-back bedding, boots, slip on the nightstand", objects=["4B_wake_bed bedding slack variant", "new: desktop_stock boots and a slip"], placement="Boots at the bed foot outside the wake stance; slip on the nightstand", construction="Bedding family variant (A03 bedding batch); desktop_stock", purpose="Sleep odd hours; the one bed in the building that is used at every hour", preserve="Wake stance and bedside clearance", acceptance="Overview from the approach")],
         canon=[C_LIFE, "game/docs/core_loop.md (wake bedside)"], implementation=apt_impl(preserved="The unique F04 bed record, the bedside return anchor and its clearance, the alcove light switch")),

    # ------------------------------------------------------------------ 4C
    vestibule("F04_C_VESTIBULE", "4C", G4C, "bike_vs_gloves", "2.7 x 2.5 m off the public core: a bicycle wheel leaning where it should not, the satchel on the floor, and on the other wall a brushed hat and a folded pair of white gloves on a clean shelf. Two tenants, two walls.", group_intro=INTRO_4C),
    area("F04_C_MAIN", G4C, "ORISON", "The negotiated table", "6.1 x 5.3 m, one window, openings to vestibule, studio and private hall", "Cam Ortiz, Noel Price; Jonah at the door on Sundays",
         ("The dining set, bookshelf, wireless table and colour board are installed; no radio. The room should show two territories sharing one surface: the table set for two people who eat "
          "separately (two placings at opposite ends, one with a paper-wrapped sandwich and a bike lamp, one with a folded napkin and a condition-report card), a chalk line under the oilcloth "
          "visible at the hem; Cam's corner by the door with the bike pump, a spare tube and road snacks; Noel's bay by the window with a museum-calm shelf of three objects under a cloth. Both "
          "tenants visible, neither disappearing (decor profile). The player infers a negotiation that has lasted longer than either expected."),
         [change("F04_C_MAIN-001", "P1", "add", "Two placings and the chalk line", objects=["4C_din_t (existing) with new desktop_stock: two placings, a sandwich in paper, a bike lamp, a napkin, a card; a chalk-line decal under the oilcloth hem"], placement="Placings at opposite ends; the line across the table's middle under the cloth",
                 construction="desktop_stock by support id; oilcloth as a cloth-family cover with a hem", materials="oilcloth, paper, brass lamp, linen", purpose="Hero object the_negotiated_dining_table; contradiction: set for two people who eat separately", sources=["game/data/apartment_life_profiles.json"], acceptance="Detail view of the table"),
          change("F04_C_MAIN-002", "P1", "add", "Cam's courier corner and Noel's museum bay", objects=["new: 4C_pump, 4C_tube, 4C_snacks (desktop_stock) on the floor by the vestibule opening", "new: 4C_museum_shelf (Shelf01) under the window with three covered objects and a folded cloth"], placement="Corner beside the vestibule opening; shelf under the window sill",
                 construction="Shelf family with three small objects under a muslin cloth (cloth family)", materials="rubber, brass, muslin, acid-free card", purpose="Life profile surface sets courier_corner and archival_shelf; proposed backstory: three objects from the family flat before the trial", sources=["design/ORISON_RELATIONSHIP_WEB.md II.1"], acceptance="Overview reads two sides"),
          change("F04_C_MAIN-003", "P2", "add", "Domestic radio", objects=["new: DomesticRadio_4C on 4C_wireless_table"], signal=SIGNAL_YES, purpose="No radio in data", acceptance="Radio operable"),
          change("F04_C_MAIN-004", "P2", "refine", "Colour board becomes Cam's route map", objects=["4C_story_colorboard"], construction="Pin a route-line decal and ticket stubs (no lettering) to the existing board", purpose="Decor profile: Cam's route by movement", acceptance="Detail view")],
         canon=[C_LIFE, C_DECOR, C_APPL, C_WEB], proposed_backstory=["A chalk line under the oilcloth divides the table.", "Noel's shelf holds three objects from the family flat before the trial."], implementation=apt_impl()),
    kitchen("F04_C_KITCHEN", "4C", G4C, "quick_food_vs_preserved", "One kitchen, two centuries: Cam's side quick food in paper, Noel's side preserved and labelled; the icebox is dead on Noel's side and nobody empties the tray (a dry tray, a dust line); the battered copper kettle both use.",
            extra_changes=[change("F04_C_KITCHEN-003", "P2", "add", "The copper kettle and the dry tray", objects=["new: 4C_copper_kettle (desktop_stock) on the range; the icebox drip tray dry and dusty"], materials="battered copper, zinc tray with dust", purpose="Appliance Bible III: the kettle is evidence, the dead icebox nobody empties", acceptance="Detail view")]),
    private_hall("F04_C_PRIVATE_HALL", "4C", G4C, "a 6.6 x 1.5 m hall serving bath, kitchen and both bedrooms: a bicycle leans along one wall (the only place it fits) with a 0.8 m route kept; Noel's work coat hangs on the other wall."),
    area("F04_C_STUDIO", G4C, "ORISON", "4C studio closet: divided storage", "3.4 x 2.5 m, opening from the main room, two wardrobes", "both",
         ("Two wardrobes for two tenants: one with the maroon jersey and knickerbockers and a satchel hung by its strap, one with the indigo coat and brushed hat, a box of white gloves. "
          "The division is the content."),
         [change("F04_C_STUDIO-001", "P2", "refine", "Two garment sets", objects=["4C_w0_wardrobe (Cam), 4C_w1_wardrobe (Noel)"], construction="Garment silhouette sets per wardrobe", materials="maroon jersey, indigo drill", purpose="Wardrobe bible per resident", acceptance="Open leaves show different wardrobes")],
         canon=[C_WARD], implementation=apt_impl()),
    bath("F04_C_BATH", "4C", G4C, "two_adults_divided", "Two of everything on opposite sides of the basin; two towels on separate hooks; a tape line on the shelf nobody admits to."),
    area("F04_C_BED1", G4C, "ORISON", "Cam's bedroom", "3.3 x 3.8 m, one window", "Cam Ortiz (sleeps late, rides early; never fully still)",
         ("Bed and nightstand; the jersey pulled back over the shirt on the chair, one sock, the cycling cap on the bedpost, the bed not made because they came in and did not fully undress. "
          "Lena's mend on the jersey shoulder in non-matching wool (web II.5)."),
         [change("F04_C_BED1-001", "P2", "add", "Jersey with the mended shoulder on the chair", objects=["new: 4C_bed1_chair (ChairOak) with a cloth jersey silhouette, patch decal"], placement="Chair at the bed foot", purpose="Web II.5 made an object; wardrobe bible late-night state", acceptance="Detail view")],
         canon=[C_WARD, C_WEB], implementation=apt_impl()),
    area("F04_C_BED2", G4C, "ORISON", "Noel's bedroom", "3.3 x 3.8 m, one window", "Noel Price (tidiest 3 a.m. in the building)",
         ("Bed made with the folded edge aligned, carpet slippers with their backs intact, the work coat hung, the gloves folded on the nightstand beside a condition report. Nothing used; everything placed."),
         [change("F04_C_BED2-001", "P2", "add", "Slippers, gloves and the condition card", objects=["new: desktop_stock slippers under the bed, gloves and a card on 4C_bed1_ns"], purpose="Wardrobe bible: slippers with the backs intact; the museum register at home", acceptance="Detail view")],
         canon=[C_WARD, C_LIFE], implementation=apt_impl()),

    # ------------------------------------------------------------------ 4D
    vestibule("F04_D_VESTIBULE", "4D", G4D, "rolling_luggage", "2.6 x 2.7 m with three doors: a cardboard case and a gladstone bag that do not match, a railway ticket on the shelf, a hotel-style rules card, no coat hooks in use. Hotel wayfinding: a card on the door back with an arrow (no lettering) pointing to the exit.",
              extra_changes=[change("F04_D_VESTIBULE-003", "P2", "add", "Luggage and the rules card", objects=["new: 4D_case, 4D_gladstone (crate/desktop_stock luggage variants), 4D_rules_card (pinboard-family card)"], placement="Luggage against the wall opposite the door; card on the door back at 1.5 m", purpose="Entry set rolling_luggage; decor profile hotel wayfinding", acceptance="Threshold view")], group_intro=INTRO_4D),
    area("F04_D_MAIN", G4D, "ORISON", "4D: the short-term rental's front room", "7.45 x 3.35 m, one window, doors to vestibule, kitchen and bedroom", "the guests, whoever they are this week",
         ("A 5C-template table and chair. It should be host-generic: a matched set that nobody chose, a lamp with a paper shade, a second house-rules card, a tray with two glasses turned down, "
          "takeout debris and transit stubs (story panel), a half-packed bag open on the floor, and on the wall one impersonal print. No photographs. No personal history at all. The player infers "
          "that the history is the absence, and that the room has been checked into for twenty years."),
         [change("F04_D_MAIN-001", "P1", "add", "Host-generic set", objects=["new: 4D_settee (Sofa195), 4D_lamp (task lamp landlord_enamel variant on a side table), 4D_wireless_table (TableRect07), DomesticRadio_4D, 4D_print (CharacterMemoryArt)", "existing 4D_table, 4D_chair plus a second chair"],
                 placement="Settee under the window, lamp table beside it, radio table on the long wall, dining table by the kitchen door with two chairs", construction="Shared variants; the landlord's lamp variant repeated from 4B", materials="moquette in a colour nobody chose, paper shade, walnut", signal=SIGNAL_YES,
                 wear="even, light, impersonal: the settee's two cushions equally crushed", purpose="Life profile surface set host_generic; decor profile impersonal reassurance", acceptance="Overview from the vestibule reads a furnished let"),
          change("F04_D_MAIN-002", "P2", "add", "Left behind and half packed", objects=["new: desktop_stock: takeout cartons, transit stubs (papers), an open case on the floor (crate family open variant)"], placement="Case open by the bedroom door, out of the swing", purpose="Story panel: takeout debris, transit stubs, half-packed bags; surface set left_behind", acceptance="Reverse view"),
          change("F04_D_MAIN-003", "P2", "refine", "Identify the punchlist's lumpy white mass", objects=["unknown: the giant untextured mass reported in F04_D_MAIN (walkthrough_punchlist.md)"], purpose="Close or fix the V1 row against the V2 capture", acceptance="No untextured mass in any view"),
          change("F04_D_MAIN-004", "P2", "refine", "Pendant instead of flush dome", objects=["F04_D_MAIN_LT"], construction="pendant_shade variant", purpose="Living-room family", acceptance="RoomLumaAudit unchanged")],
         canon=[C_LIFE, C_DECOR, C_STORY], implementation=apt_impl()),
    kitchen("F04_D_KITCHEN", "4D", G4D, "inadequate_cookware", "One pan for everything, hotel-issue; the icebox cold and dry with its ice card blank; a house-rules card about the gas. The monitor-top in data should be an icebox never iced (Bible VIII.5.a; Appliance Bible: never turned on).",
            fridge="monitor", extra_changes=[change("F04_D_KITCHEN-003", "P2", "refine", "Monitor-top to a dry icebox", objects=["F04_4D_FRIDGE_01 (FridgeMonitor -> FridgeIcebox)"], construction="Variant swap; dry tray; blank ice card", purpose="Bible VIII.5.a four electric flats; the rental's fridge was never run", acceptance="Fridge module passes")]),
    private_hall("F04_D_PRIVATE_HALL", "4D", G4D, "a hall between two doors with a duplicate rules card on the wall; a wire hanger on the knob."),
    bath("F04_D_BATH", "4D", G4D, "rental_minimal", "Hotel-issue soap, one thin towel each, one of them clearly the building's (wardrobe bible), a rules card about the bath."),
    area("F04_D_BED", G4D, "ORISON", "4D bedroom", "4.35 x 5.15 m, one window, doors to the main room and the owner's closet", "the guests",
         ("Template bed and wardrobe. Two single beds would be the rental's truth but the plan gives one: make it a double with two pillows that do not match, one in a borrowed nightshirt's "
          "fold, the case open on the floor still packed, the wardrobe empty with its hangers wired together. The locked closet door is beside the bed with a brass plate (no lettering) and a lock."),
         [change("F04_D_BED-001", "P2", "add", "Mismatched pillows, packed case, wired hangers", objects=["4D_bed bedding variant with two pillows", "new: open case (crate family), 4D_wardrobe garment set empty with hangers"], purpose="Wardrobe bible late-night state; no personal history", acceptance="Overview")],
         canon=[C_WARD, C_LIFE], implementation=apt_impl()),
    area("F04_D_STUDY", G4D, "ORISON", "4D locked owner's closet (converted study)", "3.1 x 2.7 m with a window, door from the bedroom (F04_D_BED_STORAGE_DOOR)", "the landlord; nine previous guests",
         ("Empty today, with an ordinary unlocked door. The profile converts it into the locked owner closet: the door locked (a RESIST-REFUSE reason: the owner's storage), and inside, "
          "visible only by teleport, the lost property of previous guests on shelves, each tagged. The player never enters; the locked door is the object."),
         [change("F04_D_STUDY-001", "P1", "refine", "Lock the closet door", objects=["F04_D_BED_STORAGE_DOOR leaf_state closed -> locked"], construction="Door source record change in completion_interiors (leaf_state locked); the matrix's locked-door count rises by one and the card gives the owner's reason",
                 purpose="Life profile room conversion locked_owner_closet", sources=["game/data/orison_v2/completion_interiors.json doors", "design/PROP_SET_INTERACTION_MATRIX.md locked doors"], preserve="Resident key rules (no guest key)", acceptance="E rattles with a reason; door route test updated"),
          change("F04_D_STUDY-002", "P3", "add", "Lost property shelves (interior, unseen in play)", objects=["new: 4D_lost_shelves (Shelf01 x2) with tagged objects (desktop_stock)"], purpose="Hero object prior_guest_lost_property; proposed backstory: nine guests, every tag says 4D", acceptance="Teleported capture only")],
         canon=[C_LIFE], proposed_backstory=["The closet holds nine previous guests' lost property, each tagged with a date and the room number 4D."], implementation=apt_impl(), coverage="inaccessible_teleported"),
]
