"""Building-wide findings: defects and designs that cut across many rooms. One
pseudo-area whose change ids (BW-nnn) are referenced by the room pages. It has
no capture of its own; the evidence is the room sheets cited in each change.
"""
from _common import *

G = "BUILDING-WIDE / systemic findings and shared families"

AREAS = [
    area("BW_BUILDING_WIDE", G, "ORISON", "Systemic findings that no single room can fix", "Every floor; the evidence is the room sheets named in each change", "every resident; the player",
         ("The room-by-room review repeats a small number of findings in dozens of rooms. They are listed once here with stable ids so the room pages can cite them instead of restating them, "
          "and so the implementing agent can fix a family rather than a room. In order of how much they cost the building's credibility: the six completion-interior homes are furnished with "
          "copied templates (1D carries a seamstress's furniture; 1A, 3D and 4D have only a bed, wardrobe, table and chair; 3D has no range); the three converted second bedrooms are not "
          "converted; several shared furniture variants read post-1950 (tulip-pedestal round tables, chrome wire shelving, square-steel-post shelves, slab-cushion sofas); bath tile is applied to "
          "both faces of bath walls so it shows in halls and bedrooms; ventilation ducts and their hangers end in air; the service spine is a bare block-out shell with no risers, lights or "
          "finishes; windows are bare of curtains and blinds everywhere at 20:00; bedding is flat slabs; shower curtains are rigid fluted cylinders; mirrors hang tilted off walls; cold cyan light "
          "leaks around door leaves and openings with no visible source; six homes have no radio; completion-interior main rooms are lit by flush domes where every authored living room has a "
          "pendant. None of these is a texture problem; they are variant, family and data problems, which is why they are cheap to fix once and expensive to fix per room."),
         [change("BW-001", "P1", "refine", "Completion-interior homes: replace copied templates with resident sets", objects=["completion_interiors_source.json records for 1A, 1D, 2C, 3D, 4C, 4D (templates copied from 5C and 2B)"],
                 construction="Author per-unit furniture records in the completion source with the resident's program (see the unit pages: F01_A_MAIN-001..006, F01_D_MAIN-001..005, F02_C_MAIN-001, F03_D_MAIN-001..004, F04_C_MAIN-001..004, F04_D_MAIN-001..004) and re-project; add the missing range to 3D (F03_D_KITCHEN) and radios to 1A, 1D, 2C, 3D, 4C, 4D",
                 purpose="Six of eighteen homes are spatially proven and visually anonymous; one is furnished as the wrong trade", sources=["art/data/orison_v2/completion_interiors_source.json", "tools/build_v2_authoring_projection.py", "design/ORISON_V2_COMPLETION_INTERIORS_CHECKPOINT_2026-09-25.md"],
                 preserve="Doors, taps, showers, toilets, stoves, fridges, switched lights and the 144-waypoint route of the completion checkpoint", acceptance="Threshold views of all six homes identify the resident; OrisonV2CompletionInteriorsTest passes with the new records"),
          change("BW-002", "P1", "refine", "Convert the three second bedrooms", objects=["2C_bed1/2C_bed1_ns", "5C_bed1/5C_bed1_ns", "6C_bed1/6C_bed1_ns"], construction="Remove the second beds and install the recording room, painting studio and provenance archive per F02_C_BED2, F05_C_BED2 and F06_C_BED2; keep 4C's two beds",
                 purpose="Lived-in brief: no single resident occupies two generic made beds; life profiles declare the conversions", sources=["game/data/apartment_life_profiles.json room_conversions", "design/CLAUDE_APARTMENT_LIVED_IN_PASS.md 4"], acceptance="Sleeper count equals resident count in every unit"),
          change("BW-003", "P1", "refine", "Retire the post-1950 furniture variants", objects=["TableRound03 (tulip pedestal) in 2A, 3B, 4A (4A_din_t), 4B (4B_meal_table); TableRound10, the same flared pedestal, in 5B (5B_din_t), 6A and 6C; Shelf04 chrome wire units in 2A; Shelf01 steel posts (2B_fabric_shelf_01/02, 3B_tools0/1, 4B_equipment_shelf, b1_parts_shelf), 4B_shelf (Shelf02 grey steel rack) and 5A_planshelf (Shelf07 thin grey posts); Sofa195/Sofa210 slab cushions (6C_sofa, 4B_couch)"],
                 construction="Add period variants to domestic_tables (a turned-leg oak round table), domestic_storage (an oak open shelf unit with turned posts) and domestic_seating (a sprung moquette sofa with rolled arms) and rebind the affected instances; the shared-mesh factory keeps every actor identity",
                 materials="oak, moquette, dull nickel only where a 1927 object would have it", purpose="Bible VIII.4: no injection-moulded colour, no stainless; a 1957 tulip table in a 1928 flat is a texture-independent anachronism", sources=["art/blender/domestic_furniture.md", "game/data/orison_v2/domestic_tables.json", "domestic_storage.json", "domestic_seating.json"],
                 preserve="All 41 seating and 62 table actor identities, supports and the exact shared-mesh contract", acceptance="No tulip pedestal or chrome wire in any overview; apartment furniture batch passes"),
          change("BW-004", "P1", "refine", "Bath tile on one face only", objects=["bath wall finish quads in every unit (2C, 3B and others show tile on the hall and bedroom faces; F04 review: 4B closet side wall, 4C vestibule, 4C private hall on two walls, 4C kitchen; F05 review: 5A private hall and study, 5B main room, vestibule and kitchen end wall, 5C vestibule and private hall)"], construction="The baked wall finish must flip with side (the WK-1 fix for plaster facing); apply the same side-aware emission to the tile family so the room-side face is tile and the far side is the neighbouring room's plaster",
                 purpose="A bedroom with subway tile on one wall reads as a bathroom", sources=["design/walkthrough_punchlist.md WK-1 (build_baked_wall_finish winding)", "art/blender/building_surface_finish.md"], acceptance="No tile visible from any hall, bedroom or kitchen station"),
          change("BW-005", "P1", "refine", "Ducts and hangers must terminate and seat", objects=["ventilation branch sheets and trapeze hangers in 2D, 3C and the baths (duct_supports.md); the register that ends in a lamp-like shade; F04/F05 review: louvred boxes on square sheet-metal ducts in the 4B, 4C and 4D baths (F04_B/C/D_BATH_VENT_REGISTER), grey box registers in 5A, 5B and 5C, the 5C vestibule duct whose end hangs in mid-air by the door head, and the 5D floor-level duct strip rising to a box register"], construction="Hangers rise to the slab soffit and seat (the fitted trapezes of duct_supports.md); the duct closes into the chase with a collar; registers are the painted gravity grille variant (vent_register.md), never a shade",
                 purpose="Accord 11: nothing floats; Bible VIII.5.i: inside a flat there is only a painted gravity register", sources=["art/blender/duct_supports.md", "art/blender/vent_register.md", "art/blender/ventilation_fabric_ports.md"], acceptance="2D and 3C overviews show seated hangers; no register reads as a lamp"),
          change("BW-006", "P1", "refine", "The service spine is a shell: give it risers, cage bulbs, a dado and a lift", objects=["F02-F06 SERVICE_HALL, SERVICE_HALL_SOUTH, SERVICE_CROSSING, SERVICE_CORE"], construction="Install the exposed risers with lagging (heating_distribution.md) through the halls, a cage bulb per 4 m (fixed_lighting cage family), a painted dado and concrete floor finish, pipe tags; the service core needs its service lift landing doors and a plain stair finish distinct from the public marble",
                 purpose="The spine is the player's own route and reads as block-out; the public stair's marble on the service stair is a wrong copy", sources=["art/blender/heating_distribution.md", "art/blender/fixed_lighting.md", "art/blender/stair_honed.md"], preserve="Routes, the dumbwaiter, door swings", acceptance="Service hall overviews show lit, piped, finished corridors"),
          change("BW-007", "P2", "add", "Window treatments everywhere, by sleep schedule", objects=["every apartment window (W-GLAZE/W-SHOW joinery family)"], construction="Add a blind and a curtain pair variant to the window joinery family with a state per unit (blackout down for day sleepers, lace for 1A and 6C, bare for 2C and 6A, paint-stained for 5C), driven by the sleep_schedule the window-glow authority already reads",
                 purpose="Lived-in pass: window treatment state matches sleep schedule; bare windows at 20:00 in November read as vacancy", sources=["TASKS.md W-GLAZE/W-SHOW/W-JOINERY", "game/data/apartment_life_profiles.json"], acceptance="Facade wide station reads curtain states; every bedroom overview shows a treatment"),
          change("BW-008", "P2", "refine", "Bedding, shower curtains and mirrors", objects=["bedding family slabs; shower-curtain rigid cylinders (B4 cloth batch); medicine cabinet mirrors hanging off the wall"], construction="Bedding: the A03 native beds carry the slack variant; apply it to the completion beds too. Curtains: the B4 drawn/gathered variation with hems must replace the fluted cylinder in every bath. Mirrors: seat the cabinet flush (the two fixings of household_accessories.md). Receptors: bathroom_details.md gives the shower a coved enamel tray, drain grille and hems clearing the rim by 25 mm, yet no capture of 4A, 4C, 4D or 5A shows a tray under the curtain; confirm the installed shower GLB is the rebuilt one and that the tray is not culled by the curtain pose",
                 purpose="Three families seen in every home", sources=["art/blender/bedding.md", "art/blender/household_accessories.md", "cloth batch B4 in art/data/v2_owner_improvement_20261008.json"], acceptance="Bath and bed overviews across floors"),
          change("BW-009", "P2", "refine", "Cold cyan light leaks and sky reflections at night", objects=["door-leaf slits, hall openings and the public core marble showing a cool blue light with no fixture (F02, F03 reviews); a thin bright vertical line or yellow strip beside the stair in the F04 and F05 public cores and east halls; two dark triangular artefacts above the F05 stair (TH tile); the bright slot along the F04 service core ceiling edge and the bare lintel glow in the F05 service core (RV)"], construction="Find the source (sky/moon contribution through the voxel field or an ungoverned light) and clamp it; Accord 15: every lumen has a fixture",
                 purpose="A cyan glow on a 1928 stair reads as a modern fixture or a defect", sources=["game/scripts/building/light_rig.gd", "design/V2_LAMP_SURFACE_BALANCE_2026-10-05.md", "TASKS.md L13/L14"], acceptance="Public core night stations show only warm practical light"),
          change("BW-010", "P2", "refine", "Pendants for the completion-interior living rooms", objects=["F01_A_MAIN_LT, F01_D (has pendant), F03_D_MAIN_LT, F04_D_MAIN_LT flush domes"], construction="Swap to the pendant_shade variant at the authored anchor", purpose="Every authored living room is lit by a pendant; the copies are not", sources=["game/data/orison_v2/fixed_lighting.json"], acceptance="RoomLumaAudit unchanged"),
          change("BW-011", "P2", "add", "A domestic radio in every home", objects=["new DomesticRadio_1A, _1D, _2C, _3D, _4C, _4D on their wireless tables (add tables to 1A and 3D)"], signal=SIGNAL_YES, purpose="Bible VIII.4: everyone has a means of recording and listening; six homes have none", sources=["game/data/orison_v2/domestic_radios.json"], acceptance="Twelve radios become eighteen; each operates"),
          change("BW-012", "P2", "refine", "The electric-fridge count", objects=["F02_2A_FRIDGE_01, F03_3D_FRIDGE_01, F04_4D_FRIDGE_01 (FridgeMonitor -> FridgeIcebox)"], purpose="Bible VIII.5.a four electric flats (1A, 3A, 5B, 6C)", sources=["game/data/orison_v2/household_fridges.json"], acceptance="Seven monitor-tops become four"),
          change("BW-013", "P2", "add", "The signal outlet beside every switch", objects=["one brass flush plate per room beside each SwitchPlate (133 plates)"], construction="Static part in the light_switch family, 70 x 115 mm, cloth lead stub where a device connects", signal=SIGNAL_YES, purpose="Bible VIII.3: a signal outlet beside the power socket in every room including the bathrooms", sources=["art/blender/light_switch.md"], acceptance="Detail view at any switch"),
          change("BW-015", "P2", "refine", "Exposed white-brick texture patches on interior piers", objects=["pier faces showing a bright white brick texture: 5B main room pier, the 2C door jamb and the F02 landing/west-hall junction, the lobby wall patch (reviews); F04 review: exposed red brick with a white stone bracket inside the F04 landing and public core (DT1, OV) and at the west hall/landing junction (TH)"], construction="The exterior masonry or a retained-slab join is showing through where a plaster finish quad is missing; emit the plaster finish on those faces (the WK-1 side-aware emission) or give the exposed brick its interior common-brick map",
                 purpose="A white brick patch in a plastered room reads as an unfinished model, not as stratigraphy", sources=["art/blender/exterior_masonry.md", "art/blender/building_surface_finish.md"], acceptance="No white brick in any apartment or lobby overview"),
          change("BW-016", "P2", "refine", "Apartment door leaves blow out under the lamp", objects=["fitted door leaves (orison_v2_fitted_door.gd family) read as flat bright white slabs at night in 6A, 5B and elsewhere; the transom over 4A's door (F04 east hall) blows to a white rectangle; door frames in the F05 east hall and service crossing blow bright; the 5A main-room doorway panel (DT1); 4B private-hall leaves read as flat khaki insets"], construction="Lower the leaf finish albedo toward the authored cream enamel and give it the panel relief and knob set of the door_fabric family; check the lamp's specular on the enamel",
                 purpose="A door that reads as a white light in a dark room breaks Accord 15 and the period cream-paint look", sources=["art/blender/door_knob_set.md", "design/V2_LAMP_SURFACE_BALANCE_2026-10-05.md"], acceptance="Night overviews show cream panelled leaves"),
          change("BW-017", "P1", "refine", "Public hall practicals: west and east halls and landings have no fixture record", objects=["F02-F06 WEST_HALL, EAST_HALL, LANDING and PUBLIC_CORE spaces: fixed_lighting.json carries F02/F03/F04_SOUTHWEST_HALL_LT and no other public-hall fixture; room_lighting.json has no hall entries"],
                 construction="Establish where the halls' present light comes from (the F04 west hall reads lit with no fixture in frame; the F04 east hall, F04 landing, F05 west hall and both F05 service halls read dark or lamp-only); add a flush-dome or opal pendant pair per hall and one per landing from the fixed_lighting family at the hall centreline, 2.9 m, switched with the floor; the desktop light budget is off (light_rig.gd, 2026-08-08) so no victim is needed on desktop, and the mobile ranking already prefers circulation fixtures",
                 lighting="Warm 2700 K practical per fixture; the 4B lettered transom and the unit doors must read from the landing without the hand lamp", purpose="Review: unit doors 5A/5B render nearly black and the 4A transom is the only lit thing in its hall; a 1928 corridor was never unlit at 20:00", sources=["game/data/orison_v2/fixed_lighting.json", "game/scripts/building/light_rig.gd", "art/blender/fixed_lighting.md"], preserve="Existing SOUTHWEST_HALL_LT fixtures, the lift landing plates and the door-glow authority", acceptance="West and east hall overviews on every floor show a practical and legible door leaves with the hand lamp off"),
          change("BW-018", "P1", "refine", "Water closets: the low cistern must read", objects=["5C_wc (completion source) and its six copies 1A_wc, 2C_wc, 3D_wc, 4C_wc, 4D_wc, F01_STAFF_WC; 2B_wc and its copy 1D_wc; 5A_wc and 5B_wc"],
                 construction="bathroom_details.md describes bath_water_closet.blend with a hollow wash-down bowl, porcelain foot, low cistern, wooden seat, supply shutoff and a separate CisternHandle pivot, with the toilet model references authored in domestic_furniture_source.json and projected by build_v2_authoring_projection.py; the captures show an undersized white block behind the seat (5B, 5C), a flat grey strip and a block (5A), nothing at all (4A, 4C, 4D) and a magenta cistern face (3D). Confirm every WC record references the rebuilt model, that the cistern mesh is not culled or scaled, and that the material binds",
                 purpose="Accord 11: the flush must terminate; a bowl with no cistern cannot work and every reviewer named it first", sources=["art/blender/bathroom_details.md", "art/data/orison_v2/completion_interiors_source.json", "tools/build_v2_authoring_projection.py"], preserve="The flush owner: sound, lever travel, refill time and repeat-use refusal; the paper spindle on the cistern side", acceptance="Every bath DT station on the WC shows bowl, low cistern and handle; 4B's tanked WC is the reference"),
          change("BW-019", "P2", "refine", "Completion casework: mouldings and hardware on wardrobes, nightstands and kitchen cupboards", objects=["Wardrobe05 (5A_w0), Wardrobe06 (5B_aw), Wardrobe07/08 (5C_w0/w1), the 4A, 4C and 4D wardrobes; Nightstand01 everywhere; Cupboard06/Cupboard08 wall cupboards (4A_k_wall_cupboard, 5A_k_wall_cupboard and kin); Counter05 base cabinets with speckled stone tops (16 instances)"],
                 construction="Give the wardrobes a cornice, stile-and-rail door panels, escutcheons and turned knobs (household_wardrobes.md); nightstands a drawer pull and a top lip; wall cupboards painted panelled doors with wooden knobs; base cabinets a scrubbed deal or zinc top in place of the speckled stone and a plinth", materials="painted deal, oak, zinc, brass", wear="rubbed paint at the knobs, a ring on the zinc",
                 purpose="Review: every bedroom and kitchen on F04 and F05 names the same plain primitives; flat white handle-less boxes with stone tops read 1950, and the completion homes have no other casework", sources=["art/blender/household_wardrobes.md", "art/blender/domestic_storage.md", "game/data/orison_v2/domestic_storage.json", "game/data/orison_v2/household_wardrobes.json"], preserve="Wardrobe leaf motions and the fitted-storage supports", acceptance="Bedroom and kitchen overviews show panelled casework with hardware"),
          change("BW-020", "P3", "refine", "Terrazzo aggregate scale", objects=["terrazzo, terrazzo_b and terrazzo_dark maps (floor_coverage_pass.gd: cell-snapped hex, 3.0 m cells) on the public hall floors and in the druggist and luncheonette"],
                 construction="Re-author the aggregate at 5 to 15 mm chips with brass divider strips on a 1.2 m bay (the 1912 Queens hall standard) and keep the hex lattice and divider logic", purpose="Review (F04, city): chips the size of a hand turn the floor into crazy paving", sources=["game/scripts/building/floor_coverage_pass.gd", "art/blender/concrete_trowelled.md (the related mineral finishes)"], acceptance="Hall and shop floor detail stations read as terrazzo at 1 m"),
          change("BW-021", "P3", "refine", "Kitchen floors: linoleum over the oak", objects=["4A, 4B, 4C, 5A, 5C kitchens where the oak strip runs in from the hall (review)"],
                 construction="Lay a battleship-linoleum sheet variant within the kitchen footprint, worn through to the burlap at the sink and range stances; the owner finish profile decides the colour", materials="linoleum, worn", purpose="Review: oak strip in a wet room reads wrong for a tenement kitchen of 1912; linoleum over boards is the period norm", sources=["game/data/orison_v2/owner_finish_profiles.json", "art/blender/building_surface_finish.md"], acceptance="Kitchen overviews on F04 and F05"),
          change("BW-022", "P2", "refine", "Unit numerals on the apartment doors", objects=["4C and 4D entry doors (F04 public core, southwest hall) carry no numeral; 4B carries a lettered transom; verify every other unit door"],
                 construction="One enamel numeral plate per unit door from the wayfinding plate family, Label3D lettering, centred on the top rail; no numerals in textures", purpose="Review: from the hall nothing says which flat is which; the player's 4B is the only door the hall names", sources=["art/blender/wayfinding_plate.md", "art/blender/door_knob_set.md"], acceptance="Hall threshold stations read the unit numeral"),
          change("BW-023", "P1", "refine", "Arcade rear rooms: eleven identical bare boxes", objects=["site_rear cells of all eleven arcade shops: brick end wall, flat grey floor, one empty shelf unit and two brown cubes in every one; only the funeral parlour's rear carries trade furniture; no rear room has a practical"],
                 construction="Verify that the trade receiving sets instantiate in the rear cells (laundry_receiving, news_receiving, pawn_receiving, photo_receiving, radio_receiving, diner_receiving, bar_receiving, bodega receiving); if they do and sit elsewhere, re-anchor them; if they are missing, author the receiving set per trade and a cage bulb per rear room from the fixed_lighting family; retire the two shared brown cubes", purpose="Review (city): nothing in any rear room says which shop it belongs to", sources=["game/data/orison_v2/*_receiving.json", "game/data/floor_01_cell_registry.json", "art/blender/fixed_lighting.md"], preserve="Rear doors, routes and the cell registry's refusals", acceptance="Each site_rear floor station identifies the trade"),
          change("BW-014", "P3", "refine", "Wainscot joinery and peepholes", objects=["public-hall wainscot reads as a continuous veneer sheet (F03 review); apartment doors have glowing peepholes (F05_DOOR_05 renders its peephole as a flat white disc, F05_DOOR_06 and the 5A door as a dot; 4D vestibule and 4B hall doors likewise)"], construction="Add stile-and-rail relief to the millwork profile; remove the peephole emissive (a 1928 door has a chain and a transom, no glowing lens)", sources=["art/blender/millwork_profile.md", "art/blender/door_knob_set.md"], purpose="Accord 14 construction evidence; period", acceptance="Hall detail views")],
         canon=[C_LIVED, C_BIBLE_VIII4, C_BIBLE_VIII5A, C_ACCORDS, C_ENTROPY],
         implementation={"sources": ["art/blender/v2_batch_workflow.md (batch by family)", "tools/plan_v2_fabrication.py (changed-input planning)", "game/data/orison_v2/*.json installed data"],
                         "dependencies": "Families first (BW-003, BW-004, BW-005, BW-008, BW-018, BW-019), then data (BW-001, BW-002, BW-011, BW-012, BW-017, BW-023), then room passes", "preserved": "Every existing interaction owner, route, save owner and the 17 protected paths; no hand-edited glTF or JSON",
                         "acceptance": "A repeat of this dossier's capture scene at the new head with the same stations; the per-room acceptance views listed on each page"},
         coverage="n/a (cross-cutting)"),
]
