"""ROOF: the two bulkhead cores and seven deck zones."""
from _common import *

GR = "ROOF"
INTRO_ROOF = ("<b>The roof.</b> Eight storeys up (Bible III: B1, F01-F06, ROOF), reached by both stairs through bulkheads with doors that open and close normally. The 1928 reopening put four "
              "ILG-pattern electric ventilators here on four sheet-metal risers for the twenty-three windowless bathrooms (Bible VIII.5.i); the house tank stands on its timber legs southwest of the "
              "public bulkhead with the exposed ballcock the player services; the masonry chimney stands beside the east parapet; the guarded lift drive sits inside the public bulkhead. The "
              "prospectus drew the roof as a garden with people in it (Bible VIII.3); Malcolm keeps beds and communal planters and hands out rooted cuttings on Saturdays; Juno records up here "
              "Mon/Wed, Sacha photographs Tue/Thu, Iris sketches the light court at 13:00, Mae has her one unhurried hour on Sundays (schedules). The owner JSON lists the roof field, drainage and "
              "ventilator housings (A06) and the neighbouring tanks and aerials (A07) as pending; the membrane, coping, flashings, drainage, service weathering, chimney, tank, ventilators and "
              "lift drive each have their own Blender records. The smoke capture at 20:00 shows a dark deck under a star field with the tank, bulkheads, parapets and neighbouring masses; the "
              "player's lamp is the only light. <b>What the roof lacks</b> is use: no beds, no planters, no line, no watering can, no pigeon, no tar patch; the garden the prospectus promised is not here.")

AREAS = [
    core("ROOF_PUBLIC_CORE", GR, "Public roof bulkhead: lift drive and the court skylight", "The public stair's top bulkhead with the guarded lift drive, the pitched light-court skylight beside it and the door onto the west deck",
         "The bulkhead holds the Blender lift drive behind its guard and the skylight's pitched panes; it is the one interior on the roof. The skylight is the eye's top (Bible III: it sees from lobby runner to skylight).",
         extra_changes=[change("ROOF_PUBLIC_CORE-003", "P2", "add", "Roof-use evidence inside the bulkhead", objects=["new: a coil of washing line, a watering can and a trug on the floor beside the door (desktop_stock); a chalk tally on the wall by the door"], placement="Against the bulkhead wall opposite the lift guard, outside the door swing", purpose="Schedules: Malcolm comes through this door at 07:00 and 17:00", preserve="Lift drive guard and refusal, door swing", acceptance="Threshold view from the stair")],
         evidence={"limits": "Lift machinery and skylight are review-only owners; nothing here changes them."}),
    core("ROOF_SERVICE_CORE", GR, "Service roof bulkhead", "The service stair's top bulkhead with its door onto the middle deck", "The service bulkhead has the sloped weather cover, open gutter outlet and external rainleader of roof_service_weathering.md; coal dust on the treads from chimney work.",
         extra_changes=[change("ROOF_SERVICE_CORE-003", "P3", "add", "Chimney-sweep evidence", objects=["new: a soot sack and a set of rods against the wall inside the door (desktop_stock)"], purpose="The 1912 flue is swept; the tools live by the nearest door", acceptance="Threshold view")]),
    roof_deck("ROOF_DECK_WEST", GR, "West deck: the tank and three ventilators", "The largest deck (13.45 x 24 m) with the house tank, three ventilator curbs (A, B, C), the west parapet and both passages to the north and south decks",
              "The tank on its legs is the deck's landmark and the ballcock activity lives at its exposed valve. The three ventilator curbs with their motors sit along the deck; the ILG housings are pending in A06. Malcolm's beds belong here along the west parapet where the morning light comes over it.",
              extra_changes=[change("ROOF_DECK_WEST-002", "P1", "add", "Malcolm's beds and communal planters", objects=["new: 3 timber raised beds 2.4 x 0.9 x 0.4 m along the west parapet; 4 communal planters (half-barrels) by the north passage; a compost bin by the tank legs"],
                                    placement="Beds 0.6 m off the parapet face, clear of the fan curbs and drainage falls; planters at the passage mouths leaving 1.2 m; compost bin 0.8 m from the tank's southwest leg", construction="New static native family (roof_beds) with soil fill, staked tomatoes gone over in November, geraniums in the planters; no collision beyond the box hulls",
                                    materials="creosoted timber, soil, galvanised staples, half-barrels", wear="watering stains on the membrane downhill of each bed; a path worn between bed and tank", lighting="none added", purpose="Schedules: beds, staking, planters, the compost bin fed with everyone's greens; Bible VIII.3 the roof garden promise; web II.8 the cuttings' descendants",
                                    sources=["game/data/resident_schedules.json (malcolm_reed roof blocks)", "art/blender/roof_membrane.md", "art/blender/roof_drainage.md"], preserve="Falling field, outlets, tank valve stance, ventilator curbs and guards", acceptance="Overview from the bulkhead door reads a garden; roof route test unchanged"),
                             change("ROOF_DECK_WEST-003", "P2", "add", "Washing line between the tank leg and a parapet post", objects=["new: line, two props, four pegs, one sheet (cloth family)"], placement="From the tank's northeast leg to a post on the west parapet, 1.9 m high, clear of the route", purpose="A 1928 roof is a drying yard; the laundry airer downstairs is for winter", acceptance="Overview")]),
    roof_deck("ROOF_DECK_SOUTH", GR, "South deck: the street side", "17.85 x 8.5 m along the south parapet facing the street, with ventilator curb D and passages west, middle and southeast",
              "The street-facing parapet is where the view of the storm ends and the T-ENDS railway would be heard; Sacha's night photography station is at this coping. Fan D stands here.",
              extra_changes=[change("ROOF_DECK_SOUTH-002", "P2", "add", "Sacha's tripod mark and Juno's mic stand", objects=["new: three tripod-foot scuffs (decal) at the coping centre; a folded mic stand chained to the parapet post (asm_micstand, RESIST-REFUSE)"], placement="Coping centre and the southwest post", purpose="Schedules: roof divided, Juno Mon/Wed and Sacha Tue/Thu", acceptance="Detail view at the coping")]),
    roof_deck("ROOF_DECK_NORTH", GR, "North deck: the alley side", "11.7 x 7.8 m along the north parapet over the service alley, with passages west, middle and northeast",
              "Over the alley: the rear service door's weather below, the north neighbours' backs beyond. Pigeons roost on this coping (C2, gated); the guano is positional and sparse.",
              extra_changes=[change("ROOF_DECK_NORTH-002", "P3", "add", "Roost evidence under C2 when ruled", objects=["new: positional guano decals under the north coping's three posts; no birds until C2"], purpose="Commensals C2 gated; the evidence layer can be authored first", sources=["design/ORISON_COMMENSALS_BRIEF.md"], acceptance="Detail view of the coping")]),
    roof_deck("ROOF_DECK_MIDDLE", GR, "Middle deck between the bulkheads", "4.1 x 7.7 m between the public and service bulkheads with the service door", "The connecting deck: a tar patch, the rainleader's outlet, a bucket under the service bulkhead's gutter.",
              extra_changes=[change("ROOF_DECK_MIDDLE-002", "P3", "add", "Bucket under the gutter outlet", objects=["new: galvanised bucket (desktop_stock) under the service bulkhead's open gutter outlet"], purpose="Accord 11: every outlet terminates somewhere; the super's bucket", acceptance="Detail view")]),
    roof_deck("ROOF_DECK_EAST", GR, "East deck: the chimney walk", "2.45 x 11.35 m along the east side with passages to the southeast and northeast decks", "The narrow walk past the masonry chimney beside the east parapet (Bible VIII.5.c: the flue is 1912 and still working); soot on the coping downwind.",
              extra_changes=[change("ROOF_DECK_EAST-002", "P3", "add", "Soot on the lee coping", objects=["soot decal on the coping east of the chimney"], purpose="Consequence within two metres of the flue", acceptance="Detail view")]),
    roof_deck("ROOF_DECK_SOUTHEAST", GR, "Southeast deck corner", "6.15 x 4.15 m at the east parapet with passages south and east", "The corner where the chimney and the south parapet meet; the best view of the arcade's glass roof (destination compass: see the Arcade from above).",
              extra_changes=[change("ROOF_DECK_SOUTHEAST-002", "P3", "add", "A folding stool for the view", objects=["new: folding stool (seating family) by the corner post"], purpose="Mae's unhurried hour on Sundays; Iris sketching", acceptance="Overview")]),
    roof_deck("ROOF_DECK_NORTHEAST", GR, "Northeast deck pocket", "3.7 x 1.45 m pocket with passages east and north", "A pocket behind the service bulkhead where nothing happens: the one place on the roof the mop never reaches; a dead pigeon's feathers (C2) or nothing.",
              extra_changes=[change("ROOF_DECK_NORTHEAST-002", "P3", "keep", "Keep it empty", purpose="Intentional emptiness; the roof needs one corner nobody uses", acceptance="Overview unchanged")]),
]
AREAS[0]["group_intro"] = INTRO_ROOF
