"""F02: circulation, 2A Mina Vale, 2B Lena Ortiz, 2C Juno Kells, 2D sealed."""
from _common import *

GC = "F02 / circulation"
G2A = "F02 / 2A Mina Vale (Case 01)"
G2B = "F02 / 2B Lena Ortiz"
G2C = "F02 / 2C Juno Kells (case)"
G2D = "F02 / 2D sealed"

INTRO_2A = ("<b>Mina Vale, 2A.</b> Caption editor; twenty-two years a certified court reporter until four blank seconds in the record of the State ended that life (Bible IV). "
            "Her wound: everything must be annotated or it does not count; the rule she must learn is that silence does not require annotation. 2A is the complete, voiced Case 01 and the "
            "bar every other case is measured against: the failed Vantry point that chirps, the caption desk, the calibrator, the letter, the refrigerator caption residue after the first dream. "
            "Canon dressing: labelled everything, cable discipline, duplicate correction tools, measured portions, the conspicuously unlabelled box (hero object), slate tailor-made clothes and a "
            "stenographer's pencil behind the ear. Decor profile: a working wall, captions visible from the desk, the unsaid allowed one confrontational axis. Teresa is her mother one floor down and "
            "their hours never overlap (web II.4); Cal's reel two floors up holds her four seconds (web II.1). <i>Proposed backstory:</i> the unlabelled box holds the stenotype paper of one "
            "afternoon in court; the caption wall is pinned so that one card is blank. <b>Build state:</b> the richest apartment in data (desk, pinboard, lamp, papers, headphones, deck, projector, "
            "three wire shelves, sofa, radio, bookshelf, case objects) and the one whose gameplay must be preserved exactly. The main room reads under-dressed at overview distance and the "
            "wire shelving reads later than 1927; the desk is in the bedroom, which is right for a woman who works nights alone.")

INTRO_2B = ("<b>Lena Ortiz, 2B.</b> Seamstress, burgundy knit, shears; she mends everyone but her own hem (Bible IV); visible repairs can hold. Canon: clients welcome at the door, "
            "a cutting table, a repair queue, fabric stored vertically, the mended upholstery armchair as hero object, the biggest pots in the building because she cooks for others, "
            "cleanliness 0.7, maintenance 0.9; one hem still pinned. Her arrival layer is 1911 and the Triangle fire (web I); she has opinions about locked doors she has never spoken aloud; "
            "she mends Cam's jersey strap without being asked (web II.5); Saturday she sits early at the Harukiya and mends the banquette's split vinyl. The sewing machine treadle is an "
            "OPERATE owner in the matrix. <i>Proposed backstory:</i> three garments in the repair queue are from this building, tagged with floor numbers instead of names. "
            "<b>Build state:</b> B-type plan (vestibule, main with openings, kitchen, private hall, bed, bath), the fabric worktable, pattern board, patterns, notions, two fabric shelves in the hall, "
            "a radio. The furniture is hers; the room needs the queue, the machine and the chair.")

INTRO_2C = ("<b>Juno Kells, 2C.</b> Audio artist, asymmetric crop, recorder (a Rule-of-Signal device, licensed early); her work was taken and the feedback became load-bearing; "
            "connection requires an open channel (Bible IV.1, a case). Canon: a working musician's entry, the second bedroom converted to a recording room with blankets fixed to the walls and a "
            "stolen session archive (hero object), cable management as the one meticulous thing in a room of chaos, takeout and coffee, the range used as a shelf for tape boxes, cleanliness 0.38, "
            "nocturnal; she samples others without asking and take 18 of Rhea's session lives in her archive (web II.7); she roof-records Mon/Wed and visits Cal to trade tapes on Saturdays. "
            "<i>Proposed backstory:</i> one reel box is labelled only with a 1927 date. <b>Build state:</b> a completion-interior C-type home with two made beds, two nightstands, a dining set, a "
            "colour board, a bookshelf and a wireless table, and a studio closet holding two wardrobes. No recording room exists; the second bedroom is a second bedroom.")

AREAS = [
    # ------------------------------------------------------------------ circulation
    core("F02_LANDING", GC, "F02 passenger lift landing", "At the top of the primary stair's first flight; opening west to the west hall", "The landing is the floor-and-unit decision for 2A and 2D; the lift's brass plate and dial are here. The punchlist asks each half-landing for its own piece; this landing's should be the first photograph the building owns (1928).", level="F02"),
    public_hall("F02_WEST_HALL", GC, "F02 west hall: Mina's approach", "Between the landing and the southwest hall; 2A's entry door (F02_DOOR_02)", "the player on the first shift, Mina, Teresa at 22:00 never (their hours miss)",
                "This is the first apartment approach the player walks on the first shift: Mina's door with its transom and a mat squared to the millimetre; the only hall in the building with a milk bottle rinsed and inverted. Nothing else should distract from the door.", level="F02"),
    public_hall("F02_SOUTHWEST_HALL", GC, "F02 southwest hall: the sealed door of 2D", "Dead-end public hall south of the west hall; 2D's entry (F02_D_ENTRY_DOOR) is locked", "nobody; the player on the service round",
                "A hall that goes nowhere, to a door that does not open. It has its own flush dome and switch and is the quietest public space on the floor. The sealed threshold deserves the building's silence treatment (see F02_D_RESTRICTED): a paper notice, dust on the mat, no milk.", level="F02"),
    core("F02_PUBLIC_CORE", GC, "F02 public core: stair and lift", "The dog-leg stair and passenger lift at the centre; 2C's entry (F02_C_ENTRY_DOOR) opens here", "Juno's door opens directly onto the core, so her comings and goings at 02:00 are heard on the stair; the half-landing north of here is where Teresa and Mina's floors touch (web II.4).", level="F02"),
    public_hall("F02_EAST_HALL", GC, "F02 east hall: the 1.2 m approach to 2B", "From the core east to the service crossing; 2B's entry is beyond the crossing", "Lena's clients, Cam on Tuesdays and Sundays",
                "A narrow public hall that carries Lena's trade: a client waiting, a parcel of finished work left against the wall for collection (schedule: delivering door to door, lingering at each threshold). The review anchor F02_B_EXIT_REVIEW is here.", level="F02"),
    service_hall("F02_SERVICE_CROSSING", GC, "F02 service crossing", "The 1.2 m square where the public east hall crosses the service spine; 2B's entry door (F02_B_ENTRY_DOOR) opens here",
                 "The crossing is a controlled public threshold onto the service spine: a painted line on the floor, a notice frame, the dumbwaiter's call bell within reach. Lena's door opens into it, which is why her clients use the service hall as a waiting room.", level="F02"),
    service_hall("F02_SERVICE_HALL", GC, "F02 service hall (north)", "The north maintenance continuity from the crossing to the service core", "The north run passes the kitchens' service side; riser tags and the super's chalk belong here; nothing on the route.", level="F02"),
    service_hall("F02_SERVICE_HALL_SOUTH", GC, "F02 service hall (south)", "The south maintenance continuity from the crossing", "A short dead-end run with a cage bulb; the mop-shadow corner lives at its end.", level="F02"),
    core("F02_SERVICE_CORE", GC, "F02 service core", "Service lift and stair west of the service hall", "The service stair is the super's stair: the rail is dull where the public rail is polished; chalk tallies on the wall by the floor plate.", level="F02"),

    # ------------------------------------------------------------------ 2A
    vestibule("F02_A_VESTIBULE", "2A", G2A, "labeled_everything",
              "A 1.95 x 2.7 m vestibule opening straight into the main room. Mina's landing set is a key board with every hook labelled and a numbered coat strip; the labels are blank card rectangles at this scale (no lettering), but the regularity reads from the door.",
              extra_changes=[change("F02_A_VESTIBULE-003", "P2", "add", "The out-tray of filed receipts", placement="On the vestibule shelf, square to its edge", construction="One papers-family stack with a paper-clip stroke", purpose="Schedules: receipt kept and filed, 13:30 sharp", acceptance="Visible in the threshold view")],
              group_intro=INTRO_2A),
    area("F02_A_MAIN", G2A, "ORISON", "Mina's living room: the working wall", "8.1 x 6.95 m, two west windows, openings to the vestibule and kitchen, door to the private hall", "Mina Vale; the player for the whole of Case 01",
         ("The largest living room in the building and the one the player studies longest. Today it holds a sofa, three wire shelving units, a round table and two chairs, a coffee table with the "
          "deck, a wireless table and radio, a projector on a stand, the repaired bookshelf and the radiator; Mina stands in it at 20:00. The walls are bare. The decor profile asks for a working "
          "wall: captions visible from the desk, images arranged so that one confrontational axis runs from the desk to the thing she never annotated. The desk is in the bedroom (right for her), "
          "so this room is the public face of her discipline: the shelves hold labelled boxes in rows with their labels facing out, every cable runs to a point and is tied, the sofa has one cushion "
          "squared and one with a dent, the coffee table carries the deck and a labelled jar of pencils; the unlabelled box sits in plain sight on the lowest shelf with its blank face forward. "
          "The player infers a woman who has annotated her whole life except one object, and that the object is the point."),
         [change("F02_A_MAIN-001", "P1", "refine", "Replace the wire shelving with labelled closed storage", objects=["2A_shelf0, 2A_shelf1, 2A_shelf2 (Shelf04)"],
                 placement="Same three anchors against the west pier wall; same footprint", dimensions="as installed (about 0.9 x 0.4 m, 1.8 m high)", construction="Swap the Shelf04 variant to a closed oak shelf unit variant from domestic_storage with box rows (desktop_stock box family) and label rectangles facing out",
                 materials="oak, grey card boxes, white label rectangles", wear="finger-grime at the box pulls only on the top two rows (the ones she uses nightly)", purpose="Wire shelving reads post-1950; a court reporter's archive is boxed and labelled (life profile: labeled_everything; decor profile: do not cover storage she uses nightly)",
                 sources=["art/blender/domestic_storage.md", "art/blender/desktop_stock.md"], preserve="The three anchor positions and the route along the shelves", acceptance="Overview shows three matching labelled units; no wire"),
          change("F02_A_MAIN-002", "P1", "add", "The caption wall", objects=["new: 2A_caption_wall (pinboard-family board 1.2 x 0.9 m) with card rectangles and strings; one blank card"],
                 placement="On the wall between the two west windows at 1.4 m, on the axis from the bedroom desk through the hall door to the window pier", construction="One pinboard owner (FurnitureInteractionPass, single tack target) with 24 card rectangles in rows and one empty card; red thread decals linking cards; no lettering",
                 materials="cork, index card, red thread", wear="a pale rectangle where a card was moved", purpose="Decor profile: captions visible from the desk, one confrontational axis; proposed backstory: the one blank card is the four seconds",
                 sources=["design/resident_decor_profiles.json", "design/PROP_SET_INTERACTION_MATRIX.md pinboard row"], preserve="Case 01 owners (F02_A_MONITOR_01, F02_A_CAPTION_WORK_ZONE, Vantry point, calibrator, letter) untouched; WallArtLaw hook", acceptance="Detail view from the hall door shows the board centred between the windows"),
          change("F02_A_MAIN-003", "P1", "refine", "The unlabelled box in plain sight", objects=["existing hero object conspicuously_unlabeled_box (life profile) if instantiated; else new desktop_stock box"],
                 placement="Lowest shelf of 2A_shelf1, front edge, blank face forward, 10 mm proud of the row", construction="Same box family as the labelled rows with no label rectangle; INSPECT card per the matrix; no second state owner",
                 purpose="Life profile hero object and Case 01 dialogue anchor", sources=["game/data/apartment_life_profiles.json", "design/lived_in_pass.md (hero object triple duty)"], preserve="MinaCaseGameplay dialogue anchor if already bound", acceptance="Detail view of the shelf row reads the one blank box"),
          change("F02_A_MAIN-004", "P2", "add", "Cable discipline", objects=["new: cloth flex runs from the radio, projector and deck to the brass signal outlet and a floor outlet, tied at 0.3 m intervals"],
                 placement="Along the skirting from each device to the plate beside F02_A_MAIN_SWITCH", construction="Static cable family (task_lamp_supply materials) with cord clips", materials="cloth-braided flex (good flat: coloured silk flex, Bible VIII.4)", signal=SIGNAL_YES,
                 purpose="Life profile surface set cable_discipline; wealth reads through wiring", sources=["game/data/orison_v2/task_lamp_supply.json"], acceptance="Detail view at the radio shows the flex to the plate"),
          change("F02_A_MAIN-005", "P2", "add", "Rug and the sofa's two cushions", objects=["new: 2A_rug (floor cloth family, 2.4 x 1.6 m)", "2A_sofa cushions"], placement="Rug under the coffee table square to the sofa; nothing under the chairs",
                 materials="a worn Turkey-pattern rug with the pattern bleached toward the window", wear="one sofa cushion dented, one squared", purpose="Appliance Bible III inverted: the parlour is 1970 (meaning modern for 1928), the kitchen 1890; one calm sightline (decor principle)", acceptance="Overview from the vestibule"),
          change("F02_A_MAIN-006", "P3", "keep", "Keep the projector and deck where they are", objects=["2A_tv (ProjectorProp)", "2A_deck"], purpose="F14 rules the projector in case flats; the found-wall throw must not be obstructed by the caption wall (the board is on the window wall, the throw faces the pier)", acceptance="Projector image lands on bare plaster with the board out of its cone")],
         canon=[C_BIBLE_IV, C_LIFE, C_DECOR, "game/docs/core_loop.md (Case 01 anchors)", C_MATRIX], proposed_backstory=["The blank card on the caption wall is the four seconds.", "The unlabelled box holds the stenotype paper of one afternoon in court."],
         implementation=apt_impl(extra_sources=["game/data/orison_v2/case_one_placement.json", "game/scripts/game/mina_case_gameplay.gd (preserve)"], preserved="Every Case 01 owner and anchor (monitor, caption work zone objects, Vantry point F02_A_MAIN_VANTRY_POINT, calibrator, letter, refrigerator caption marker), Mina's routine paths and the door passages, projector throw, radiator valve, bookshelf panel")),
    kitchen("F02_A_KITCHEN", "2A", G2A, "measured_portions", "Mina's kitchen carries the Case 01 refrigerator caption residue after the first wake; the fridge is a monitor-top in data where the Bible allows four electric flats (1A, 3A, 5B, 6C). Converting it to an icebox keeps the caption marker (it binds to the refrigerator marker, not the model).",
            fridge="monitor", extra_changes=[change("F02_A_KITCHEN-003", "P2", "refine", "Monitor-top to icebox", objects=["F02_2A_FRIDGE_01 (FridgeMonitor -> FridgeIcebox)"], placement="Same anchor and leaf hand", construction="Swap the household_fridges variant; keep the FridgeProp owner and the mina_factual_refrigerator_caption marker/socket",
                                                   purpose="Bible VIII.5.a (four electric flats) prevails over data; the ice card then tells her exactness (a number she never changes)", sources=["game/data/orison_v2/household_fridges.json", "game/scripts/game/mina_caption_manifestation.gd (residue socket)"],
                                                   preserve="Refrigerator caption residue socket, fridge leaf and ice door", acceptance="OrisonV2WakeReconstructionTest and the household fridge module pass with the icebox variant")]),
    private_hall("F02_A_PRIVATE_HALL", "2A", G2A, "a 1.3 m hall: nothing on the floor; a labelled key hook for the bath and bed doors, which is the only joke she makes."),
    bath("F02_A_BATH", "2A", G2A, "single_adult_exact", "The smoke capture shows the standard set: pedestal basin, WC, curtain, cabinet, register. For Mina add only exactness: the toothbrush parallel to the basin edge, the towel's fold aligned to the rail end.",
         captions={"F02_A_BATH_OV": "Standard V2 bathroom kit as installed.", "F02_A_BATH_DT1": "Painted gravity register and flush dome; the register is Bible VIII.5.i's stack A."}),
    area("F02_A_BED", G2A, "ORISON", "Mina's bedroom: the desk where the night happens", "5.4 x 5.45 m, two windows, door from the private hall", "Mina Vale (20:00 at the desk: corrections of corrections)",
         ("The desk, its chair, the pinboard, the green office lamp, the papers, the mug and the headphones are all here, with the bed, nightstand and wardrobe. This is the right arrangement: she "
          "works at night in the room where she sleeps, and the bed is made because she has not been in it. The room should read as two rooms sharing a wall: the desk side exact, lit by the lamp, "
          "the pinboard dense with cards; the bed side dark, the slate suit on the wardrobe door for the morning that will start at 13:30. The player infers a night worker and the discipline that "
          "replaced a courtroom."),
         [change("F02_A_BED-001", "P2", "refine", "Desk surface: duplicate correction tools", objects=["2A_papers, 2A_mug, 2A_phones (existing)", "new: two identical pencil jars, two identical erasers, a correction-tape reel, a stenographer's pad (desktop_stock)"],
                 placement="On 2A_desk within the lamp's pool, the duplicates side by side", construction="desktop_stock pieces seated by support id", materials="glass jars, cedar pencils, a red-and-black pad cover", wear="the desk's front edge polished by forearms", purpose="Life profile surface set duplicate_tools; story panel: correction tape", acceptance="Detail view of the desk under the lamp"),
          change("F02_A_BED-002", "P2", "refine", "Pinboard density", objects=["2A_pinboard (DomesticObject00)"], placement="As installed above the desk", construction="Increase the card count on the pinboard variant to a full grid with two overlapping cards; the single tack owner stays",
                 purpose="Decor profile working wall continues into the bedroom", acceptance="Detail view reads a full board"),
          change("F02_A_BED-003", "P2", "add", "The suit on the wardrobe door and the bed made for later", objects=["2A_w0_wardrobe (garment set: slate tailor-made, grey cloche on the shelf)", "2A_bed0 counterpane squared"],
                 construction="Wardrobe garment silhouettes slate and white; a hanger on the outer leaf with the jacket", materials="worsted, cotton shirting", purpose="Wardrobe bible street state for a woman who dresses as though still due in court", acceptance="Reverse view shows the hung jacket and the squared bed")],
         canon=[C_LIFE, C_WARD, C_SCHED], implementation=apt_impl(preserved="Desk zone and the papers/pinboard FurnitureInteractionPass owners; Case 01 objects if any are seated here; wardrobe leaves; bedside route")),

    # ------------------------------------------------------------------ 2B
    vestibule("F02_B_VESTIBULE", "2B", G2B, "clients_welcome", "2B's entry opens onto the service crossing, so the vestibule is the client's waiting room: a bentwood chair, a mirror, a paper pattern taped to the back of the door, the tape measure on the hook. The threshold anchor F02_B_THRESHOLD is here.",
              extra_changes=[change("F02_B_VESTIBULE-003", "P2", "add", "Client's chair and a parcel of finished work", objects=["new: 2B_client_chair (ChairOak), 2B_parcel (desktop_stock string-tied parcel)"], placement="Chair against the wall beside the opening; parcel on its seat",
                                    purpose="Schedules: delivering door to door; entry set clients_welcome", preserve="Route to the main opening", acceptance="Threshold view from the crossing")], group_intro=INTRO_2B),
    area("F02_B_MAIN", G2B, "ORISON", "Lena's workroom: the cutting table and the queue", "4.15 x 4.5 m, one window, openings to the vestibule and the private hall", "Lena Ortiz; her clients; Cam on Sunday evenings",
         ("The main room has the fabric worktable, the pattern board, patterns and notions, a dining table and chairs, the radio and the radiator. It should become a working seamstress's front room in "
          "warm dialogue with repaired things (decor profile): the treadle sewing machine under the window where the light is, the cutting table with a tape, chalk and shears, the repair queue "
          "on a rail with paper tags, the mended upholstery armchair (hero object) with its visible contrasting patch, fabric stored vertically on the hall shelves, and the biggest pots in the "
          "building visible through the kitchen door. The player infers a woman who repairs the whole block and has not got to her own hem."),
         [change("F02_B_MAIN-001", "P1", "add", "Treadle sewing machine under the window", objects=["new: 2B_sewing_machine (new native family: cast-iron treadle base, oak cabinet, black japanned head)"],
                 placement="Under the window with the treadle toward the room, 0.4 m from the window pier, chair in front", dimensions="about 0.9 x 0.45 m, 0.78 m high", construction="One new native family (Blender) with a treadle OPERATE owner per the matrix (treadle turns, needle drops); no cloth simulation",
                 materials="cast iron, oak, japanned steel with gold line decals (no lettering)", wear="the treadle worn bright at the ball of the foot; thread ends on the floor", sound="treadle rhythm as the existing sewing possession vocabulary", signal=SIGNAL_NO,
                 purpose="Appliance Bible II: sewing machine in the front room, oiled and true; matrix: OPERATE", sources=["design/ORISON_APPLIANCE_BIBLE.md", "design/PROP_SET_INTERACTION_MATRIX.md", "design/PROP_ACTIVITIES.md"], preserve="Window light, route to the kitchen door", acceptance="Overview shows the machine under the window; E turns the treadle"),
          change("F02_B_MAIN-002", "P1", "add", "The repair queue and the mended armchair", objects=["new: 2B_repair_rail (a wall rail with five hung garments, paper tags)", "new: 2B_armchair (domestic_seating armchair with a contrasting patch on the right arm)"],
                 placement="Rail on the wall beside the private-hall opening at 1.7 m; armchair in the corner away from the window facing the machine", construction="Cloth family garment silhouettes (sewn edges per B4) on a rail; seating variant with a patch decal", materials="burgundy wool, a man's jersey in maroon (Cam's), navy cape lining in scarlet (Teresa's), a celluloid collar (Peter's)",
                 wear="the chair's left arm worn through, the right arm patched proudly", purpose="Life profile hero object mended_upholstery_armchair; proposed backstory: three garments from this building, tagged by floor", sources=["game/data/apartment_life_profiles.json", "design/ORISON_RELATIONSHIP_WEB.md II.5, II.6"],
                 acceptance="Detail views of rail and chair"),
          change("F02_B_MAIN-003", "P2", "refine", "Cutting table surface", objects=["2B_fabric_worktable (existing)", "2B_story_patterns, 2B_story_notions (existing)"], placement="As installed", construction="Add shears, a chalk, a tape and a pincushion from desktop_stock to the table; keep the pattern board",
                 purpose="Daily loop mend, fit, deliver", acceptance="Detail view of the table"),
          change("F02_B_MAIN-004", "P3", "add", "Her own frock with the pinned hem", objects=["new: dress form with a printed voile frock, one hem pinned (cloth family)"], placement="Beside the armchair, 0.3 m from the wall", materials="printed cotton voile, steel pins", purpose="Life profile contradiction: everything mended but her own hem", acceptance="Visible in the reverse view")],
         canon=[C_BIBLE_IV, C_LIFE, C_DECOR, C_APPL, C_WEB], proposed_backstory=["Three garments in the queue are from this building, tagged with floor numbers."], implementation=apt_impl(extra_sources=["design/PROP_ACTIVITIES.md (sewing machine)"])),
    kitchen("F02_B_KITCHEN", "2B", G2B, "cooks_for_others", "The B-type kitchen with its own door: the biggest pots in the building on the range, a stack of borrowed plates chalked underneath, a pie dish wrapped to go for the Ortiz dinner on Sunday."),
    private_hall("F02_B_PRIVATE_HALL", "2B", G2B, "the two fabric shelves (2B_fabric_shelf_01/02) are the vertical fabric store; bolts stand on end with their selvedge out, sorted by weight; the hall is where a client is measured, so the floor is clear and the mirror is here.",
                 extra_changes=[change("F02_B_PRIVATE_HALL-002", "P2", "refine", "Bolts stored vertically", objects=["2B_fabric_shelf_01, 2B_fabric_shelf_02 (Shelf01)"], construction="Add standing bolt cylinders (cloth family) to the shelf variant", materials="wool suiting offcuts, voile, burgundy knit", purpose="Life profile surface set vertical_fabric", acceptance="Threshold view from the main room")]),
    area("F02_B_BED", G2B, "ORISON", "Lena's bedroom", "3.3 x 4.0 m, one window, door from the private hall", "Lena Ortiz",
         ("A small bedroom with the bed and wardrobe; the only room in the flat that is not a workroom, and so the one that shows what she keeps for herself: the long black hair she covers daily "
          "is combed out here (wardrobe bible), a pincushion band on the nightstand, the selvedge scrap that ties her twist on the mirror corner, a photograph of the shop on Greene Street that "
          "is never explained (web I: Triangle Shirtwaist, 1911)."),
         [change("F02_B_BED-001", "P2", "add", "Nightstand, mirror and the one photograph", objects=["new: 2B_bedside (Nightstand01), 2B_mirror (mirror family), 2B_photo (desktop_stock frame)"], placement="Nightstand on the door side; mirror on the wall opposite the window; frame on the nightstand",
                 materials="deal, a cracked mirror glass, a tin frame", purpose="Wardrobe bible towel state (hair down); web I arrival layer as an object, unexplained", sources=["design/ORISON_WARDROBE_BIBLE.md", "design/ORISON_RELATIONSHIP_WEB.md I"], acceptance="Detail view of the nightstand")],
         canon=[C_WARD, C_WEB], proposed_backstory=["The unexplained photograph is the Greene Street factory."], implementation=apt_impl()),
    bath("F02_B_BATH", "2B", G2B, "single_adult", "The bath has a window; a darned stocking dries on the rail (wardrobe bible: one darned at the heel)."),

    # ------------------------------------------------------------------ 2C
    vestibule("F02_C_VESTIBULE", "2C", G2C, "working_musician", "2C's entry opens directly off the public core, so the cable cases stacked inside the door are heard being dragged across the landing at 02:00. The ulster on the hook is a man's.", group_intro=INTRO_2C),
    area("F02_C_MAIN", G2C, "ORISON", "Juno's living room: the chaos with labelled cables", "6.1 x 5.3 m, one window, openings to the vestibule, the studio closet and the private hall", "Juno Kells",
         ("A completion-interior living room: dining set, colour board, bookshelf, wireless table, radiator. It should be a working musician's front room arranged as an album sequence "
          "(decor profile: images read left to right like two beats of a set): the recording rig where a table should be, cable cases open, a takeout carton on the floor, a percolator on the "
          "sill, the one meticulous thing being the cable labels (coloured tape bands on every lead, tied in loops on a hook strip). The player infers that the mess is not carelessness; it is "
          "a person who orders only the channel."),
         [change("F02_C_MAIN-001", "P1", "add", "The rig and the cable hook strip", objects=["new: 2C_rig_table (work_tables family), 2C_mixer (signal family: Bakelite and brass desk with rotary knobs), 2C_reeldeck (reeldeck asm), 2C_cable_hooks (strip with tape-banded loops)"],
                 placement="Rig table against the wall opposite the window where the dining table stood; the dining table moved against the kitchen-side wall as a late-meal surface; hook strip beside the rig at 1.5 m",
                 dimensions="rig table 1.4 x 0.6 m", construction="Reuse asm_reeldeck, asm_headphones, asm_cablecoil; one new small mixer in the signal family (Rule of Signal: forty years early); RESIST-REFUSE owners per the matrix (private rigged equipment)",
                 materials="Bakelite, brass, cloth flex in coloured silk; coloured tape bands", signal=SIGNAL_YES, wear="tape residue on the table edge, a burn from a soldering iron", sound="a valve hum from the rig when powered (existing ambient vocabulary only)",
                 purpose="Life profile surface sets music_work and cable_management; contradiction: meticulous cable labels in a room of chaos", sources=["design/PROP_SET_INTERACTION_MATRIX.md (amp, reeldeck, headphones, cablecoil rows)", "art/blender/work_tables.md"],
                 preserve="Routes to studio and private hall openings; radiator reach", acceptance="Overview from the vestibule reads the rig first"),
          change("F02_C_MAIN-002", "P2", "add", "Album sequence on the wall", objects=["new: two framed images 0.5 m apart on the window wall (CharacterMemoryArt)"], placement="Left to right at 1.5 m, the pipe run avoided (decor profile: pipes must not cut the rhythm)", construction="WallArtLaw hook, two frames",
                 purpose="Decor profile composition", acceptance="Detail view shows two frames with nothing between"),
          change("F02_C_MAIN-003", "P2", "add", "Takeout and coffee", objects=["new: desktop_stock: folded cartons, a percolator, one mug, menus under a magnet"], placement="Carton stack by the private-hall opening; percolator on the window sill", purpose="Kitchen set takeout_plus_coffee spills into the main room", acceptance="Reverse view")],
         canon=[C_LIFE, C_DECOR, C_MATRIX, C_BIBLE_VIII2], implementation=apt_impl()),
    kitchen("F02_C_KITCHEN", "2C", G2C, "takeout_plus_coffee", "The range is used as a shelf for tape boxes (Appliance Bible III); only one burner is lit, under the percolator. The stove's hob tapes (3 strips) exist in data (punchlist 2026-08-21) and should sit on the hob, not inside it.",
            extra_changes=[change("F02_C_KITCHEN-003", "P2", "add", "Tape boxes on the cold side of the range", objects=["new: desktop_stock reel boxes x6 on F02_2C_STOVE_01's cold burners and the wall cupboard"], placement="Stacked on the two burners away from the percolator; never inside the oven leaf's sweep",
                                                   materials="grey card boxes with coloured tape bands", purpose="Appliance Bible III: range used as a shelf", preserve="StoveProp oven leaf and burner service APIs", acceptance="Detail view at the range")]),
    private_hall("F02_C_PRIVATE_HALL", "2C", G2C, "a 6.6 x 1.5 m hall serving bath, kitchen and both bedrooms: a blanket is pinned over the recording-room door's transom and a red lamp jar hangs beside it (the recording light, unlit by day)."),
    area("F02_C_STUDIO", G2C, "ORISON", "Juno's studio closet: the archive wall", "3.4 x 2.5 m, opening from the main room; two wardrobes", "Juno Kells",
         ("A windowless closet with two wardrobes, authored as household work and storage. For Juno it is the stolen session archive (hero object): one wardrobe keeps clothes, the other is "
          "shelved and full of tape boxes dated in her hand, with one reel box labelled only with a 1927 date. The player who opens the second wardrobe sees an archive, not a wardrobe."),
         [change("F02_C_STUDIO-001", "P1", "refine", "Second wardrobe becomes the session archive", objects=["2C_w1_wardrobe (Wardrobe08)"], construction="Wardrobe variant with shelves instead of a rail and reel boxes as owned contents (never loot, per the matrix)", materials="oak, grey card, coloured tape",
                 purpose="Life profile hero object stolen_session_archive; web II.7 take 18 lives here", sources=["art/blender/household_wardrobes.md", "design/ORISON_RELATIONSHIP_WEB.md II.7"], preserve="Both wardrobe leaf motions", acceptance="Opening the leaf shows shelves of boxes")],
         canon=[C_LIFE, C_WEB], proposed_backstory=["One reel box labelled only with a 1927 date."], implementation=apt_impl()),
    bath("F02_C_BATH", "2C", G2C, "single_adult", "Yesterday's kohl on the basin edge; a silver ear cuff on the shelf (wardrobe bible)."),
    area("F02_C_BED1", G2C, "ORISON", "Juno's bedroom", "3.3 x 3.8 m, one window, door from the private hall", "Juno Kells (sleeps late)",
         ("Her one bed, unmade at 20:00 because she rose at noon; the ulster over the foot, knitted bloomers on the chair, the recorder on the nightstand with its strap hanging. "
          "The punchlist records a picture frame wedged between the wardrobe top and ceiling in the earlier layout; V2 has no wardrobe here, so the wall is free for one frame."),
         [change("F02_C_BED1-001", "P2", "refine", "Unmade bed and the recorder on the nightstand", objects=["2C_bed0 (counterpane thrown back variant from the bedding family)", "2C_bed0_ns with desktop_stock recorder (signal device) and a mug"], construction="Bedding family slack variant; recorder as desktop_stock with the licensed early look (black Bakelite, cloth cord)", signal=SIGNAL_YES,
                 purpose="Sleep schedule nocturnal; wardrobe bible signature", sources=["art/blender/bedding.md"], acceptance="Overview shows the bed unmade")],
         canon=[C_WARD, C_LIFE], implementation=apt_impl()),
    area("F02_C_BED2", G2C, "ORISON", "Juno's recording room (converted second bedroom)", "3.3 x 3.8 m, one window, door from the private hall", "Juno Kells",
         ("Data gives 2C a second made bed with its nightstand; the profile converts this room into an acoustically improvised recording room: blankets fixed to the walls with battens, a cable "
          "routed under the door, instrument stands, a boom, the window blanketed, the second bed gone. The player infers the night work and the thing she is not told about."),
         [change("F02_C_BED2-001", "P1", "remove", "Remove the second bed and nightstand", objects=["2C_bed1", "2C_bed1_ns"], purpose="Lived-in brief: retain one bed; the second bedroom is the recording room (life profile room_conversions)", sources=["game/data/apartment_life_profiles.json", "art/data/orison_v2/completion_interiors_source.json"],
                 acceptance="No bed in the room; the completion-interiors test's sleeper count equals one"),
          change("F02_C_BED2-002", "P1", "add", "Blanket walls, stands and the boom", objects=["new: 2C_blanket_panels (cloth family, four 1.2 x 2.0 m hung blankets on battens)", "new: 2C_micstand x2 (asm_micstand), 2C_amp (asm_amp), 2C_guitar (asm_guitar), 2C_pedalboard (asm_pedalboard)"],
                 placement="Blankets on the three solid walls and over the window; stands in the room's centre leaving a 0.8 m route from the door; amp in the corner", construction="Reuse the existing assemblies named in the matrix (amp, guitar, pedalboard, micstand are RESIST-REFUSE owners); blankets with sewn edges",
                 materials="grey and brown wool blankets, pine battens, nickel stands", wear="chalk marks on the floor where the stands go", sound="none added; the room is a dead space acoustically (acoustic graph node may be given higher absorption if the graph supports it)",
                 purpose="Life profile room conversion recording_room; studio brief precedent for the drape family", sources=["design/CLAUDE_APARTMENT_LIVED_IN_PASS.md", "design/PROP_SET_INTERACTION_MATRIX.md", "game/data/acoustic_graph.json"], preserve="Door swing and the route", acceptance="Threshold view from the hall reads a recording room, not a bedroom")],
         canon=[C_LIFE, C_LIVED, C_MATRIX], implementation=apt_impl()),

    # ------------------------------------------------------------------ 2D
    area("F02_D_RESTRICTED", G2D, "ORISON", "2D: the sealed apartment", "10.05 x 8.5 m shell behind the locked F02_D_ENTRY_DOOR off the southwest hall", "nobody; the Tenant; the player cannot enter",
         ("The smoke capture (teleported) shows a bare, lit shell: oak floor, plaster, a ventilation duct with its hangers along the ceiling, a radiator riser, one bath register. The door is locked "
          "(the capture recorded the leaf state) and the hall outside has its own dome. Keep it empty. A sealed flat in a building that keeps everyone is not vacant; it is withheld. What the "
          "player should infer, from the hall only, is that someone pays attention to this door: the Bible's own silence (VIII.5.h) applied to one address."),
         [change("F02_D_RESTRICTED-001", "P1", "keep", "Keep the interior empty and lit as it is", purpose="Intentional empty space; the matrix rules locked doors RESIST-REFUSE with a reason; no interior dressing is proposed", acceptance="Teleported overview unchanged"),
          change("F02_D_RESTRICTED-002", "P2", "add", "The sealed threshold treatment, on the hall side only", objects=["new: a paper notice frame beside F02_D_ENTRY_DOOR (Label3D, one line: the Estate's seal, no explanation)", "new: dust mat without wear, no milk, a strip of brown paper over the letter slot"],
                 placement="Hall side at 1.5 m beside the jamb; mat squared and clean", construction="Notice in the core notice-frame family; paper strip decal on the leaf", materials="foxed paper, brown gummed paper", wear="none on the mat (nobody comes), a fingerprint on the paper strip (someone checks)",
                 sound="through the door only: nothing; the acoustic graph should give 2D a dead node so the riser knock stops at its wall", purpose="The building's silence as a visible fact; the Rule of Signal's listening head inside is the only thing that still works", signal=SIGNAL_NO,
                 sources=["design/ORISON_BIBLE.md VIII.5.h", "design/PROP_SET_INTERACTION_MATRIX.md locked doors", "game/data/acoustic_graph.json"], preserve="Lock state and the 7 locked-door count asserted by the matrix", acceptance="Threshold view from F02_SOUTHWEST_HALL shows notice, strip and clean mat; the door rattles with its reason")],
         canon=[C_BIBLE_VIII5H, C_MATRIX], implementation={"sources": ["game/data/orison_v2/upper_floor_programs.json (disposition sealed)", "game/scripts/building/orison_v2_domestic_doors.gd (locked leaves)"], "dependencies": "none", "preserved": "Locked state, interior shell, vent register", "acceptance": "ResidentKeyRoute and domestic door tests unchanged"},
         coverage="inaccessible_teleported"),
]
