"""The attached playable areas: street, facade, service alley, subway approach, bodega, the Vantry Arcade and its eleven shops, the Harukiya."""
from _common import *

GS = "STREET / facade, alley, subway approach"
GBO = "BODEGA"
GA = "VANTRY ARCADE (the Passage) / eleven shops"
GH = "HARUKIYA"

INTRO_STREET = ("<b>The street.</b> One 30 ft road crossing with 15 ft walks, no dedicated crossing point, no death: being hit is a horn, a shove and four seconds of lost dignity (ORISON_STREET_BRIEF, "
                "built). Traffic is ten instanced kinds including a rail-less tram (the authored wrong five percent) and the rare WE TUNA PIANOS truck; night traffic reads by wet-road headlight "
                "pools; both ends are the densest part of the same storm behind wet timber hoardings (T8), with a proposed railway crossing both ends (T-ENDS, not built). The front facade, "
                "marquee, neon blade, front pavement and city shells are fitted; the gateway host and the subway kiosk stair (K0/K1) stand opposite; the bodega is at the east end of the north "
                "walk. Bible VIII.1: there are still horses on Roosevelt Avenue; VIII.4: ice and coal. The street is correct and quiet; what it lacks at 20:00 on a Saturday in November is the "
                "ordinary trade of a Queens block: a newsstand's light, steam from a laundry vent, an ash can, a horse's consequence, the election's paper.")

INTRO_BODEGA = ("<b>The bodega.</b> The hero shop by owner ruling (ORISON_COMMERCIAL_DESTINATION_PLAN, 2026-08-29): counter, stools, display case, coffee urn, the cooler that hums (Juno records it), "
                "a radio, aisles of goods still advertising for manufacturers who no longer exist, the sale sign with the error Evelyn corrects in her head, the back counter of notions (fuses, "
                "washers, tape, wire) so the super's errand and the neighbours' share one room, and a receiving room behind. Thirteen residents a day use it with specific habits (schedules). "
                "The source-owned fittings (966 stocks, lined icebox, recessed counter, delivery cart, practicals), the fitted frontage, receiving room, power intake and the HALF BAKED signage "
                "are implemented. In 1928 the bodega sells valves in printed sleeves beside the cigarettes (Bible VIII.4) and hearing-aid batteries for Cal. The destination plan's impossible "
                "back-room link to the Arcade's service corridor is a ruled design not yet built; nothing here depends on it.")

INTRO_ARCADE = ("<b>The Vantry Arcade.</b> Eleven shops in one glass-vaulted hall behind a 6 m street portal and a 10.3 m throat: west side laundry, cobbler, locksmith, hardware, funeral; east side "
                "diner, druggist, news, pawn, radio, photo (FINAL_MAP_REDESIGN_BRIEF; VANTRY_ARCADE_RECONSTRUCTION_BRIEF V1 built the nave, clerestory, lantern and pendant clock). Three loaded "
                "handcarts, brass nosings, cast-iron edge drains and wheel wear are the finish layer; at 02:00 ten shops close behind sliding iron lattice grilles and the carts are chained; "
                "HARDWARE PAINT alone keeps night service because the Mina loop buys the capsule there (PS6). Every shop has a ledger (shop guide II.3) and a back door that says there is depth "
                "(V2 phase: rear zones as view-only). The shop guide's hero objects and flair items are largely fabricated (DOCS.md's October family records); this dossier checks each against "
                "the capture and proposes only what the guide names and the fabrication index leaves open: rear rooms, the human traces, the hours states.")

INTRO_BAR = ("<b>The Harukiya.</b> Otomo's basement bar transplanted under the south block and run by a Japanese operator (ledger A0.4): the teal littered descent with the soiled red rug, the "
             "battered red steel door, two receiving cabinets immediately left on entering, the long counter under its 1.76 m canopy with the rim light, the barrels and crowded pictures behind the "
             "backbar, the violet-felt pool table, the plywood stage with the phonautograph and the Songbook, the couch banks, palms, the jukebox, one tiny customer WC. The grand fabric is inherited "
             "second-hand from a closed hotel bar (A0.3); the signal machines are native and forty years early; the jukebox's records stay dated 1999-2008 as the phenomenon; the two photographs "
             "show the block in 1913 and 1919. G08-G13 (loudspeakers, piano and microphone, phonautograph, darts, receiving cabinets, signage) and the gallery, stage, pool, fixture mounts, pipe "
             "supports, ceiling finish, furniture and service access are implemented. Prohibition is not in canon; the room reads as a speakeasy for free if the owner wants it (see canon findings).")

def city(id, group, title, location, users, narrative, changes, capture_ids, canon=None, proposed_backstory=None, implementation=None, coverage=None, group_intro=None, evidence=None):
    a = area(id, group, group.split(" ")[0], title, location, users, narrative, changes, canon=canon, proposed_backstory=proposed_backstory, implementation=implementation, coverage=coverage, group_intro=group_intro, capture_ids=capture_ids, level="F01", evidence=evidence)
    return a

SHOP_IMPL = {"sources": ["art/data/building_layout.json (F01 markers and shop furniture records)", "game/data/floor_01_cell_registry.json", "art/blender/<shop>_*.md records listed in DOCS.md", "game/scripts/building/orison_v2_passage_region.gd and orison_v2_shop_seating.gd mount_records"],
             "dependencies": "Blender native batch per shop family; one composed OrisonV2FabricationBatch run; 9 m shop-batch contract; Label3D for lettering", "preserved": "Shop thresholds, counters, passage_shop_hours markers, grilles, carts, the HARDWARE PAINT counter and its night service, the receiving cabinets and keyboard owners, the 11 ledgers", "acceptance": "Shop entry, passage hours, visibility and ownership tests unchanged; doorway view, pavement-through-glass view and counter clearance per the shop guide VI"}

AREAS = [
    city("CITY_STREET", GS, "The street: road, walks and traffic", "The 30 ft carriageway and both 15 ft walks between the Orison's front and the south block (Harukiya, gateway, kiosk), from the west hoarding to the east hoarding", "everyone crossing; traffic",
         ("The route captures walk the north pavement from the Orison door to the bodega and back; the facade stations look at the building from the carriageway. The street works as built. "
          "At 20:00 in November it should also carry the block's trade and the day's paper: a newsstand's lit hatch (the News booth is in the Arcade; a second street kiosk is not proposed), "
          "an ash can at every areaway, horse consequence in the gutter with the restrained fly shimmer the commensals brief allows, the election's broadsides pasted on the hoarding, the "
          "laundry's steam vent on the Arcade's west flank (the Model Laundry is inside the Passage; its vent can still breathe onto the street), and sound: a train on the proposed viaduct, "
          "heard not seen (T-ENDS open question). The player infers a working Queens street that does not stop for the storm."),
         [change("CITY_STREET-001", "P2", "add", "Ash cans and horse consequence", objects=["new: galvanised ash cans at three areaways (instanced), two horse droppings decals in the carriageway's dray lane with the brief's fly shimmer (C2 gated)"], placement="Cans against the facades clear of both walks' routes; droppings in the lane, never on the crossing line", materials="galvanised tin", purpose="Bible VIII.1 horses; commensals brief street section", sources=["design/ORISON_COMMENSALS_BRIEF.md", "design/ORISON_STREET_BRIEF.md"], preserve="Crossing gaps, stagger contact, route limits", acceptance="Street route and containment tests unchanged"),
          change("CITY_STREET-002", "P2", "add", "Election broadsides on the hoardings", objects=["new: pasted paper rectangles with a portrait silhouette and a star (no lettering) on both end hoardings"], purpose="Period: four days after the Hoover-Smith election; the hoarding already carries old notices", acceptance="End-of-street views"),
          change("CITY_STREET-003", "P3", "add", "Laundry steam at the Arcade flank", objects=["new: a steam vent with a slow particle-free billboard plume on the west host building's flank (WeatherFX family)"], purpose="Destination plan: a laundry vents steam to the pavement; sensory and an occluder", acceptance="Street view from the Orison door"),
          change("CITY_STREET-004", "P3", "add", "Train pass, heard not seen", objects=["new: one scheduled distant train sound from the east end every few minutes (existing acoustic/weather bed)"], purpose="T-ENDS: whether a train is ever seen or only heard; heard is cheaper and better", sources=["TASKS.md T-ENDS"], acceptance="Audible from the apron without a visible source")],
         capture_ids=["route_orison_to_shop_bodega_*", "route_shop_bodega_to_orison_*", "facade_street_*"], canon=["design/ORISON_STREET_BRIEF.md section 8 rulings", "TASKS.md T-ENDS", C_COMMENSALS, C_BIBLE_VIII4], group_intro=INTRO_STREET,
         implementation={"sources": ["art/data/gen_layout.py (street records)", "game/scripts/building/orison_v2_street_boundaries.gd", "game/scripts/street/street_traffic.gd"], "dependencies": "Street perf: at most +3 draws and +0.3 ms (commensals contract)", "preserved": "Traffic stream, stagger, containment, bodega route", "acceptance": "StreetContainmentTest, street crossing and route tests unchanged"}),
    city("CITY_FACADE", GS, "The Orison facade from the pavement", "The front elevation seen from the carriageway and the walks: the entrance, marquee, neon blade, windows and the front-court roof", "everyone arriving",
         ("Front, approach, door, canopy and wide stations; the blade station if the sign resolved. The facade is fitted (front_facade.md, front_court_roof.md, exterior masonry). The only "
          "building-wide story the elevation can tell is who is awake: the window glow authority already lights windows by schedule; add the ice cards in the icebox flats' kitchen windows "
          "(Bible VIII.5.a), a curtain state per sleep schedule (blackout at 1D by day), and the EST. 1928 sign's reading from the street (Bible VIII.5.h). A05 exterior stone trim is pending in the owner JSON."),
         [change("CITY_FACADE-001", "P2", "add", "Ice cards and curtain states in the windows", objects=["window joinery family: ice card rectangles in the kitchen windows of icebox flats facing the street; blackout state for 1D and the day-sleepers"], purpose="Bible VIII.5.a: the ice card tells the iceman and the player; lived-in pass: window treatment matches sleep schedule", sources=["art/blender/window_joinery.md", "game/data/apartment_life_profiles.json sleep_schedule"], preserve="Window glow authority", acceptance="Front wide station reads cards and one blacked window")],
         capture_ids=["facade_front", "facade_approach", "facade_door", "facade_canopy", "facade_front_wide", "facade_blade"], canon=[C_BIBLE_VIII5A, C_BIBLE_VIII5H, C_OWNER], implementation={"sources": ["art/blender/front_facade.md", "art/blender/exterior_masonry.md", "art/blender/window_joinery.md"], "dependencies": "A05 pending", "preserved": "Facade owners", "acceptance": "Front facade test unchanged"}),
    city("CITY_ALLEY", GS, "The service alley", "The graded rear alley from the rear service door north and east to the street, with the shed and its work lights (G07), the coal cover, the boiler well window", "the player; deliveries; Teresa at 22:00",
         ("Eight walk stations outward and two looking back. The alley is fitted (service_alley.md, groundworks.md, boiler_window.md, G07 lights). It should show its trade: ash cans at the rear "
          "door, a coal cart's wheel ruts to the cover, a drain grate with leaves, a rag on the shed hook, a cat's absence (C4 gated), the neighbours' backs with one lit window. The player "
          "infers a working alley that the front of the building hides."),
         [change("CITY_ALLEY-001", "P2", "add", "Wheel ruts to the coal cover, leaves at the grate", objects=["rut decals from the street mouth to the coal cover; leaf litter decal at the drain collector"], purpose="Bible VIII.5.c coal delivery; groundworks' drain collector gets a consequence", sources=["art/blender/groundworks.md", "design/ORISON_V2_COAL_DELIVERY_PROGRESS_2026-09-26.md"], preserve="Alley route and boundaries", acceptance="Service alley test unchanged; walk stations show the ruts"),
          change("CITY_ALLEY-002", "P3", "add", "One lit window in a neighbour's back", objects=["city shells: one emissive window pane on the north neighbour's rear face"], purpose="The alley is overlooked; Accord 15 light is practical (a window is a fixture)", acceptance="Alley station 3")],
         capture_ids=["alley_*"], canon=[C_BIBLE_VIII5C, C_OWNER], implementation={"sources": ["art/blender/service_alley.md", "art/blender/groundworks.md", "art/blender/city_shells / city_closure.md"], "dependencies": "none", "preserved": "Rear door route, shed lights", "acceptance": "Service alley test unchanged"}),
    city("CITY_SUBWAY", GS, "The subway kiosk approach", "The K0/K1 gateway host and exit kiosk stair opposite the Orison, beside the Arcade portal", "nobody descends; it is a finite dark terminus",
         ("A single approach station toward the kiosk. K0 and K1 are built: iron panels, wire glass, unlit EXIT / RAPID TRANSIT, eight treads, tiled cheeks, a finite dark terminus. In 1928 Queens "
          "the subway was the elevated along Roosevelt Avenue and the IND under construction; the kiosk's language is right. Nothing to add but sound and light: reflected train light up the "
          "stair and a draught, both listed as optional later gates."),
         [change("CITY_SUBWAY-001", "P3", "keep", "Keep the kiosk as a terminus", purpose="PS11: a station, cutscene, route or fourth zone is rejected", acceptance="Unchanged"),
          change("CITY_SUBWAY-002", "P3", "add", "Reflected train light and a draught", objects=["new: a timed pale flicker up the stair cheeks and a paper scrap stirring at the top tread (existing lighting/weather owners)"], purpose="Gateway proposal: sound/reflected train light remain optional later gates", acceptance="Kiosk station shows the flicker once")],
         capture_ids=["subway_approach"], canon=["design/VANTRY_GATEWAY_AND_SUBWAY_PROPOSAL.md", "TASKS.md PS11"], implementation={"sources": ["design/VANTRY_SUBWAY_KIOSK_PROPOSAL.md"], "dependencies": "none", "preserved": "Kiosk envelope", "acceptance": "FULL walk unchanged"}),

    city("CITY_BODEGA", GBO, "The bodega: counter, aisles, cooler, receiving", "The corner shop at the east end of the north walk: storefront leaf, counter case, two aisles, the lined icebox cooler, the delivery cart, the receiving room behind the sales aisle", "thirteen residents a day; the night clerk; the player on errands",
         ("Seven authored stations: aisles, stock, counter, cooler, window stock, delivery, the back door; plus the route's bodega nodes. The source-owned fittings, frontage, receiving room and "
          "power are implemented and the stock depletes with real visits. The room should now carry the schedules' specifics: the sale sign with its error (a chalked numeral quadrant; Evelyn "
          "corrects it in her head), the counterman's stool and the ledger of credit (shop guide II.3), the beer cooler where Sacha's film is kept (an arrangement), the hearing-aid batteries "
          "Cal buys at 17:30 in a card by the till, valves in printed sleeves beside the cigarettes (Bible VIII.4), a brown derby on the counter nail, the notions counter at the back with "
          "fuses, washers, wire and tape (the super's errand), and the cat that is deferred (C4). The player infers the most densely populated social room in the fiction."),
         [change("CITY_BODEGA-001", "P1", "add", "Valves beside the cigarettes and the batteries card", objects=["new: a card of valve sleeves (six for a dollar: painted price quadrant, no lettering) on the counter case's end; a card of hearing-aid batteries by the till"], placement="On the counter case within the counterman's reach, clear of the purchase stance", construction="desktop_stock pieces seated on the counter support", signal=SIGNAL_YES,
                 purpose="Bible VIII.4: a shop stocking valves says everything about this world in one shelf; schedule: Cal's batteries", sources=["design/ORISON_BIBLE.md VIII.4", "game/data/resident_schedules.json cal_dwyer bodega"], preserve="Purchase stance and the counter owner", acceptance="Counter station shows both cards"),
          change("CITY_BODEGA-002", "P1", "add", "The notions counter at the back", objects=["new: a short back counter (work_tables family) with fuse boxes, washers in a tray, a coil of wire, tape rolls (desktop_stock) and a second small ledger"], placement="Across the rear of the sales aisle before the receiving door, leaving the 30-waypoint receiving route clear", purpose="Destination plan: the corner store that stocks what the block needs; every part fetch is a social encounter", sources=["design/ORISON_COMMERCIAL_DESTINATION_PLAN_2026-08-29.md"], preserve="Receiving leaf and sales-aisle route", acceptance="Delivery station shows the counter; receiving route test unchanged"),
          change("CITY_BODEGA-003", "P2", "add", "The sale sign's error, the ledger, the derby", objects=["new: chalked sale card on the window stand with a quadrant numeral crossed out; a credit ledger on the counter; a brown derby on a nail"], purpose="Schedules: Evelyn corrects the sale sign; II.3 every shop has a ledger; period ephemera", acceptance="Window-stock and counter stations"),
          change("CITY_BODEGA-004", "P3", "add", "Sacha's film in the beer cooler", objects=["two film tins on the cooler's lowest shelf among the bottles"], purpose="Schedule: the counterman keeps their film stock in the beer fridge", preserve="Cooler depletion presentation", acceptance="Cooler station")],
         capture_ids=["bodega_*", "route_orison_to_shop_bodega_3", "route_orison_to_shop_bodega_4", "route_shop_bodega_to_orison_0"], canon=[C_BIBLE_VIII4, C_SCHED, "design/ORISON_COMMERCIAL_DESTINATION_PLAN_2026-08-29.md", C_OWNER], group_intro=INTRO_BODEGA,
         implementation={"sources": ["art/blender/bodega_fittings.md", "art/blender/bodega_frontage.md", "art/blender/bodega_receiving.md", "art/blender/bodega_power.md", "game/scripts/building/orison_v2_exterior_cell.gd"], "dependencies": "G13 bodega signage implemented; no new light", "preserved": "Stock depletion registry, storefront leaf, receiving leaf, counter purchase", "acceptance": "Bodega fittings, frontage, receiving-route and power tests unchanged"}),

    city("CITY_PASSAGE", GA, "The nave: portal, throat, aisle, crossing and terminus", "The 6 m street portal, 10.3 m throat, 20 x 26 m hall with the terrazzo aisle, barrel vault, clerestory, crossing lantern and pendant clock, south terminus with the directory; three handcarts; grilles at night", "shoppers by day; the player at night when only HARDWARE PAINT is lit",
         ("The passage floor surveys and the aisle light stations. V1 of the reconstruction raised the nave; V2-V6 (rear zones, storefront families, light hierarchy, evidence of use and historical "
          "layering, abnormalities) remain. At 20:00 the hall should be the night-jewel state: grilles down on ten shops, the aisle's pendants on, one warm bay at the far end, the carts chained, "
          "the clock lit. Evidence of use (V5): worn thresholds and brass, a parcel shelf, ghost signs, one 1950s fluorescent retrofit in a cheap tenant (the dated-arrival phenomenon, like the "
          "jukebox records). The directory should list a shop that is not there (V6's restrained impossible)."),
         [change("CITY_PASSAGE-001", "P2", "add", "Night-jewel hours state check", objects=["PassageHoursDirector states at 20:00: ten grilles closed? (shop guide: ordinary closing begins at 02:00, so at 20:00 the shops are OPEN and lit)"], purpose="Verify the capture's hour: the shops are open until 02:00, so the 20:00 nave must read as an evening arcade, lit and trading, with the diner and laundry doors open", sources=["TASKS.md PS6", "design/SHOP_INTERIOR_BUILD_GUIDE.md I"], acceptance="Passage stations show open grilles and lit shopfronts; if closed, the hours director's clock binding is the defect"),
          change("CITY_PASSAGE-002", "P2", "add", "V5 evidence of use on the aisle", objects=["worn brass nosings (already fitted) plus: a parcel shelf by the terminus directory, a ghost sign on the throat's brick, one fluorescent tube in the pawnbroker's fascia (anachronism as phenomenon)"], purpose="Reconstruction brief V5; Bible VIII.5.g precedent for dated arrivals", sources=["design/VANTRY_ARCADE_RECONSTRUCTION_BRIEF.md"], preserve="Aisle light ids and positions, cart lanes", acceptance="Aisle stations"),
          change("CITY_PASSAGE-003", "P3", "add", "The directory's extra shop", objects=["terminus directory (Label3D): one line for a trade with no bay"], purpose="V6: the directory listing a shop that is not there", acceptance="Terminus station")],
         capture_ids=["passage_*", "PASSAGE_*"], canon=["design/VANTRY_ARCADE_RECONSTRUCTION_BRIEF.md", "TASKS.md PS6, PS12", C_SHOPS], group_intro=INTRO_ARCADE, implementation=SHOP_IMPL, coverage="unreviewed",
         evidence={"limits": "No capture station stood in the nave itself: the city sweep's floor surveys cover the shop sales floors, rear stores and the bar, and its aisle light markers are not stations. The nave is visible only in the backgrounds of shop-threshold stations (for example shop_keys_cut_SITE_SHOP_IN1 and shop_shoe_rebuilding_SITE_SHOP_IN1 look out through the glazing). A follow-up capture should add the eight PASSAGE_AISLE_LT_nn and two PASSAGE_PORTAL_LT markers as stations.", "observed": ["Through the shop glazing at 20:00 the aisle reads lit, with shopfronts and signs across it; the grille state could not be judged from inside the shops."], "interpretations": ["The arcade's own evidence of use (V5) and its night state remain unreviewed by this pass."]}),
    city("CITY_SHOP_MODEL_LAUNDRY", GA, "MODEL LAUNDRY: hand laundry", "West side, first bay (5.40 x 7.00 m), awning front, door open by day; rear store behind", "the proprietor; Rhea on Saturdays with the week in a bag",
         ("Marker stations IN0-IN2, the front floor survey and the rear-room survey. Fitted: parcel shelves, ticket wire, transaction furniture, wrapped parcels, hung shirts, open tubs, the "
          "opposed-roll wringer, flat irons, drying racks, ironing furniture, the receiving cabinet (NIGHT MAIL). The guide's flair, that the unclaimed parcels are dated and some tickets are "
          "years old, needs the ticket halves on the wire to vary in age (yellowed to white) and the parcel wall's string to sag on the oldest row. The rear should read as the wash house: tubs, "
          "heat, a stove, steam."),
         [change("CITY_SHOP_MODEL_LAUNDRY-001", "P2", "refine", "Aged ticket halves and the oldest parcel row", objects=["laundry_trade ticket wire: ticket halves in four ages; parcel shelves: the top row's string sagging, paper darker"], purpose="Shop guide 1 flair: the unclaimed parcels are dated; the rhyme with the photo shop's portraits", sources=["art/blender/laundry_trade.md", "art/blender/laundry_fittings.md"], acceptance="Counter station reads age on the wire"),
          change("CITY_SHOP_MODEL_LAUNDRY-002", "P2", "add", "Steam and heat in the rear", objects=["rear store: a gas ring under the irons with a glow decal, a steam billboard above the tubs (WeatherFX), a wet floor mask"], purpose="Guide: this is hands, water, a mangle and heat; V2 rear zones", acceptance="Rear survey stations")],
         capture_ids=["shop_model_laundry_*", "storm_shop_model_laundry_*", "site_rear_model_laundry_*"], canon=[C_SHOPS, "art/blender/laundry_trade.md"], implementation=SHOP_IMPL),
    city("CITY_SHOP_SHOE_REBUILDING", GA, "SHOE REBUILDING: the cobbler", "West side, second bay (5.40 x 6.00 m), blade sign, door closed", "the proprietor",
         ("Fitted: the finishing machine, patcher, stock, open paired shoes, fine dust finish and the rear approach (cobbler_fittings.md; T12 reviewed). The guide's flair is the leather dust on every "
          "horizontal surface with a clean rectangle where the ledger sits; the capture should show the dust mask and the clean rectangle. The waiting seat with a footrest and the rack of lasts "
          "like a bone collection are the remaining legibility items."),
         [change("CITY_SHOP_SHOE_REBUILDING-001", "P2", "add", "Lasts rack and the waiting seat", objects=["new: a rack of iron lasts in sizes (shop stock family), a low seat with a footrest (shop_seating)"], placement="Rack on the party wall behind the bench; seat by the door inside the swing's clear", purpose="Shop guide 2 fittings", sources=["art/blender/cobbler_fittings.md", "art/blender/shop_seating.md"], acceptance="Doorway station"),
          change("CITY_SHOP_SHOE_REBUILDING-002", "P3", "refine", "The clean rectangle under the ledger", objects=["dust mask with a clean rectangle at the ledger's seat on the counter"], purpose="Guide flair", acceptance="Counter detail")],
         capture_ids=["shop_shoe_rebuilding_*", "storm_shop_shoe_rebuilding_*", "site_rear_shoe_rebuilding_*"], canon=[C_SHOPS], implementation=SHOP_IMPL),
    city("CITY_SHOP_KEYS_CUT", GA, "KEYS CUT: the locksmith", "West side, third bay (3.40 x 5.00 m), blade sign; the key-copy counter where resident keys are authorized", "the proprietor; residents copying keys; the player",
         ("Fitted: the key board (98 pierced blanks), machinery, display, the authorized key-copy transaction (resident_keys.md). The guide's flair is the ledger: a register of every key cut in the "
          "building, address, date, how many. The ledger exists in the 11-ledger contract; it should sit open at the counter with the building's name implied by a numeral column (no lettering). "
          "The second-hand fire safe with a dead company's gold-leaf name (as a blank cartouche) and the roll of picks unrolled are the remaining items."),
         [change("CITY_SHOP_KEYS_CUT-001", "P2", "add", "The safe and the picks", objects=["new: a second-hand fire safe in the corner with a blank gold-leaf cartouche; a roll of picks unrolled on the bench (shop stock family)"], placement="Safe in the rear corner clear of the counter stance; picks on the bench", purpose="Shop guide 3 fittings", sources=["art/blender/locksmith_fittings.md"], acceptance="Doorway and counter stations"),
          change("CITY_SHOP_KEYS_CUT-002", "P2", "refine", "The register open at the counter", objects=["keys_cut ledger: open, a column of numerals as strokes, a pencil on a string"], purpose="Guide flair: the most quietly frightening object on the street", acceptance="Counter detail")],
         capture_ids=["shop_keys_cut_*", "storm_shop_keys_cut_*", "site_rear_keys_cut_*"], canon=[C_SHOPS, "art/blender/resident_keys.md"], implementation=SHOP_IMPL),
    city("CITY_SHOP_HARDWARE_PAINT", GA, "HARDWARE PAINT: night service", "West side, fourth bay (5.20 x 6.50 m), blade sign; the only shop lit and open at 03:00; the maintenance counter where the capsule is bought", "the player on the first shift; Omar for fuses",
         ("Fitted: the ordered drawer wall, aisle panels, paint bench, balance, shaker, mixing paddle, bins, coupling stock, window stand, service counter, glass stand, seven tools with one empty "
          "silhouette, the leaning ladder (the only ladder on the block). The guide's flair is complete. What the night-service state needs is the proprietor's absence made legible: a bell on the "
          "counter, a card (Label3D) saying night service, a lamp over the counter brighter than the shop (the openish lamp energy), and the carbon transmitter capsule's box visible on the shelf "
          "behind the counter so the player can see what they are buying."),
         [change("CITY_SHOP_HARDWARE_PAINT-001", "P1", "add", "Counter bell, night-service card and the capsule box on the shelf", objects=["new: brass counter bell, a night-service card (Label3D, telegram grammar), a capsule box on the shelf behind the counter (desktop_stock)"], placement="On storm_shop_hardware_paint_counter_top clear of the purchase stance; box on the first shelf behind", signal=SIGNAL_YES, purpose="PS6: one warm bay at the far end; core loop: the capsule is bought here", sources=["game/docs/core_loop.md", "TASKS.md PS6"], preserve="MaintenanceShopCounter owner and stock validation", acceptance="Golden repair route test unchanged; counter station shows bell, card and box")],
         capture_ids=["shop_hardware_paint_*", "storm_shop_hardware_paint_*", "site_rear_hardware_paint_*"], canon=[C_SHOPS, "game/docs/core_loop.md"], implementation=SHOP_IMPL),
    city("CITY_SHOP_FUNERAL_PARLOUR", GA, "FUNERAL PARLOUR: arranged and empty", "West side, fifth bay (4.40 x 7.00 m), awning", "nobody; the register has one signature",
         ("Fitted: the lectern and the deliberately empty bier, fixed curtain runs, potted palms and laid wreaths, the empty window stand. The guide's flair: price cards on the sample caskets turned "
          "face down, and the register open at a page with one signature and a lot of blank lines (Dorothy Ash went from here). Keep the emptiness; add only the chairs in rows if absent, "
          "the three caskets at three price grades with their cards face down, and a telephone on a small desk (a signal device, early)."),
         [change("CITY_SHOP_FUNERAL_PARLOUR-001", "P2", "add", "Three sample caskets with price cards face down", objects=["new: three caskets at three grades in the corner (shop stock family), card rectangles face down"], placement="Rear corner clear of the chair rows and the bier's approach", purpose="Shop guide 8 flair", sources=["art/blender/funeral_fittings.md"], acceptance="Doorway station"),
          change("CITY_SHOP_FUNERAL_PARLOUR-002", "P2", "refine", "The register's one signature", objects=["lectern register: one signature stroke and blank rules"], purpose="Guide: Dorothy Ash went from here", acceptance="Lectern detail"),
          change("CITY_SHOP_FUNERAL_PARLOUR-003", "P3", "keep", "Keep the bier empty and the room orderly", purpose="Guide: nothing in this room is a shock; the emptiness is the object", acceptance="Unchanged")],
         capture_ids=["shop_funeral_parlour_*", "storm_shop_funeral_parlour_*", "site_rear_funeral_parlour_*"], canon=[C_SHOPS, "art/blender/funeral_fittings.md"], implementation=SHOP_IMPL),
    city("CITY_SHOP_LUNCHEONETTE", GA, "LUNCHEONETTE: the diner", "East side, first bay (5.00 x 7.00 m), awning, door open; two receiving cabinets in the corner", "Peter on Saturdays at the third stool; Iris on Thursdays",
         ("Fitted: griddle, soda pumps, mixer, hollow urns, the empty pie display, back bar, narrow shelves, register, cigar display, counter, kickplate, ledger, the tall/compact receiving pair and "
          "the overhead. The guide's hero is the back bar with its urns; it is built. The remaining items: eight stools (shop_seating has the soda-counter stools), the menu board with sliding "
          "letters (Label3D), a ceiling fan, sugar shakers and a jar of pickled eggs, and Peter's third stool worn differently from the rest (same order since 1924)."),
         [change("CITY_SHOP_LUNCHEONETTE-001", "P2", "add", "Menu board, shakers, pickled eggs, the fan", objects=["new: menu board (Label3D), sugar shakers and a jar on the counter (desktop_stock), a ceiling fan (static)"], purpose="Shop guide 5 fittings", sources=["art/blender/diner_overhead.md", "design/V2_DINER_BACKBAR_2026-10-06.md"], acceptance="Counter station"),
          change("CITY_SHOP_LUNCHEONETTE-002", "P3", "refine", "The third stool's wear", objects=["shop_seating stool 3: vinyl top worn through to the cord"], purpose="Schedule: Peter's third stool since 1924", acceptance="Stool detail")],
         capture_ids=["shop_luncheonette_*", "storm_shop_luncheonette_*", "site_rear_luncheonette_*"], canon=[C_SHOPS, C_SCHED], implementation=SHOP_IMPL),
    city("CITY_SHOP_OTIS_SON", GA, "OTIS & SON: the druggist", "East side, second bay (4.10 x 7.00 m), awning; the near-side shop thirty seconds from the door", "the block; Rhea for pastilles",
         ("Fitted: counter and the 54-drawer cabinet, telephone and ledger, mortar, dispensary bench, balance case, round ranks, the locked poison cupboard with tactile bottles, the hero carboys and "
          "window display, the unused soda fountain. The guide's whole programme is built. Remaining: the colour the carboys throw onto the pavement at night (the window stand's backlight), "
          "and the four stools at the fountain if absent."),
         [change("CITY_SHOP_OTIS_SON-001", "P2", "refine", "Carboy backlight onto the pavement", objects=["window stand: a practical behind the carboys (one of the fitted shop lights) so the glass throws colour onto the aisle at night"], purpose="Shop guide 11 hero: they throw colour onto the pavement at night; Accord 15 light is practical", sources=["art/blender/druggist_carboys.md"], preserve="Light budget", acceptance="Pavement-through-glass station shows colour on the terrazzo")],
         capture_ids=["shop_otis_son_*", "storm_shop_otis___son_*", "site_rear_otis___son_*"], canon=[C_SHOPS], implementation=SHOP_IMPL),
    city("CITY_SHOP_NEWS_CIGARS", GA, "NEWS & CIGARS: the booth", "East side, third bay (2.10 x 4.00 m), blade; the proprietor's side is deliberately inaccessible; served through the hatch", "the proprietor on his stool; Malcolm for the form guide on Sundays",
         ("Fitted: source-owned papers, glazed stock, pipe bowls, counter, the seated proprietor stool, the receiving cabinet (OUTER RIM). The guide's flair: the proprietor's chair has worn a hollow "
          "in one floor tile and the punchboard is half punched. The headline board is the period's voice (Label3D): on 10 November 1928 it is the election's week."),
         [change("CITY_SHOP_NEWS_CIGARS-001", "P2", "add", "The hollow in the tile and the punchboard", objects=["floor tile under the stool: a dished variant; a punchboard on the counter half punched (shop stock family)"], purpose="Shop guide 6 flair", sources=["art/blender/news_fittings.md"], acceptance="Hatch station"),
          change("CITY_SHOP_NEWS_CIGARS-002", "P3", "add", "Headline board for the week", objects=["headline board (Label3D, telegram grammar): the election result as a single line"], purpose="Period; no lettering in texture", acceptance="Pavement station")],
         capture_ids=["shop_news_cigars_*", "storm_shop_news_cigars_*", "site_rear_news_cigars_*"], canon=[C_SHOPS], implementation=SHOP_IMPL),
    city("CITY_SHOP_PAWNBROKER", GA, "PAWNBROKER: the block's bank", "East side, fourth bay (4.40 x 6.00 m), blade", "the block's worst months",
         ("Fitted: the passive clock wall, hollow display cases, window stock, parcel racks, grille counter, safe, the receiving cabinet (TOWER OF ASH), T10 finishes. The guide's hero, the unredeemed "
          "shelf of numbered parcels and objects, and the flair that no two clocks agree, are built. Remaining: the balance under a glass dome, the loupe on a cord, the pledge ledger (the "
          "fabrication index lists shelving, grille/counter, safe, balance, ledger, loupe as open), and the window's three sad objects (a violin case, a wedding ring in an envelope)."),
         [change("CITY_SHOP_PAWNBROKER-001", "P2", "add", "Balance under a dome, loupe on a cord, the pledge ledger", objects=["new: jeweller's balance in a glass dome on the counter, a loupe on a cord, a heavy ledger with a pen (shop stock family)"], placement="Counter inside the grille, clear of the wicket's pass shelf", purpose="Shop guide 7 fittings; fabrication index open items", sources=["art/blender/pawn_fittings.md", "art/blender/v2_fabrication_coverage.md"], acceptance="Counter station"),
          change("CITY_SHOP_PAWNBROKER-002", "P3", "refine", "A wedding ring in a tiny envelope in the window", objects=["window stock: one small envelope with a ring shape"], purpose="Guide: every one is somebody's worst month", acceptance="Window station")],
         capture_ids=["shop_pawnbroker_*", "storm_shop_pawnbroker_*", "site_rear_pawnbroker_*"], canon=[C_SHOPS, "art/blender/pawn_clocks.md"], implementation=SHOP_IMPL),
    city("CITY_SHOP_RADIO_SERVICE", GA, "RADIO SERVICE: the one shop the divergence touches", "East side, fifth bay (3.00 x 5.00 m), awning; a receiving cabinet", "the man who knows about 1610 and will not say",
         ("Fitted: the alignment bench and side leaf, counter, ledger and horn/cone window display, aerial-wire reels and iron ring, charging jars and rack, the period receiving chassis, the "
          "four-level rack with fourteen valves, test instruments. The guide's flair: one receiver on the bench tuned to 1610 with nothing there, the dial at the top of the band, the speaker "
          "hissing an open channel, no label. Check that the set exists and that its dial reads top-of-band; the hiss belongs to the existing ambient owners."),
         [change("CITY_SHOP_RADIO_SERVICE-001", "P1", "add", "The 1610 set on the bench", objects=["radio_apparatus bench: one receiver with its dial pointer at the top of the band and a speaker (signal family); an open-channel hiss from the existing shop ambience owner at low level"], placement="On the bench's leaf, clear of the ledger stance", signal=SIGNAL_YES, purpose="Shop guide 4 flair: the best single object on the street; Bible III WORS 1610", sources=["art/blender/radio_apparatus.md", "art/blender/radio_bench.md", "design/ORISON_BIBLE.md III"], preserve="Receiving keyboard sessions", acceptance="Bench station shows the pointer at the band's top; no label"),
          change("CITY_SHOP_RADIO_SERVICE-002", "P3", "keep", "Keep the chair and kettle 1927", purpose="Guide: only the signal path is early", acceptance="Unchanged")],
         capture_ids=["shop_radio_service_*", "storm_shop_radio_service_*", "site_rear_radio_service_*"], canon=[C_SHOPS, C_BIBLE_VIII2, C_BIBLE_III], implementation=SHOP_IMPL),
    city("CITY_SHOP_PHOTO_SUPPLIES", GA, "PHOTO SUPPLIES: dear photographs", "East side, sixth bay (5.00 x 6.00 m), awning; the darkroom door with its red lamp", "Nadia on Sundays; Sacha's trade",
         ("Fitted: three expensive cameras and their stand, the counter and glass chamber, rear shelves and cartons, enlargers, trays, tanks, dryer, tripods, flash tins, seven unclaimed portraits "
          "on a rail, fixed glazing, the darkroom's double curtain and actor-controlled red lamp, the receiving cabinet (COUNTY LEAGUE). The guide is built. Remaining: one of the mounted "
          "portraits should be of a building (Nadia is in here more than upstairs), and the unclaimed rail should rhyme with the laundry's wire in age."),
         [change("CITY_SHOP_PHOTO_SUPPLIES-001", "P2", "refine", "One portrait is a building", objects=["photo_portraits rail: replace one generated portrait plate with an architectural plate (a facade silhouette)"], purpose="Shop guide 10 flair; schedules: Nadia", sources=["art/blender/photo_portraits.md"], acceptance="Rail detail station")],
         capture_ids=["shop_photo_supplies_*", "storm_shop_photo_supplies_*", "site_rear_photo_supplies_*"], canon=[C_SHOPS, C_BIBLE_VIII4], implementation=SHOP_IMPL),

    city("CITY_BAR_DESCENT", GH, "The Harukiya descent: street lobby, stair, vestibule and the red door", "The street leaf on the south walk, the 1.6 m shaft with fifteen risers to the -2.80 m landing, the red steel door, the raised lounge deck with the two receiving cabinets immediately left", "everyone who drinks; the player",
         ("Stations: the lobby, stair, deck, the floor surveys of lobby and vestibule (the three DECK stations face the red door and the peeling teal wall at close range and show little of the deck itself; the descent is best read in the STAIR and lobby surveys). Canon (CANONICAL): teal peeling walls, litter on the treads, the soiled red rug, graffiti strata, the fluorescent "
          "ballast hum, the red steel door with closer and kick plate; the two cabinets on the deck. B2 commissions the detritus diorama: layered, meaningful accumulation implying use, neglect, "
          "improvisation, hidden labour or former glamour, never messy as a substitute for design. The player infers compression before release."),
         [change("CITY_BAR_DESCENT-001", "P1", "add", "The detritus diorama on the stair (B2)", objects=["new: on the treads and landing: cans, a crate, paper, a dead token, a sticker strata decal band at hand height, a crushed hat; the red rug's soil mask; a capacity notice and a soda-acid extinguisher on its bracket (1928 retrofits)"], placement="Litter against the stair cheeks leaving the 1.6 m clear; rug at the landing; notice and extinguisher on the landing wall",
                 construction="Static instanced litter from the crate/desktop_stock families; decals; the extinguisher as one native part", materials="tin, paper, felt, brass extinguisher", wear="the rug's centre worn to the warp", lighting="the ballast fluorescent as authored", purpose="Ledger CANONICAL stairwell; B2 commission", sources=["docs/harukiya_reference_notes.md II", "TASKS.md B2"], preserve="Stair collision, the red door's notch and the capsule route", acceptance="Bar route test unchanged; stair station reads the diorama"),
          change("CITY_BAR_DESCENT-002", "P2", "add", "The 1913 and 1919 photographs", objects=["two framed photographs (CharacterMemoryArt) on the landing wall: the block in 1913 and under its first name in 1919 (ledger A0.5)"], purpose="The bar showing the player its own history", sources=["docs/harukiya_reference_notes.md A0.5"], acceptance="Landing station"),
          change("CITY_BAR_DESCENT-003", "P3", "add", "Speakeasy judas window, optional", objects=["red door: a sliding judas panel at 1.6 m"], purpose="Canon finding: Prohibition is not in canon; gated on an owner ruling", acceptance="Only if ruled")],
         capture_ids=["bar_F01_BAR_LT_LOBBY", "bar_F01_BAR_LT_STAIR", "bar_F01_BAR_LT_DECK*", "retail_bar_lob_floor_*", "retail_bar_vest_floor_*"], canon=[C_BAR, "TASKS.md B1-B5"], group_intro=INTRO_BAR,
         implementation={"sources": ["docs/harukiya_reference_notes.md", "design/HARUKIYA_RECONSTRUCTION_BRIEF.md", "game/scripts/building/orison_v2_bar_region.gd"], "dependencies": "B1a footprint ruling: no plan growth", "preserved": "B5 list: teal descent, red steel door, two cabinets left of the entrance, canopy, barrels and pictures, violet felt, practical light", "acceptance": "Bar route test unchanged"}),
    city("CITY_BAR_ROOM", GH, "The Harukiya room: counter, tables, pool, couches, jukebox, darts", "The checkerboard table floor, the long counter under the canopy, the backbar with barrels and pictures, the violet-felt pool table, the couch banks, palms, jukebox and the darts wall", "the Saturday regulars: Lena early, Juno in the back booth, Rhea watching, Teresa by the exit, Cam standing by the door, Jonah holding the room",
         ("Stations: the well, the table lights, the pool, the west bays, the canopy lights, darts, and the floor survey. The gallery, stage, pool, mounts, pipe supports, ceiling smoke film, "
          "furniture, loudspeakers, darts, receiving cabinets and signage are implemented. The room reads as built. The schedules give it its people: Lena mends the corner banquette's split "
          "vinyl (a visible patch), Teresa's seat nearest the exit, Juno's back booth, Cam's standing spot by the door with a beer ring on the dado, Jonah's spot between songs. The remaining "
          "canon items: the tip jar, towel, opener, spike and forgotten pen on the counter; the dead token under cabinet 01; the worn floor arc where players stand; the fuse board and handwash "
          "sign at the service end; the sticky patch with its two flies (C2)."),
         [change("CITY_BAR_ROOM-001", "P1", "add", "Counter service objects", objects=["new: tip jar, bar towel, opener, spike, a forgotten pen, a cash register (not a POS) on the counter; rubber mats behind it (desktop_stock / bar families)"], placement="On the counter top inside the canopy, clear of the three seat zones' stances", purpose="Ledger II inventory: the counter's working surface", sources=["docs/harukiya_reference_notes.md II north side"], preserve="BarSeatZone stances, songbook terminal", acceptance="Canopy station"),
          change("CITY_BAR_ROOM-002", "P2", "add", "Lena's patch on the banquette, Cam's ring by the door", objects=["couch bank corner module: a contrasting vinyl patch; a beer-ring decal on the dado by the entrance"], purpose="Schedules: Lena mends the split vinyl; Cam never sits", acceptance="West bay and deck stations"),
          change("CITY_BAR_ROOM-003", "P2", "add", "Dead token, floor arc, fuse board, handwash sign", objects=["a token under cabinet 01; a worn arc decal where players stand; a knife switch and fuse board at the service end; a handwash notice (Label3D)"], purpose="Ledger II entrance zone and retrofits re-dated to 1928", acceptance="Deck and service-end stations"),
          change("CITY_BAR_ROOM-004", "P3", "add", "Teacups behind the counter, optional speakeasy reading", objects=["a row of teacups on the backbar shelf"], purpose="Canon finding: gated on a Prohibition ruling", acceptance="Only if ruled")],
         capture_ids=["bar_F01_BAR_LT_WELL", "bar_F01_BAR_LT_TAB*", "bar_F01_BAR_LT_POOL", "bar_F01_BAR_LT_WEST*", "bar_F01_BAR_LT_CAN*", "bar_F01_BAR_LT_DARTS", "retail_bar_floor_*"], canon=[C_BAR, C_SCHED, C_OWNER], implementation={"sources": ["art/blender/bar_gallery.md", "art/blender/bar_pool.md", "art/blender/bar_fixture_mounts.md", "art/blender/bar_ceiling_finish.md", "G08-G13 sources"], "dependencies": "A0.4 Japanese content scales with the room: any added fabric must name what it adds on that side (the teacups, if ruled, count)", "preserved": "Seat zones, darts, pool, songbook, jukebox, receivers, lights", "acceptance": "Bar route and furniture tests unchanged"}),
    city("CITY_BAR_STAGE", GH, "The stage: phonautograph, piano, microphone and the lit sign", "The plywood stage at the far end under the lit sign with the curtain folds, the upright piano, the stage microphone, the loudspeakers and the Songbook's phonautograph", "singers; the Songbook",
         ("Stations STAGE0 and STAGE1. G09 (piano and microphone), G10 (phonautograph), G08 (loudspeakers), the stage curtain and the cloth fascia are implemented. The phonautograph is the oldest "
          "thing in the Orison (Bible III.2) and records only; the stage sign is neon. Remaining: the obsolete printed binder and the grimy remote of the ledger's karaoke adaptation become, in "
          "1928, the Songbook's bound book of takes and a brass crank; a chalk setlist board (Label3D) beside the stage; the mic stand's cable taped to the stage edge."),
         [change("CITY_BAR_STAGE-001", "P2", "add", "The bound book of takes and the setlist board", objects=["new: a bound ledger of takes on the terminal's shelf (papers bound variant), a chalk setlist board (Label3D) on the stage pier"], purpose="Bible III.2 the Songbook; ledger karaoke adaptation re-dated", sources=["design/ORISON_BIBLE.md III.2", "docs/songbook_brief.md"], preserve="SongbookTerminalProp and the phonautograph's motion owner", acceptance="Stage station")],
         capture_ids=["bar_F01_BAR_LT_STAGE*"], canon=[C_BAR, "Bible III.2 (the phonautograph)"], implementation={"sources": ["art/blender/bar_stage.md", "G09, G10 sources"], "dependencies": "none", "preserved": "Phonautograph, piano keys, microphone owners", "acceptance": "Bar stage test unchanged"}),
    city("CITY_BAR_WC", GH, "The customer WC", "The tiny customer WC off the bar aisle through a 0.70 m door with a 145-degree open pose; sink with hot/mixed/off", "customers",
         ("Stations WC and WC sink. The retained clearance, the working sink and the door pose are implemented. Ledger: toilet, sink, exposed plumbing, mirror, exhaust, floor drain, mismatched "
          "repairs. Remaining: the mismatched repairs as a timeline (a 1928 pipe clip over a 1912 iron), a cracked mirror, a roller towel, graffiti strata lower than the stair's."),
         [change("CITY_BAR_WC-001", "P2", "add", "Mismatched repairs, cracked mirror, roller towel", objects=["a pipe clip of a different metal on the exposed run; a mirror with a crack decal; a roller towel on a bracket"], purpose="Ledger restroom line; Accord 13", sources=["art/blender/bar_service_access.md"], preserve="Door pose and sink input", acceptance="WC station")],
         capture_ids=["bar_F01_BAR_LT_WC", "bar_F01_BAR_WC_SINK_01"], canon=[C_BAR], implementation={"sources": ["art/blender/bar_service_access.md"], "dependencies": "none", "preserved": "Door, sink", "acceptance": "Bar route WC return unchanged"}),
]
