"""Implementation status per change id, overlaid on the change register.

The builder (build_dossier.py, also `--register-only`) copies `status` and
`owner_notes` from here into change_register.{csv,json,xlsx}. Everything not
listed stays `proposed`. Statuses: proposed, implemented, verified, deferred,
rejected. Each entry names the commit and the evidence that shows the change
in the build; evidence packets live under implementation/<slice>/.
"""

SLICE1 = "implementation/slice1 (captures, batch.json, run receipts)"

STATUS = {
    # ------------------------------------------------------------ slice 1
    "F04_A_VESTIBULE-004": {"status": "verified", "owner_notes": "Blockout purpose text now reads 4A; the sweep caption shows it. " + SLICE1},
    "F04_D_STUDY-001": {"status": "verified", "owner_notes": "F04_D_BED_STORAGE_DOOR leaf_state locked in completion_interiors_source; the sweep's threshold opening was refused (threshold_door: locked) and OrisonV2CompletionInteriorsTest now expects the refusal and skips the closet: with V2_TEST_UNIT=4D the four lock checks pass (implementation/slice1b/receipts). The suite still ends in its kitchen-to-hall leg (12 waypoints), which fails identically on main at 16f1d353 for 1A (38 waypoints, same target) and for 3D on this branch (14 waypoints): the fridge beside the kitchen door blocks the route line, a pre-existing defect flagged separately. On main the 4D leg already failed earlier, at the walk into the closet after opening its door (7 waypoints; implementation/baseline_completion_4D), so the lock removes a broken step rather than adding one. " + SLICE1},
    "BW-012": {"status": "verified", "owner_notes": "2A, 3D, 4D fittings monitor_top false; household_fridges plan instances FridgeIcebox; family rebuilt in Blender; the fabrication batch counts 4 monitors of 18 (test expects 4); 2A native capture and 3D/4D sweep overviews show oak iceboxes. " + SLICE1},
    "F04_D_KITCHEN-003": {"status": "verified", "owner_notes": "Resolved by BW-012: F04_4D_FRIDGE_01 is a dry icebox (F04_D_KITCHEN_OV). " + SLICE1},
    "F04_D_KITCHEN-005": {"status": "verified", "owner_notes": "Keep note closed with the swap above."},
    "F04_D_KITCHEN-004": {"status": "verified", "owner_notes": "Runtime census lists F04_4D_STOVE_01 (orison_v2_stove.gd) with four grates and burner caps at (-10.6, -7.65) in F04_D_KITCHEN; the range mounts. The overview station does not frame it; no data change."},
    "BW-010": {"status": "verified", "owner_notes": "F01_A_MAIN_LT, F03_D_MAIN_LT, F04_D_MAIN_LT: completion lighting kind pendant_shade and fixed_lighting plan variant pendant_shade_rise100; family rebuilt; fixed_lighting validator 5971 checks, 0 failures on rerun (one contextual standing-view failure at F01_BAR_LT_DECK0 on the first run, absent on rerun and in the owner's final receipts); sweep overviews show the pendants. " + SLICE1},
    "F04_D_MAIN-004": {"status": "verified", "owner_notes": "Resolved by BW-010 (F04_D_MAIN_OV). " + SLICE1},
    "F02_C_KITCHEN-004": {"status": "rejected", "owner_notes": "Measured, not a bug: the runtime census records F02_2C_FRIDGE_01 at yaw 90.0 degrees exactly (square to the east wall, 0.46 m off it); the skew in the review tiles is wide-angle perspective near the frame edge. No data change. " + SLICE1},
    "F04_C_KITCHEN-004": {"status": "rejected", "owner_notes": "As F02_C_KITCHEN-004: F04_4C_FRIDGE_01 yaw 90.0 in the runtime census; no clipping in the data. " + SLICE1},
    "F05_C_KITCHEN-004": {"status": "rejected", "owner_notes": "As F02_C_KITCHEN-004: F05_5C_FRIDGE_01 yaw 90.0 in the runtime census. " + SLICE1},
    # ------------------------------------------------------------ water closets, measured (implementation/baths)
    "BW-018": {"status": "rejected", "owner_notes": "Measured, not missing: every one of the 19 water closets instantiates bath_water_closet.glb with LowCistern and RemovableCisternLid visible; the cistern is 0.46 x 0.22 x 0.31 m with its top 0.80 m above the floor and at least 0.11 m clear of every bath wall (sweep census probe, implementation/baths/receipts). The raised lid (top 0.94 m) hides it from front-on stations, which is what the review saw. No data change; a lid-down default in unoccupied flats is a possible P3 follow-up."},
    "F04_A_BATH-003": {"status": "rejected", "owner_notes": "Cistern present (BW-018 measurement: 4A_wc LowCistern visible, 0.42 m clear of the east wall). The curtain/receptor part stays with BW-008."},
    "F05_A_BATH-003": {"status": "rejected", "owner_notes": "Cistern present (BW-018 measurement: 5A_wc LowCistern visible, 0.15 m clear of the south wall). The pipe strip and register parts stay with BW-005 and heating_distribution."},
    "F03_D_BATH-003": {"status": "rejected", "owner_notes": "Not reproduced: the bath sweep at 49e5e3a1 renders 3D_wc's cistern in porcelain (implementation/baths/images/F03_D_BATH_OV.jpg); the magenta face in the review tile was transient."},
    "F04_B_BATH-003": {"status": "verified", "owner_notes": "Keep note confirmed by the same probe: 4B's cistern is the family's low cistern, identical to every other unit."},
    # ------------------------------------------------------------ slice 2 (implementation/slice2)
    "BW-002": {"status": "implemented", "owner_notes": "2C_bed1, 5C_bed1 and 6C_bed1 (with nightstands) removed at their owners (completion source; domestic_furniture_source; blockout anchors); 4C keeps its two beds (re-templated on 5C_bed0). Conversions started with existing variants: 2C session table and chair under the window, 5C pigment table (TableRect09) on the inner wall with a stool, 6C archive table under the window and two shelves on the east wall. Hero props (blanket walls, easel, drying rack, catalogue drawers) stay open on their room entries. Bedding validator expects 19 beds; tables 64, seating 43, storage 45 instances rebuilt. Suites: OrisonV2BeddingTest passes; the fabrication batch for the twelve rebuilt families passes; OrisonV2UpperFurnitureTest stays red on a pre-existing check (mesh material overrides: 394 failures on main at 16f1d353, 400 here, the six new native meshes counted the same way); the C-unit completion route stops at the 2C bath leg exactly as on main."},
    "F02_C_BED2-001": {"status": "implemented", "owner_notes": "Removed with BW-002."},
    "F05_C_BED2-001": {"status": "implemented", "owner_notes": "Removed with BW-002."},
    "F06_C_BED2-001": {"status": "implemented", "owner_notes": "Removed with BW-002."},
    "BW-011": {"status": "implemented", "owner_notes": "DomesticRadio_1A/1D/2C/3D/4C/4D added to domestic_radios_source (families from the 1928 catalogue: radiola table, Crosley Pup, homebrew regenerative); wireless tables (TableRect07 template) added to 1A, 3D and 4D on the south wall between the doors; orison_v2_radios.gd now places 18 units; the apartment batch test expects 18 receivers. DomesticRadioTest passes; in OrisonV2ApartmentBatchTest the new receivers pass their clearance and operator-stance checks, and the only remaining receiver failures are the pre-existing texture-backed-parts check (98 on main for the twelve, 142 for eighteen); the other red groups (46 fixed-furniture collisions, 18 wood, 12 category, 10 plant, 6 coffee, 2 plant) are identical on main."},
    "F01_A_MAIN-001": {"status": "implemented", "owner_notes": "1A_wireless_table at (-12.0, -6.95) yaw 180 and DomesticRadio_1A on it (BW-011)."},
    "F01_D_MAIN-003": {"status": "implemented", "owner_notes": "DomesticRadio_1D on the existing 1D_wireless_table (BW-011)."},
    "F01_D_MAIN-001": {"status": "implemented", "owner_notes": "1D_fabric_worktable record and anchor removed; the 1D_story_pattern_board anchor had no consumer and is gone."},
    "F01_D_PRIVATE_HALL-002": {"status": "implemented", "owner_notes": "The 1D_fabric_shelf_01/02 anchors removed (they had no furniture consumer; the review's shelves were the baked template surfaces)."},
    "F04_D_BATH-003": {"status": "implemented", "owner_notes": "F04_D_BATH_SWITCH anchor moved to (-6.1, 1.12, -9.75) yaw 0: the north wall beside the bath door, off the basin wall."},
    "F05_C_BED1-002": {"status": "implemented", "owner_notes": "5C_w0_wardrobe and its stance moved to the bedroom's east wall (3.45, 9.3) facing west; 5C_w1_wardrobe stays in the closet for F05_C_STUDIO-001."},
    "F06_B_ALCOVE-001": {"status": "implemented", "owner_notes": "6B_abed turned to yaw -90 with its head at the west wall (-14.6, 9.9) so the foot faces the hall door; nightstand at the window side (-15.35, 11.2); stances moved."},
    "B1_RESIDENT_STORAGE-003": {"status": "implemented", "owner_notes": "Bay cage labels are single-sided (Label3D double_sided false) on the bay fronts."},
    "F01_VESTIBULE-002": {"status": "implemented", "owner_notes": "Entry sign labels single-sided; no mirrored read through the glass."},
    "ROOF_PUBLIC_CORE-004": {"status": "implemented", "owner_notes": "Lift-drive sign single-sided (the bulkhead finish part stays open)."},
    "BW-009": {"status": "implemented", "owner_notes": "The readability cues' nine ungoverned light pools (blue and orange OmniLights beside the stair on F01-F03, at the 2A/4B doors and the 4B terminal) are gated off in production (show_light_pools false in orison_v2_runtime_root). Remaining leaks, if any, need a capture to name."},
    "F01_PUBLIC_CORE-003": {"status": "implemented", "owner_notes": "The orange-tan plane was the readability cues' WARM light pool on the core wall; gated off with BW-009."},
    "F03_EAST_HALL-003": {"status": "implemented", "owner_notes": "The powder-blue plane was the readability cues' PUBLIC light pool beside the stair; gated off with BW-009."},
    "F05_B_BATH-003": {"status": "rejected", "owner_notes": "Misread: the 'column radiator standing mid-room' is the shower's closed curtain pose (the fluted cream cylinder on its enamel tray); the heating data places no radiator in 5B's bath. The curtain's look is BW-008's item."},
    "F03_B_ALCOVE-001": {"status": "rejected", "owner_notes": "Measured, not a bug: 3B_aw_wardrobe at yaw 0 on the north wall shows its two leaves and knobs to the room and the bed foot (implementation/slice2/images/F03_B_ALCOVE_DT3.jpg); the punchlist's back-to-room reading does not hold at this station. No data change."},
    # ------------------------------------------------------------ slice 3 (implementation/slice3b, implementation/numerals)
    "BW-017": {"status": "verified", "owner_notes": "Twelve flush domes (flush_dome_rise100 at 2.9 m) on the west and east public halls of F02-F06 (two on the 6.1 m halls of F05/F06), each hall on a landlord's switch beside the stair end or the unit door jamb; blockout anchors, room_lighting records, fixed_lighting plan instances and mirror; family rebuilt. Landings and cores (open stair voids) still have no practical: they need a wall sconce placed against the stair geometry and stay open. Verified at 4e589c0c: upper lighting 9,257 checks, 0 failures (the first run's four F05_C standing-capsule failures cleared with the 5C wardrobe and pigment-table moves); the hall sweep overviews show the domes lit and the switches on the wainscot (implementation/slice3b)."},
    "F04_LANDING-003": {"status": "deferred", "owner_notes": "The landing has no ceiling (stair void); a sconce on the core wall is the remaining item after BW-017's hall domes."},
    "F04_WEST_HALL-003": {"status": "verified", "owner_notes": "F04_WEST_HALL_LT dome (BW-017, implementation/slice3b); the terrazzo scale stays with BW-020."},
    "F04_EAST_HALL-003": {"status": "verified", "owner_notes": "F04_EAST_HALL_LT dome (BW-017, implementation/slice3b/images/F04_EAST_HALL_OV.jpg); the transom blow-out stays with BW-016."},
    "F05_WEST_HALL-004": {"status": "verified", "owner_notes": "F05_WEST_HALL_LT_A/_B domes (BW-017, implementation/slice3b/images/F05_WEST_HALL_OV.jpg); the leaf finish stays with BW-016."},
    "BW-022": {"status": "verified", "owner_notes": "Every apartment entry leaf carries an enamel numeral plate (0.11 x 0.075 m porcelain-finish plate, single-sided Label3D numeral in cobalt) on its hall face at 1.6 m, placed by orison_v2_domestic_doors.gd from the door's connected spaces, seated on the leaf's actual painted face by a vertex probe (the panel rails stand proud of the slab). The readability cues' debug portal masses stay off in production, but their floating 2A, 4B and PUBLIC ENTRANCE labels remain: OrisonV2DoorCasingsTest holds every portal to exactly one Label3D child, so retiring them is the test owner's call, not this slice's. Verified at 0b5f8a7b: both door-route suites and OrisonV2DoorCasingsTest exit 0, and the hall sweep shows the enamel plates reading 4B, 2B and 3D on the leaves (implementation/numerals2; the earlier implementation/numerals run showed why the plate had to move onto the panel bed). "},
    "F04_SOUTHWEST_HALL-003": {"status": "verified", "owner_notes": "4D's entry leaf carries its numeral (BW-022). (implementation/numerals2/images/F03_SOUTHWEST_HALL_OV.jpg shows 3D's plate; 4D's leaf carries the same assembly.)"},
    # ------------------------------------------------------------ slice 4 (implementation/slice34)
    "BW-003": {"status": "verified", "owner_notes": "At the family recipes: TableRound03/TableRound10 carry an Edwardian turned oak column on a cruciform base of capped feet (column, feet and base in the variant's wood; worktop unchanged); Sofa195/Sofa210 carry rolled arms over the padded arm; Shelf01/02/04/07 stand on square oak posts with oak rails. Plans record column=turned, arms=rolled, posts=oak. The slab seat cushions and the shelves' painted-bin and tin stock (source surfaces) stay as they were. Verified at 4e589c0c: fabrication batch of the twelve rebuilt families exit 0 (tables 64, seating 43, storage 45 instances), upper lighting 9,257 checks with 0 failures, ten-room sweep with 0 failures; native captures of 2A_din_t, 2A_sofa, 2A_shelf0 and 5A_planshelf and the room overviews are under implementation/slice34."},
    "F05_B_MAIN-005": {"status": "verified", "owner_notes": "5B_din_t is the pedestal form now (BW-003). (implementation/slice34)"},
    "F02_B_PRIVATE_HALL-003": {"status": "verified", "owner_notes": "2B_fabric_shelf_01/02 posts are oak (BW-003). (implementation/slice34)"},
    "F06_C_MAIN-005": {"status": "verified", "owner_notes": "6C_sofa carries rolled arms (BW-003); 6C_cof (Coffee06) is unchanged. (implementation/slice34/images/F06_C_MAIN_OV.jpg)"},
    "F05_A_STUDY-002": {"status": "verified", "owner_notes": "5A_planshelf posts are oak (BW-003); the placeholder blocks on it stay as source stock. (implementation/slice34/images/F05_A_STUDY_OV.jpg)"},
    # ------------------------------------------------------------ slice 5 (implementation/slice5)
    "BW-004": {"status": "verified", "owner_notes": "Root cause: a wall segment is one box finished with its owning space's class, and a wet room owns the shared wall, so the hall or bedroom beyond saw subway tile. orison_v2_blockout.gd now adds a 4 mm far-face skin on every interior wet wall, finished with the neighbouring space's class and cut by the same openings; exterior walls and wet-to-wet walls are left alone; no collision, no new owner. Verified at 67c233a5 and 47d93679: the private-hall overviews of 5A, 4C and 2C read plaster where implementation/skinbase (the pre-skin tree at 9f95732c, same station) still shows the bath's subway tile; the bath interiors keep their tile (implementation/slice5, slice5b). OrisonV2FloorSurfaceTest reports the same 57 failures (bath floor/ceiling face ownership and the roof decks) before and after the skin, byte-identical stderr sets (implementation/floorbase vs slice5), so they pre-exist. A speckled patch at the 5A hall corner in the first capture did not reproduce at the same station in the second run and is a screen-space transient, not geometry."},
    "BW-016": {"status": "verified", "owner_notes": "Room-leaf paints a step lower (door_prop.gd interior palette); the entry leaves keep their darker corridor paints. The panel relief already exists; the transom blow-out over 4A stays open. Verified at 67c233a5: F05_B_VESTIBULE_OV shows the darker entry leaf beside the lighter room leaf with panel relief intact; F05_A_PRIVATE_HALL_OV and F04_C_PRIVATE_HALL_OV read the room leaves without the white blow-out (implementation/slice5)."},
    "BW-014": {"status": "rejected", "owner_notes": "The peephole is a brass lens cylinder (door_prop.gd), not an emitter; the bright disc in the reviews is the lamp's specular on brass. The wainscot relief stays open."},
}
